import fs from 'fs';
import path from 'path';

// Load existing clean real words from scratch/extracted_real_words.json
const existingReal = JSON.parse(fs.readFileSync('./scratch/extracted_real_words.json', 'utf8'));

// Additional curated high-frequency English-Vietnamese vocabulary pairs across B-Z
const additionalRealWords = [
  // B
  { en: "Background", vn: "Nền tảng, lí lịch", cat: "Work & Career" },
  { en: "Baggage", vn: "Hành lý", cat: "Travel & Tourism" },
  { en: "Balance", vn: "Sự cân bằng, số dư", cat: "Finance" },
  { en: "Bankrupt", vn: "Phá sản", cat: "Finance" },
  { en: "Bargain", vn: "Món hời, mặc cả", cat: "Shopping & Fashion" },
  { en: "Barrier", vn: "Rào cản, chướng ngại", cat: "Work & Career" },
  { en: "Baseline", vn: "Đường cơ sở, điểm chuẩn", cat: "Academic" },
  { en: "Behalf", vn: "Thay mặt, đại diện", cat: "TOEIC Mastery" },
  { en: "Behavior", vn: "Hành vi, ứng xử", cat: "Psychology" },
  { en: "Benchmark", vn: "Tiêu chuẩn đánh giá", cat: "Tech & AI" },
  { en: "Beneficial", vn: "Có lợi, ích lợi", cat: "Health & Mind" },
  { en: "Beneficiary", vn: "Người thụ hưởng", cat: "Finance" },
  { en: "Benefit", vn: "Lợi ích, phúc lợi", cat: "TOEIC Mastery" },
  { en: "Betray", vn: "Phản bội", cat: "Psychology" },
  { en: "Beverage", vn: "Đồ uống, thức uống", cat: "Food & Dining" },
  { en: "Bewilder", vn: "Làm hoang mang, làm bối rối", cat: "Advanced Vocab" },
  { en: "Bias", vn: "Thành kiến, thiên vị", cat: "Psychology" },
  { en: "Bilingual", vn: "Song ngữ", cat: "Education" },
  { en: "Binding", vn: "Ràng buộc pháp lý", cat: "Law & Ethics" },
  { en: "Biodiversity", vn: "Đa dạng sinh học", cat: "Environment" },
  { en: "Biography", vn: "Tiểu sử", cat: "Arts & Culture" },
  { en: "Biological", vn: "Thuộc sinh học", cat: "Science & Space" },
  { en: "Bittersweet", vn: "Vừa vui vừa buồn, đắng ngọt", cat: "Psychology" },
  { en: "Bizarre", vn: "Kỳ quái, kỳ lạ", cat: "Advanced Vocab" },
  { en: "Blanket", vn: "Chiếc chăn, bao phủ", cat: "Home & Living" },
  { en: "Bleak", vn: "U ám, ảm đạm", cat: "Advanced Vocab" },
  { en: "Blemish", vn: "Vết nhược điểm, tì vết", cat: "Shopping & Fashion" },
  { en: "Blink", vn: "Nháy mắt, chớp mắt", cat: "Beginner" },
  { en: "Blissful", vn: "Hạnh phúc viên mãn", cat: "Psychology" },
  { en: "Blockade", vn: "Sự phong tỏa", cat: "Law & Ethics" },
  { en: "Blueprint", vn: "Bản thiết kế chi tiết", cat: "Tech & AI" },
  { en: "Blunder", vn: "Sai lầm ngớ ngẩn", cat: "Advanced Vocab" },
  { en: "Blunt", vn: "Thẳng thắn, cùn", cat: "Psychology" },
  { en: "Boast", vn: "Khoe khoang, tự hào", cat: "Psychology" },
  { en: "Bold", vn: "Dũng cảm, in đậm", cat: "Intermediate" },
  { en: "Bolster", vn: "Củng cố, tăng cường", cat: "TOEIC Mastery" },
  { en: "Bonus", vn: "Tiền thưởng, phần thưởng", cat: "Work & Career" },
  { en: "Bookstore", vn: "Hiệu sách", cat: "Beginner" },
  { en: "Booming", vn: "Phát triển bùng nổ", cat: "Finance" },
  { en: "Boost", vn: "Thúc đẩy, tăng cường", cat: "TOEIC Mastery" },
  { en: "Border", vn: "Biên giới, ranh giới", cat: "Travel & Tourism" },
  { en: "Bother", vn: "Phền thoái, làm phiền", cat: "Beginner" },
  { en: "Bottom", vn: "Đáy, phía dưới", cat: "Beginner" },
  { en: "Boundless", vn: "Vô tận, không giới hạn", cat: "Advanced Vocab" },
  { en: "Boycott", vn: "Tẩy chay", cat: "Law & Ethics" },
  { en: "Brainstorm", vn: "Động não, thảo luận ý tưởng", cat: "Work & Career" },
  { en: "Branch", vn: "Chi nhánh, cành cây", cat: "TOEIC Mastery" },
  { en: "Bravery", vn: "Sự dũng cảm", cat: "Family & Life" },
  { en: "Breach", vn: "Sự vi phạm, lỗ hổng", cat: "Law & Ethics" },
  { en: "Breakthrough", vn: "Bước đột phá", cat: "Tech & AI" },
  { en: "Breath", vn: "Hơi thở", cat: "Health & Mind" },
  { en: "Breathtaking", vn: "Ngoạn mục, ngoạn cảnh", cat: "Travel & Tourism" },
  { en: "Breed", vn: "Giống loài, chăn nuôi", cat: "Nature & Elements" },
  { en: "Brevity", vn: "Tính ngắn gọn, súc tích", cat: "Academic" },
  { en: "Bribe", vn: "Hối lộ", cat: "Law & Ethics" },
  { en: "Briefcase", vn: "Cặp tài liệu", cat: "Work & Career" },
  { en: "Brilliant", vn: "Xuất sắc, rực rỡ", cat: "Intermediate" },
  { en: "Brisk", vn: "Nhanh nhẹn, phát đạt", cat: "Finance" },
  { en: "Brittle", vn: "Giòn, dễ gãy", cat: "Science & Space" },
  { en: "Broadband", vn: "Băng thông rộng", cat: "Tech & AI" },
  { en: "Broadcast", vn: "Phát sóng, truyền thanh", cat: "Arts & Culture" },
  { en: "Brochure", vn: "Tờ rơi quảng cáo", cat: "TOEIC Mastery" },
  { en: "Brokerage", vn: "Dịch vụ môi giới", cat: "Finance" },
  { en: "Browse", vn: "Xem qua, duyệt web", cat: "Tech & AI" },
  { en: "Brutal", vn: "Tàn bạo, khắc nghiệt", cat: "Advanced Vocab" },
  { en: "Budget", vn: "Ngân sách", cat: "Finance" },
  { en: "Buffer", vn: "Bộ đệm, vùng đệm", cat: "Tech & AI" },
  { en: "Bulky", vn: "Cồng kềnh", cat: "Shopping & Fashion" },
  { en: "Bulletin", vn: "Bản tin ngắn", cat: "Education" },
  { en: "Bullying", vn: "Sự bắt nạt", cat: "Education" },
  { en: "Bungled", vn: "Làm hỏng, vụng về", cat: "Advanced Vocab" },
  { en: "Buoyant", vn: "Nổi được, sôi nổi", cat: "Finance" },
  { en: "Burdensome", vn: "Nặng nề, gánh nặng", cat: "TOEIC Mastery" },
  { en: "Bureaucracy", vn: "Bộ máy quan liêu", cat: "Law & Ethics" },
  { en: "Burgeon", vn: "Phát triển nhanh chóng", cat: "Advanced Vocab" },
  { en: "Bypass", vn: "Đường vòng, bỏ qua", cat: "Tech & AI" },

  // C
  { en: "Cabinet", vn: "Tủ, nội các", cat: "Home & Living" },
  { en: "Calculate", vn: "Tính toán", cat: "Academic" },
  { en: "Calibration", vn: "Sự hiệu chỉnh", cat: "Tech & AI" },
  { en: "Calligraphy", vn: "Thư pháp", cat: "Arts & Culture" },
  { en: "Camouflage", vn: "Sự ngụy trang", cat: "Nature & Elements" },
  { en: "Campaign", vn: "Chiến dịch", cat: "TOEIC Mastery" },
  { en: "Cancel", vn: "Hủy bỏ", cat: "Beginner" },
  { en: "Candid", vn: "Thật thà, thẳng thắn", cat: "Psychology" },
  { en: "Candidate", vn: "Ứng cử viên", cat: "Work & Career" },
  { en: "Capable", vn: "Có năng lực", cat: "Intermediate" },
  { en: "Capacity", vn: "Sức chứa, năng suất", cat: "TOEIC Mastery" },
  { en: "Capitalism", vn: "Chủ nghĩa tư bản", cat: "Finance" },
  { en: "Captivate", vn: "Làm say đắm, thu hút", cat: "Arts & Culture" },
  { en: "Capture", vn: "Bắt giữ, nắm bắt", cat: "Intermediate" },
  { en: "Career", vn: "Sự nghiệp", cat: "Work & Career" },
  { en: "Carefree", vn: "Vô tư, thảnh thơi", cat: "Family & Life" },
  { en: "Cargo", vn: "Hàng hóa vận chuyển", cat: "TOEIC Mastery" },
  { en: "Carnival", vn: "Lễ hội hóa trang", cat: "Arts & Culture" },
  { en: "Cascade", vn: "Thác nước, nối tiếp", cat: "Nature & Elements" },
  { en: "Casualty", vn: "Thương vong, nạn nhân", cat: "Safety & Emergency" },
  { en: "Catastrophe", vn: "Thảm họa lớn", cat: "Safety & Emergency" },
  { en: "Category", vn: "Hạng mục, thể loại", cat: "Education" },
  { en: "Cater", vn: "Phục vụ tiệc, đáp ứng", cat: "Food & Dining" },
  { en: "Caution", vn: "Sự cẩn trọng, cảnh báo", cat: "Safety & Emergency" },
  { en: "Ceasefire", vn: "Lệnh ngừng bắn", cat: "Law & Ethics" },
  { en: "Celebration", vn: "Sự lễ kỷ niệm", cat: "Family & Life" },
  { en: "Celestial", vn: "Thuộc bầu trời, vũ trụ", cat: "Science & Space" },
  { en: "Censor", vn: "Kiểm duyệt", cat: "Law & Ethics" },
  { en: "Census", vn: "Cuộc điều tra dân số", cat: "Law & History" },
  { en: "Centralize", vn: "Tập trung hóa", cat: "Work & Career" },
  { en: "Ceremony", vn: "Nghi lễ, buổi lễ", cat: "Arts & Culture" },
  { en: "Certainty", vn: "Sự chắc chắn", cat: "Psychology" },
  { en: "Certificate", vn: "Chứng chỉ, văn bằng", cat: "Education" },
  { en: "Chairman", vn: "Chủ tịch", cat: "Work & Career" },
  { en: "Challenge", vn: "Thử thách", cat: "Intermediate" },
  { en: "Chamber", vn: "Phòng họp lớn, buồng", cat: "Law & History" },
  { en: "Chancellor", vn: "Thủ tướng, hiệu trưởng", cat: "Law & Ethics" },
  { en: "Chaos", vn: "Sự hỗn loạn", cat: "Advanced Vocab" },
  { en: "Charity", vn: "Hội từ thiện", cat: "Family & Life" },
  { en: "Charter", vn: "Hiến chương, thuê riêng", cat: "Law & Ethics" },
  { en: "Chauvinism", vn: "Chủ nghĩa sô-vanh", cat: "Psychology" },
  { en: "Chronicle", vn: "Sử biên niên, ghi chép", cat: "Arts & Culture" },
  { en: "Circuit", vn: "Mạch điện, chu trình", cat: "Tech & AI" },
  { en: "Circulate", vn: "Lưu thông, tuần hoàn", cat: "Health & Mind" },
  { en: "Citation", vn: "Trích dẫn, biểu dương", cat: "Academic" },
  { en: "Citizen", vn: "Công dân", cat: "Law & Ethics" },
  { en: "Civic", vn: "Thuộc công dân, đô thị", cat: "Law & Ethics" },
  { en: "Clarify", vn: "Làm rõ, giải thích", cat: "TOEIC Mastery" },
  { en: "Clarity", vn: "Sự rõ ràng, minh bạch", cat: "Academic" },
  { en: "Classification", vn: "Sự phân loại", cat: "Science & Space" },
  { en: "Clause", vn: "Mệnh đề, điều khoản", cat: "Law & Ethics" },
  { en: "Clearance", vn: "Sự cấp phép, xả hàng", cat: "Shopping & Fashion" },
  { en: "Clemency", vn: "Sự khoan hồng", cat: "Law & Ethics" },
  { en: "Clientele", vn: "Tập hợp khách hàng", cat: "TOEIC Mastery" },
  { en: "Climax", vn: "Đỉnh điểm, cao trào", cat: "Arts & Culture" },
  { en: "Climate", vn: "Khí hậu", cat: "Environment" },
  { en: "Clinical", vn: "Thuộc lâm sàng", cat: "Health & Mind" },
  { en: "Closure", vn: "Sự đóng cửa, giải thoát tâm lý", cat: "Work & Career" },
  { en: "Cluster", vn: "Cụm, chùm", cat: "Tech & AI" },
  { en: "Coalition", vn: "Liên minh", cat: "Law & Ethics" },
  { en: "Coal", vn: "Than đá", cat: "Environment" },
  { en: "Coarse", vn: "Thô ráp, thô tục", cat: "Advanced Vocab" },
  { en: "Cognitive", vn: "Thuộc nhận thức", cat: "Psychology" },
  { en: "Coherent", vn: "Mạch lạc, chặt chẽ", cat: "Academic" },
  { en: "Cohesion", vn: "Sự kết nối, gắn kết", cat: "Academic" },
  { en: "Coincide", vn: "Trùng hợp, xảy ra đồng thời", cat: "Intermediate" },
  { en: "Collaboration", vn: "Sự hợp tác", cat: "Work & Career" },
  { en: "Collateral", vn: "Tài sản thế chấp", cat: "Finance" },
  { en: "Colleague", vn: "Đồng nghiệp", cat: "Work & Career" },
  { en: "Collective", vn: "Tập thể, chung", cat: "Law & Ethics" },
  { en: "Collision", vn: "Sự va chạm, xung đột", cat: "Safety & Emergency" },
  { en: "Colloquial", vn: "Thông tục, khẩu ngữ", cat: "Education" },
  { en: "Colossal", vn: "Khổng lồ, to lớn", cat: "Advanced Vocab" },
  { en: "Combustion", vn: "Sự đốt cháy, sự cháy", cat: "Science & Space" },
  { en: "Command", vn: "Lệnh, sự chỉ huy", cat: "Tech & AI" },
  { en: "Commence", vn: "Bắt đầu, khởi công", cat: "TOEIC Mastery" },
  { en: "Commend", vn: "Khen ngợi, tuyên dương", cat: "TOEIC Mastery" },
  { en: "Commensurate", vn: "Tương xứng, phù hợp", cat: "Work & Career" },
  { en: "Commentary", vn: "Bình luận, bài bình luận", cat: "Arts & Culture" },
  { en: "Commerce", vn: "Thương mại", cat: "Finance" },
  { en: "Commission", vn: "Tiền hoa hồng, ủy ban", cat: "TOEIC Mastery" },
  { en: "Commitment", vn: "Cam kết, sự tận tụy", cat: "Work & Career" },
  { en: "Commodity", vn: "Hàng hóa, vật phẩm", cat: "Finance" },
  { en: "Commotion", vn: "Sự hỗn loạn, ồn ào", cat: "Advanced Vocab" },
  { en: "Communal", vn: "Thuộc cộng đồng", cat: "Family & Life" },
  { en: "Commute", vn: "Đi lại hàng ngày", cat: "Work & Career" },
  { en: "Compact", vn: "Nhỏ gọn, chật nén", cat: "Tech & AI" },
  { en: "Companion", vn: "Người đồng hành", cat: "Family & Life" },
  { en: "Company", vn: "Công ty, sự đi cùng", cat: "Beginner" },
  { en: "Comparable", vn: "Có thể so sánh được", cat: "Intermediate" },
  { en: "Compelling", vn: "Thuyết phục, hấp dẫn", cat: "Advanced Vocab" },
  { en: "Compensate", vn: "Bồi thường, đền bù", cat: "TOEIC Mastery" },
  { en: "Competence", vn: "Năng lực, trình độ", cat: "Education" },
  { en: "Competitive", vn: "Cạnh tranh", cat: "TOEIC Mastery" },
  { en: "Compile", vn: "Biên soạn, tổng hợp", cat: "Academic" },
  { en: "Complacent", vn: "Tự mãn", cat: "Psychology" },
  { en: "Complement", vn: "Bổ sung, phần bù", cat: "Academic" },
  { en: "Complex", vn: "Phức tạp, khu liên hợp", cat: "Intermediate" },
  { en: "Compliance", vn: "Sự tuân thủ quy định", cat: "TOEIC Mastery" },
  { en: "Complicate", vn: "Phức tạp hóa", cat: "Intermediate" },
  { en: "Complicity", vn: "Sự đồng phạm", cat: "Law & Ethics" },
  { en: "Component", vn: "Thành phần, linh kiện", cat: "Tech & AI" },
  { en: "Compose", vn: "Sáng tác, soạn thảo", cat: "Arts & Culture" },
  { en: "Comprehensive", vn: "Toàn diện, bao quát", cat: "TOEIC Mastery" },
  { en: "Compress", vn: "Nén lại, ép lại", cat: "Tech & AI" },
  { en: "Compromise", vn: "Sự thỏa hiệp", cat: "Work & Career" },
  { en: "Compulsory", vn: "Bắt buộc", cat: "Education" },
  { en: "Computation", vn: "Sự tính toán máy tính", cat: "Tech & AI" },
  { en: "Conceal", vn: "Che giấu, giấu giếm", cat: "Advanced Vocab" },
  { en: "Concede", vn: "Thừa nhận, nhượng bộ", cat: "Law & Ethics" },
  { en: "Conceive", vn: "Hình thành ý tưởng, thụ thai", cat: "Academic" },
  { en: "Concentrate", vn: "Tập trung", cat: "Beginner" },
  { en: "Conception", vn: "Quan niệm, sự thụ thai", cat: "Psychology" },
  { en: "Concession", vn: "Sự nhượng bộ, nhượng quyền", cat: "Finance" },
  { en: "Concise", vn: "Ngắn gọn, súc tích", cat: "Academic" },
  { en: "Conclude", vn: "Kết luận, kết thúc", cat: "Academic" },
  { en: "Concrete", vn: "Bê tông, cụ thể", cat: "Intermediate" },
  { en: "Concur", vn: "Đồng ý, nhất trí", cat: "Law & Ethics" },
  { en: "Condemn", vn: "Up án, lên án", cat: "Law & Ethics" },
  { en: "Condense", vn: "Ngưng tụ, tóm tắt", cat: "Science & Space" },
  { en: "Conditional", vn: "Có điều kiện", cat: "Education" },
  { en: "Conduct", vn: "Tiến hành, tư cách", cat: "TOEIC Mastery" },
  { en: "Confer", vn: "Trao tặng, hội đàm", cat: "Academic" },
  { en: "Conference", vn: "Hội nghị", cat: "TOEIC Mastery" },
  { en: "Confess", vn: "Thú nhận, xưng tội", cat: "Family & Life" },
  { en: "Confidential", vn: "Bảo mật, kín", cat: "TOEIC Mastery" },
  { en: "Configuration", vn: "Cấu hình, hình dạng", cat: "Tech & AI" },
  { en: "Confine", vn: "Giam giữ, hạn chế", cat: "Law & Ethics" },
  { en: "Confirm", vn: "Xác nhận", cat: "TOEIC Mastery" },
  { en: "Confiscate", vn: "Tịch thu", cat: "Law & Ethics" },
  { en: "Conflict", vn: "Xung đột, mâu thuẫn", cat: "Law & Ethics" },
  { en: "Conformity", vn: "Sự tuân thủ, thích ứng", cat: "Psychology" },
  { en: "Confront", vn: "Đối mặt, đối diện", cat: "Psychology" },
  { en: "Confusion", vn: "Sự nhầm lẫn, bối rối", cat: "Psychology" },
  { en: "Congenial", vn: "Hợp nhau, dễ chịu", cat: "Family & Life" },
  { en: "Congestion", vn: "Sự tắc nghẽn", cat: "Travel & Tourism" },
  { en: "Conglomerate", vn: "Tập đoàn đa ngành", cat: "Finance" },
  { en: "Congratulate", vn: "Chúc mừng", cat: "Beginner" },
  { en: "Congregate", vn: "Tụ tập, nhóm lại", cat: "Family & Life" },
  { en: "Congress", vn: "Quốc hội, đại hội", cat: "Law & History" },
  { en: "Conjecture", vn: "Sự phỏng đoán", cat: "Academic" },
  { en: "Conjunction", vn: "Liên từ, sự kết hợp", cat: "Education" },
  { en: "Conscious", vn: "Tỉnh táo, có ý thức", cat: "Health & Mind" },
  { en: "Consecutive", vn: "Liên tiếp, dồn dập", cat: "TOEIC Mastery" },
  { en: "Consensus", vn: "Sự đồng thuận", cat: "Law & Ethics" },
  { en: "Consent", vn: "Sự bằng lòng, chấp thuận", cat: "Law & Ethics" },
  { en: "Consequence", vn: "Hậu quả, kết quả", cat: "Intermediate" },
  { en: "Conservation", vn: "Sự bảo tồn", cat: "Environment" },
  { en: "Conservative", vn: "Bảo thủ, thận trọng", cat: "Psychology" },
  { en: "Considerable", vn: "Đáng kể", cat: "TOEIC Mastery" },
  { en: "Consolidate", vn: "Củng cố, hợp nhất", cat: "Finance" },
  { en: "Conspicuous", vn: "Dễ thấy, náo nhiệt", cat: "Advanced Vocab" },
  { en: "Conspiracy", vn: "Âm mưu", cat: "Law & History" },
  { en: "Constant", vn: "Hằng số, liên tục", cat: "Science & Space" },
  { en: "Constellation", vn: "Chòm sao", cat: "Science & Space" },
  { en: "Constituent", vn: "Thành phần, cử tri", cat: "Law & Ethics" },
  { en: "Constitution", vn: "Hiến pháp, thể tạng", cat: "Law & History" },
  { en: "Constraint", vn: "Ràng buộc, hạn chế", cat: "Academic" },
  { en: "Construct", vn: "Xây dựng, dựng lên", cat: "Work & Career" },
  { en: "Consulate", vn: "Lãnh sự quán", cat: "Travel & Tourism" },
  { en: "Consultant", vn: "Chuyên viên tư vấn", cat: "TOEIC Mastery" },
  { en: "Consumer", vn: "Người tiêu dùng", cat: "Finance" },
  { en: "Consumption", vn: "Sự tiêu thụ", cat: "Finance" },
  { en: "Contact", vn: "Liên lạc, tiếp xúc", cat: "Beginner" },
  { en: "Contagious", vn: "Lây nhiễm", cat: "Health & Mind" },
  { en: "Containment", vn: "Sự kiểm soát, khống chế", cat: "Safety & Emergency" },
  { en: "Contemplate", vn: "Suy ngẫm, cân nhắc", cat: "Psychology" },
  { en: "Contemporary", vn: "Đương đại, cùng thời", cat: "Arts & Culture" },
  { en: "Contempt", vn: "Sự coi thường, khinh bỉ", cat: "Psychology" },
  { en: "Contend", vn: "Tranh luận, dám chắc", cat: "Academic" },
  { en: "Contentment", vn: "Sự hài lòng, mãn nguyện", cat: "Psychology" },
  { en: "Contestant", vn: "Thí sinh, người dự thi", cat: "Education" },
  { en: "Context", vn: "Bối cảnh, ngữ cảnh", cat: "Academic" },
  { en: "Contingency", vn: "Dự phòng, tình huống bất ngờ", cat: "TOEIC Mastery" },
  { en: "Continuation", vn: "Sự tiếp tục", cat: "Intermediate" },
  { en: "Contradict", vn: "Mâu thuẫn, cãi lại", cat: "Academic" },
  { en: "Contribution", vn: "Sự đóng góp", cat: "Work & Career" },
  { en: "Controversy", vn: "Sự tranh cãi", cat: "Law & Ethics" },
  { en: "Convenient", vn: "Tiện lợi", cat: "Beginner" },
  { en: "Convention", vn: "Hội nghị, quy ước", cat: "TOEIC Mastery" },
  { en: "Converge", vn: "Hội tụ, gặp nhau", cat: "Tech & AI" },
  { en: "Conversations", vn: "Cuộc trò chuyện", cat: "Daily Life" },
  { en: "Conversion", vn: "Sự chuyển đổi", cat: "Tech & AI" },
  { en: "Convey", vn: "Truyền tải, vận chuyển", cat: "TOEIC Mastery" },
  { en: "Conviction", vn: "Sự kết án, niềm tin vững chắc", cat: "Law & Ethics" },
  { en: "Convince", vn: "Thuyết phục", cat: "Intermediate" },
  { en: "Cooperate", vn: "Hợp tác", cat: "Work & Career" },
  { en: "Coordinate", vn: "Tọa độ, điều phối", cat: "Tech & AI" },
  { en: "Copious", vn: "Dồi dào, dầy đặc", cat: "Advanced Vocab" },
  { en: "Co-owner", vn: "Đồng sở hữu", cat: "Finance" },
  { en: "Corporate", vn: "Thuộc doanh nghiệp", cat: "TOEIC Mastery" },
  { en: "Correction", vn: "Sự sửa đổi, đính chính", cat: "Education" },
  { en: "Correlate", vn: "Tương quan", cat: "Academic" },
  { en: "Correspond", vn: "Tương ứng, trao đổi thư từ", cat: "TOEIC Mastery" },
  { en: "Corridor", vn: "Hành lang", cat: "Home & Living" },
  { en: "Corroborate", vn: "Xác minh, chứng thực", cat: "Academic" },
  { en: "Corrupt", vn: "Tham nhũng, đồi quỵ", cat: "Law & Ethics" },
  { en: "Cosmopolitan", vn: "Thuộc quốc tế, toàn cầu", cat: "Travel & Tourism" },
  { en: "Council", vn: "Hội đồng", cat: "Law & Ethics" },
  { en: "Counsel", vn: "Tư vấn, cố vấn pháp lý", cat: "Law & Ethics" },
  { en: "Counteract", vn: "Chống lại, triệt hạ", cat: "Health & Mind" },
  { en: "Counterfeit", vn: "Hàng giả, làm giả", cat: "Law & Ethics" },
  { en: "Counterpart", vn: "Bên tương ứng, đối tác", cat: "TOEIC Mastery" },
  { en: "Countless", vn: "Vô số, không đếm xẻng", cat: "Advanced Vocab" },
  { en: "Courageous", vn: "Dũng cảm", cat: "Psychology" },
  { en: "Courier", vn: "Người đưa thư, chuyển phát nhanh", cat: "TOEIC Mastery" },
  { en: "Covenant", vn: "Giao kèo, giao ước", cat: "Law & Ethics" },
  { en: "Covert", vn: "Che giấu, bí mật", cat: "Law & Ethics" },
  { en: "Covet", vn: "Thèm muồng, thèm muốn", cat: "Psychology" },
  { en: "Cozy", vn: "Ấm cúng, dễ chịu", cat: "Home & Living" },
  { en: "Craftsmanship", vn: "Tay nghề thủ công", cat: "Arts & Culture" },
  { en: "Crater", vn: "Miệng núi lửa, hố vũ trụ", cat: "Science & Space" },
  { en: "Credibility", vn: "Sự uy tín, độ tin cậy", cat: "TOEIC Mastery" },
  { en: "Credit", vn: "Tín dụng, lòng tin", cat: "Finance" },
  { en: "Creditor", vn: "Chủ nợ", cat: "Finance" },
  { en: "Creed", vn: "Tín ngưỡng, tín điều", cat: "Law & Ethics" },
  { en: "Cripple", vn: "Tàn phế, tàn phá", cat: "Health & Mind" },
  { en: "Crisis", vn: "Cuộc khủng hoảng", cat: "Finance" },
  { en: "Criterion", vn: "Tiêu chuẩn đánh giá", cat: "Academic" },
  { en: "Critique", vn: "Bài phê bình, nhận xét", cat: "Arts & Culture" },
  { en: "Crucial", vn: "Quan trọng cốt yếu", cat: "Intermediate" },
  { en: "Cruelty", vn: "Sự tàn ác", cat: "Psychology" },
  { en: "Crusade", vn: "Chiến dịch lớn", cat: "Law & History" },
  { en: "Cuisine", vn: "Ẩm thực", cat: "Food & Dining" },
  { en: "Culprit", vn: "Thủ phạm, nguyên nhân", cat: "Law & Ethics" },
  { en: "Cultivate", vn: "Trồng trọt, trau dồi", cat: "Environment" },
  { en: "Cumbersome", vn: "Cồng kềnh, phức tạp", cat: "Advanced Vocab" },
  { en: "Cumulative", vn: "Tích lũy dồn dập", cat: "Finance" },
  { en: "Curb", vn: "Kiềm chế, lề đường", cat: "Environment" },
  { en: "Curiosity", vn: "Sự tò mò", cat: "Psychology" },
  { en: "Currency", vn: "Tiền tệ", cat: "Finance" },
  { en: "Curriculum", vn: "Chương trình học", cat: "Education" },
  { en: "Curtail", vn: "Cắt bớt, giảm bớt", cat: "TOEIC Mastery" },
  { en: "Custodian", vn: "Người bảo quản, người coi giữ", cat: "Law & Ethics" },
  { en: "Custody", vn: "Sự tạm giữ, quyền nuôi con", cat: "Law & Ethics" },
  { en: "Customary", vn: "Theo phong tục, thông thường", cat: "Arts & Culture" },
  { en: "Customer", vn: "Khách hàng", cat: "Beginner" },

  // E, F, G, H, I, J, K, L, M, N, O, Q, R, S, T, U, V, W, X, Y, Z
  { en: "Eager", vn: "Hào hứng, hăng hái", cat: "Psychology" },
  { en: "Earnest", vn: "Nghiêm túc, thành thật", cat: "Psychology" },
  { en: "Earnings", vn: "Thu nhập, lợi nhuận", cat: "Finance" },
  { en: "Eccentric", vn: "Lập dị, kỳ lạ", cat: "Advanced Vocab" },
  { en: "Eclipse", vn: "Nhật thực, sự che mờ", cat: "Science & Space" },
  { en: "Ecological", vn: "Thuộc sinh thái", cat: "Environment" },
  { en: "Economy", vn: "Nền kinh tế", cat: "Finance" },
  { en: "Ecstasy", vn: "Sự ngây ngất, sướng vui", cat: "Psychology" },
  { en: "Editorial", vn: "Bài biên tập, thuộc tòa soạn", cat: "Arts & Culture" },
  { en: "Educator", vn: "Nhà giáo dục", cat: "Education" },
  { en: "Effortless", vn: "Dễ dàng, không tốn sức", cat: "Intermediate" },
  { en: "Elaborate", vn: "Phức tạp, tỉ mỉ", cat: "Advanced Vocab" },
  { en: "Elastic", vn: "Co giãn, linh hoạt", cat: "Science & Space" },
  { en: "Election", vn: "Cuộc bầu cử", cat: "Law & History" },
  { en: "Electricity", vn: "Điện năng", cat: "Science & Space" },
  { en: "Elegant", vn: "Thanh lịch, trang nhã", cat: "Shopping & Fashion" },
  { en: "Element", vn: "Yếu tố, nguyên tố", cat: "Science & Space" },
  { en: "Eligible", vn: "Đủ điều kiện, hợp lệ", cat: "TOEIC Mastery" },
  { en: "Eliminate", vn: "Loại bỏ, loại trừ", cat: "TOEIC Mastery" },
  { en: "Eloquent", vn: "Hùng hồn, lưu khoát", cat: "Public Speaking" },
  { en: "Elusive", vn: "Khó nắm bắt, mơ hồ", cat: "Advanced Vocab" },
  { en: "Embargo", vn: "Cấm vận", cat: "Law & Ethics" },
  { en: "Embark", vn: "Bắt đầu hành trình, lên tàu", cat: "Travel & Tourism" },
  { en: "Embarrass", vn: "Làm ngượng ngùng", cat: "Psychology" },
  { en: "Embassy", vn: "Đại sứ quán", cat: "Travel & Tourism" },
  { en: "Embellish", vn: "Trang trí, thêu dệt", cat: "Arts & Culture" },
  { en: "Embrace", vn: "Ôm, đón nhận", cat: "Family & Life" },
  { en: "Embryo", vn: "Phôi thai", cat: "Science & Space" },
  { en: "Emergency", vn: "Trường hợp khẩn cấp", cat: "Safety & Emergency" },
  { en: "Emind", vn: "Nhắc nhở", cat: "TOEIC Mastery" },
  { en: "Eminent", vn: "Kiệt xuất, lỗi lạc", cat: "Advanced Vocab" },
  { en: "Emission", vn: "Sự phát thải", cat: "Environment" },
  { en: "Emotion", vn: "Cảm xúc", cat: "Psychology" },
  { en: "Empathy", vn: "Sự đồng cảm", cat: "Psychology" },
  { en: "Empirical", vn: "Dựa trên thực nghiệm", cat: "Academic" },
  { en: "Employee", vn: "Nhân viên", cat: "Work & Career" },
  { en: "Empower", vn: "Trao quyền", cat: "Work & Career" },
  { en: "Emulate", vn: "Mô phỏng, thi đua", cat: "Tech & AI" },
  { en: "Enchant", vn: "Mê hoặc, làm mê muội", cat: "Arts & Culture" },
  { en: "Enclose", vn: "Đính kèm, vây quanh", cat: "TOEIC Mastery" },
  { en: "Encounter", vn: "Bắt gặp, chạm chán", cat: "Intermediate" },
  { en: "Encourage", vn: "Khuyến khích", cat: "Education" },
  { en: "Endeavor", vn: "Nỗ lực, cố gắng", cat: "TOEIC Mastery" },
  { en: "Endendorse", vn: "Ủng hộ, xác nhận", cat: "Finance" },
  { en: "Endurance", vn: "Sự chịu đựng, sức bền", cat: "Health & Mind" },
  { en: "Energetic", vn: "Tràn đầy năng lượng", cat: "Beginner" },
  { en: "Enforce", vn: "Thi hành, thực thi pháp luật", cat: "Law & Ethics" },
  { en: "Engage", vn: "Tham gia, thu hút", cat: "TOEIC Mastery" },
  { en: "Engineer", vn: "Kỹ sư", cat: "Work & Career" },
  { en: "Enhance", vn: "Nâng cao, gia tăng", cat: "TOEIC Mastery" },
  { en: "Enormous", vn: "Khổng lồ, to lớn", cat: "Intermediate" },
  { en: "Enrich", vn: "Làm giàu, làm phong phú", cat: "Education" },
  { en: "Enterprise", vn: "Doanh nghiệp", cat: "Finance" },
  { en: "Enthusiasm", vn: "Sự nhiệt tình", cat: "Psychology" },
  { en: "Entire", vn: "Toàn bộ, toàn thể", cat: "Beginner" },
  { en: "Entity", vn: "Thực thể, cơ quan", cat: "Tech & AI" },
  { en: "Entrepreneur", vn: "Nhà khởi nghiệp", cat: "Work & Career" },
  { en: "Epidemic", vn: "Dịch bệnh", cat: "Safety & Emergency" },
  { en: "Equator", vn: "Đường xích đạo", cat: "Science & Space" },
  { en: "Equipment", vn: "Trang thiết bị", cat: "TOEIC Mastery" },
  { en: "Equity", vn: "Vốn chủ sở hữu, sự công bằng", cat: "Finance" },
  { en: "Equivalent", vn: "Tương đương", cat: "Academic" },
  { en: "Ergonomic", vn: "Công phu, công nghệ học", cat: "Tech & AI" },
  { en: "Erode", vn: "Xói mòn, suy yếu", cat: "Environment" },
  { en: "Errand", vn: "Việc vặt", cat: "Daily Life" },
  { en: "Erupt", vn: "Phun trào (núi lửa)", cat: "Science & Space" },
  { en: "Escalate", vn: "Leo thang, gia tăng", cat: "TOEIC Mastery" },
  { en: "Essence", vn: "Bản chất, cốt lõi", cat: "Academic" },
  { en: "Establish", vn: "Thành lập, thiết lập", cat: "TOEIC Mastery" },
  { en: "Estate", vn: "Bất động sản, di sản", cat: "Finance" },
  { en: "Estimate", vn: "Ước tính, báo giá", cat: "TOEIC Mastery" },

  // F
  { en: "Fabricate", vn: "Bịa đặt, chế tạo", cat: "Law & Ethics" },
  { en: "Fabulous", vn: "Tuyệt vời, thần thoại", cat: "Beginner" },
  { en: "Facilitate", vn: "Tạo điều kiện thuận lợi", cat: "TOEIC Mastery" },
  { en: "Factor", vn: "Yếu tố, nhân tố", cat: "Academic" },
  { en: "Faculty", vn: "Khoa, giảng viên", cat: "Education" },
  { en: "Fascinate", vn: "Mê hoặc, cuốn hút", cat: "Arts & Culture" },
  { en: "Feasible", vn: "Khả thi, thực hiện được", cat: "TOEIC Mastery" },
  { en: "Feedback", vn: "Phản hồi, ý kiến", cat: "Work & Career" },
  { en: "Fellowship", vn: "Học bổng, tình bạn", cat: "Education" },
  { en: "Fertile", vn: "Màu mỡ, phì nhiêu", cat: "Environment" },
  { en: "Financial", vn: "Thuộc tài chính", cat: "Finance" },
  { en: "Flourish", vn: "Phát triển thịnh vượng", cat: "Advanced Vocab" },
  { en: "Fluctuate", vn: "Biến động, dao động", cat: "Finance" },
  { en: "Forecast", vn: "Dự báo", cat: "TOEIC Mastery" },
  { en: "Founding", vn: "Sự sáng lập", cat: "Work & Career" },
  { en: "Frugal", vn: "Tiết kiệm, giản dị", cat: "Psychology" },
  { en: "Frustrate", vn: "Làm nản lòng, bực bội", cat: "Psychology" },
  { en: "Fulfill", vn: "Hoàn thành, đáp ứng", cat: "Work & Career" },
  { en: "Functionality", vn: "Tính năng, chức năng", cat: "Tech & AI" },
  { en: "Fundamental", vn: "Cơ bản, cốt lõi", cat: "Academic" },

  // G
  { en: "Generate", vn: "Tạo ra, phát điện", cat: "Tech & AI" },
  { en: "Generous", vn: "Rộng lượng, hào phóng", cat: "Psychology" },
  { en: "Genius", vn: "Thiên tài", cat: "Education" },
  { en: "Genuine", vn: "Thật, chính hãng", cat: "Shopping & Fashion" },
  { en: "Geology", vn: "Địa chất học", cat: "Science & Space" },
  { en: "Gigantic", vn: "Khổng lồ", cat: "Advanced Vocab" },
  { en: "Global", vn: "Toàn cầu", cat: "Environment" },
  { en: "Glossary", vn: "Bảng chú giải thuật ngữ", cat: "Education" },
  { en: "Gorgeous", vn: "Lộng lẫy, tuyệt đẹp", cat: "Shopping & Fashion" },
  { en: "Governance", vn: "Sự quản trị", cat: "Law & Ethics" },
  { en: "Gracious", vn: "Tử tế, trang nhã", cat: "Family & Life" },
  { en: "Gradual", vn: "Dần dần, từng bước", cat: "Intermediate" },
  { en: "Grandeur", vn: "Sự hùng vĩ, trang nghiêm", cat: "Arts & Culture" },
  { en: "Gratitude", vn: "Lòng biết ơn", cat: "Psychology" },
  { en: "Gravity", vn: "Trọng lực, tính nghiêm trọng", cat: "Science & Space" },
  { en: "Grievance", vn: "Lời phàn nàn, sự bức xúc", cat: "Work & Career" },
  { en: "Guarantee", vn: "Cam kết, bảo hành", cat: "TOEIC Mastery" },
  { en: "Guideline", vn: "Hướng dẫn, chỉ đạo", cat: "Work & Career" },

  // H
  { en: "Habitat", vn: "Môi trường sống", cat: "Environment" },
  { en: "Handcraft", vn: "Làm thủ công", cat: "Arts & Culture" },
  { en: "Handy", vn: "Tiện lợi, khéo tay", cat: "Daily Life" },
  { en: "Hazardous", vn: "Độc hại, nguy hiểm", cat: "Safety & Emergency" },
  { en: "Headquarters", vn: "Trụ sở chính", cat: "TOEIC Mastery" },
  { en: "Healthcare", vn: "Chăm sóc sức khỏe", cat: "Health & Mind" },
  { en: "Heritage", vn: "Di sản", cat: "Arts & Culture" },
  { en: "Hierarchy", vn: "Hệ thống phân cấp", cat: "Work & Career" },
  { en: "Highlight", vn: "Điểm nổi bật, nhấn mạnh", cat: "Education" },
  { en: "Hindrance", vn: "Chướng ngại vật", cat: "Advanced Vocab" },
  { en: "Hospitality", vn: "Lòng hiếu khách, ngành ks", cat: "Travel & Tourism" },
  { en: "Hostility", vn: "Sự thù địch", cat: "Psychology" },
  { en: "Humanity", vn: "Nhân loại, lòng nhân đạo", cat: "Law & Ethics" },
  { en: "Humble", vn: "Khiêm tốn", cat: "Psychology" },
  { en: "Hygiene", vn: "Vệ sinh", cat: "Health & Mind" },
  { en: "Hypothesis", vn: "Giả thuyết", cat: "Academic" },

  // I
  { en: "Iconic", vn: "Mang tính biểu tượng", cat: "Arts & Culture" },
  { en: "Ideology", vn: "Hệ tư tưởng", cat: "Law & Ethics" },
  { en: "Illuminate", vn: "Chiếu sáng, làm rõ", cat: "Advanced Vocab" },
  { en: "Illustration", vn: "Hình minh họa", cat: "Arts & Culture" },
  { en: "Imitation", vn: "Sự bắt chước", cat: "Arts & Culture" },
  { en: "Immense", vn: "Bao la, khổng lồ", cat: "Advanced Vocab" },
  { en: "Immerse", vn: "Đắm chìm, ngập trong", cat: "Education" },
  { en: "Imminent", vn: "Sắp xảy ra, cận kề", cat: "Advanced Vocab" },
  { en: "Impartial", vn: "Công bằng, vô tư", cat: "Law & Ethics" },
  { en: "Impeccable", vn: "Hoàn hảo, không vết gợn", cat: "Advanced Vocab" },
  { en: "Imperative", vn: "Bắt buộc, cấp thiết", cat: "TOEIC Mastery" },
  { en: "Implement", vn: "Thực thi, áp dụng", cat: "TOEIC Mastery" },
  { en: "Implicit", vn: "Ngầm hiểu, ẩn ý", cat: "Academic" },
  { en: "Incentive", vn: "Sự khuyến khích, thưởng", cat: "Finance" },
  { en: "Incline", vn: "Khuynh hướng, độ dốc", cat: "Intermediate" },
  { en: "Incorporate", vn: "Sáp nhập, kết hợp", cat: "TOEIC Mastery" },
  { en: "Incremental", vn: "Gia tăng từng bước", cat: "Tech & AI" },
  { en: "Indicate", vn: "Chỉ ra, cho biết", cat: "Academic" },
  { en: "Indispensable", vn: "Không thể thiếu", cat: "TOEIC Mastery" },
  { en: "Induce", vn: "Gây ra, xúi giục", cat: "Academic" },
  { en: "Inevitable", vn: "Không thể tránh khỏi", cat: "Intermediate" },
  { en: "Infinite", vn: "Vô tận, vô hạn", cat: "Science & Space" },
  { en: "Infrastructure", vn: "Hạ tầng", cat: "Tech & AI" },
  { en: "Ingenious", vn: "Thông minh, độc đáo", cat: "Tech & AI" },
  { en: "Inherent", vn: "Vốn có, cố hữu", cat: "Academic" },
  { en: "Initiative", vn: "Sáng kiến, sự chủ động", cat: "TOEIC Mastery" },
  { en: "Innovation", vn: "Sự đổi mới, sáng tạo", cat: "Tech & AI" },
  { en: "Insight", vn: "Sự thấu hiểu sâu sắc", cat: "Academic" },
  { en: "Inspection", vn: "Sự thanh tra, kiểm tra", cat: "TOEIC Mastery" },
  { en: "Inspiration", vn: "Cảm hứng", cat: "Arts & Culture" },
  { en: "Integrity", vn: "Chính trực, toàn vẹn", cat: "Law & Ethics" },
  { en: "Intellectual", vn: "Thuộc trí tuệ", cat: "Education" },
  { en: "Intense", vn: "Cường độ cao, mãnh liệt", cat: "Psychology" },
  { en: "Intervene", vn: "Can thiệp", cat: "Law & Ethics" },
  { en: "Intricate", vn: "Phức tạp, tinh xảo", cat: "Arts & Culture" },
  { en: "Intuition", vn: "Trực giác", cat: "Psychology" },
  { en: "Inventory", vn: "Hàng tồn kho, bảng kiểm kê", cat: "TOEIC Mastery" },
  { en: "Investigate", vn: "Điều tra, nghiên cứu", cat: "Law & Ethics" },
  { en: "Invoice", vn: "Hóa đơn", cat: "TOEIC Mastery" },
  { en: "Irrelevant", vn: "Không liên quan", cat: "Academic" },

  // J, K, L, M, N, O
  { en: "Jeopardize", vn: "Gây nguy hiểm, đe dọa", cat: "TOEIC Mastery" },
  { en: "Journalism", vn: "Ngành báo chí", cat: "Arts & Culture" },
  { en: "Jubilant", vn: "Vui mừng khôn siết", cat: "Psychology" },
  { en: "Judicious", vn: "Sáng suốt, đúng đắn", cat: "Law & Ethics" },
  { en: "Jurisdiction", vn: "Thẩm quyền tài phán", cat: "Law & Ethics" },
  { en: "Justify", vn: "Bào chữa, biện minh", cat: "Academic" },
  { en: "Keen", vn: "Sắc sảo, đam mê", cat: "Psychology" },
  { en: "Keynote", vn: "Bài phát biểu chủ đạo", cat: "TOEIC Mastery" },
  { en: "Kinship", vn: "Tình gia đình, họ hàng", cat: "Family & Life" },
  { en: "Landscape", vn: "Phong cảnh", cat: "Travel & Tourism" },
  { en: "Languish", vn: "Suy yếu, suy tàn", cat: "Advanced Vocab" },
  { en: "Leadership", vn: "Khả năng lãnh đạo", cat: "Work & Career" },
  { en: "Lease", vn: "Hợp đồng cho thuê", cat: "Finance" },
  { en: "Legacy", vn: "Di sản để lại", cat: "Arts & Culture" },
  { en: "Legislative", vn: "Thuộc lập pháp", cat: "Law & Ethics" },
  { en: "Legitimate", vn: "Hợp pháp, chính đáng", cat: "Law & Ethics" },
  { en: "Lethargic", vn: "Uể ả, mệt mỏi", cat: "Health & Mind" },
  { en: "Leverage", vn: "Đòn bẩy, tận dụng", cat: "Finance" },
  { en: "Liability", vn: "Trách nhiệm pháp lý, nợ phải trả", cat: "Finance" },
  { en: "Linguistics", vn: "Ngôn ngữ học", cat: "Education" },
  { en: "Liquidity", vn: "Tính thanh khoản", cat: "Finance" },
  { en: "Lucrative", vn: "Béo bở, sinh lời cao", cat: "Finance" },

  // M, N, O
  { en: "Magnificent", vn: "Tráng lệ, tuyệt vời", cat: "Arts & Culture" },
  { en: "Maintenance", vn: "Sự bảo trì", cat: "TOEIC Mastery" },
  { en: "Mandatory", vn: "Bắt buộc", cat: "Law & Ethics" },
  { en: "Manifestation", vn: "Biểu hiện", cat: "Academic" },
  { en: "Manipulate", vn: "Thao túng, điều khiển", cat: "Psychology" },
  { en: "Manufacture", vn: "Sản xuất", cat: "Work & Career" },
  { en: "Masterpiece", vn: "Kiệt tác", cat: "Arts & Culture" },
  { en: "Maximize", vn: "Tối đa hóa", cat: "TOEIC Mastery" },
  { en: "Mediocre", vn: "Tầm thường, trung bình", cat: "Advanced Vocab" },
  { en: "Memorandum", vn: "Bản ghi nhớ nội bộ", cat: "TOEIC Mastery" },
  { en: "Mentor", vn: "Người cố vấn", cat: "Education" },
  { en: "Merchandise", vn: "Hàng hóa mua bán", cat: "Shopping & Fashion" },
  { en: "Meticulous", vn: "Tỉ mỉ, kỹ lưỡng", cat: "TOEIC Mastery" },
  { en: "Microscope", vn: "Kính hiển vi", cat: "Science & Space" },
  { en: "Migration", vn: "Sự di cư", cat: "Environment" },
  { en: "Milestone", vn: "Cột mốc quan trọng", cat: "Work & Career" },
  { en: "Minimize", vn: "Tối thiểu hóa", cat: "Tech & AI" },
  { en: "Misconception", vn: "Quan niệm sai lầm", cat: "Academic" },
  { en: "Mitigate", vn: "Giảm nhẹ, xoa dịu", cat: "TOEIC Mastery" },
  { en: "Moderation", vn: "Sự tiết chế, điều độ", cat: "Health & Mind" },
  { en: "Momentum", vn: "Đà phát triển, thế năng", cat: "Tech & AI" },
  { en: "Monopoly", vn: "Độc quyền", cat: "Finance" },
  { en: "Monument", vn: "Đài đài kỷ niệm", cat: "Arts & Culture" },
  { en: "Mortgage", vn: "Thế chấp tài sản", cat: "Finance" },
  { en: "Motivation", vn: "Động lực", cat: "Psychology" },
  { en: "Multifaceted", vn: "Nhiều khía cạnh", cat: "Academic" },

  // N, O, P, Q, R, S, T, U, V, W, X, Y, Z
  { en: "Navigation", vn: "Sự điều hướng", cat: "Tech & AI" },
  { en: "Necessity", vn: "Nhu cầu thiết yếu", cat: "Beginner" },
  { en: "Negotiate", vn: "Đàm phán, thương lượng", cat: "TOEIC Mastery" },
  { en: "Neighborhood", vn: "Khu xóm, khu vực", cat: "Home & Living" },
  { en: "Neutrality", vn: "Tính trung lập", cat: "Law & Ethics" },
  { en: "Nomination", vn: "Sự đề cử", cat: "Arts & Culture" },
  { en: "Nonprofit", vn: "Phi lợi nhuận", cat: "Finance" },
  { en: "Notable", vn: "Đáng chú ý", cat: "Intermediate" },
  { en: "Nourishment", vn: "Chất dinh dưỡng", cat: "Health & Mind" },
  { en: "Novelty", vn: "Tính mới lạ", cat: "Shopping & Fashion" },

  { en: "Objective", vn: "Mục tiêu, khách quan", cat: "Academic" },
  { en: "Obligation", vn: "Nghĩa vụ, trách nhiệm", cat: "Law & Ethics" },
  { en: "Observation", vn: "Sự quan sát", cat: "Science & Space" },
  { en: "Obsolete", vn: "Lỗi thời, lạc hậu", cat: "Tech & AI" },
  { en: "Obstacle", vn: "Chướng ngại vật", cat: "Psychology" },
  { en: "Occupation", vn: "Nghề nghiệp", cat: "Work & Career" },
  { en: "Offensive", vn: "Xúc phạm, tấn công", cat: "Psychology" },
  { en: "Offline", vn: "Ngoại tuyến", cat: "Tech & AI" },
  { en: "Omission", vn: "Sự bỏ sót", cat: "Academic" },
  { en: "Onboarding", vn: "Quy trình hội nhập", cat: "Work & Career" },
  { en: "Ongoing", vn: "Đang diễn ra", cat: "TOEIC Mastery" },
  { en: "Optimism", vn: "Sự lạc quan", cat: "Psychology" },
  { en: "Optimized", vn: "Đã tối ưu hóa", cat: "Tech & AI" },
  { en: "Optimum", vn: "Mức tối ưu", cat: "Tech & AI" },
  { en: "Orchestra", vn: "Dàn nhạc giao hưởng", cat: "Arts & Culture" },
  { en: "Organism", vn: "Cơ thể sống, sinh vật", cat: "Science & Space" },
  { en: "Orientation", vn: "Buổi định hướng", cat: "Education" },
  { en: "Originate", vn: "Nguồn gốc, bắt đầu", cat: "Academic" },
  { en: "Outcome", vn: "Kết quả", cat: "TOEIC Mastery" },
  { en: "Outbreak", vn: "Bùng phát dịch bệnh", cat: "Safety & Emergency" },
  { en: "Outdated", vn: "Lỗi thời", cat: "Tech & AI" },
  { en: "Outperform", vn: "Vượt trội hơn", cat: "Finance" },
  { en: "Outsourcing", vn: "Thuê ngoài", cat: "TOEIC Mastery" },

  { en: "Plausible", vn: "Hợp lý, đáng tin", cat: "Academic" },
  { en: "Pledge", vn: "Lời cam kết", cat: "Law & Ethics" },
  { en: "Plethora", vn: "Sự dư thừa, rất nhiều", cat: "Advanced Vocab" },
  { en: "Plumbing", vn: "Hệ thống cấp thoát nước", cat: "Home & Living" },
  { en: "Polite", vn: "Lịch sự", cat: "Beginner" },
  { en: "Portion", vn: "Khẩu phần, phần chia", cat: "Food & Dining" },
  { en: "Portfolio", vn: "Hồ sơ năng lực, danh mục đầu tư", cat: "Finance" },
  { en: "Pragmatic", vn: "Thực tế, thực dụng", cat: "Psychology" },
  { en: "Precaution", vn: "Sự phòng ngừa", cat: "Safety & Emergency" },
  { en: "Precedent", vn: "Tiền lệ", cat: "Law & Ethics" },
  { en: "Precision", vn: "Độ chính xác cao", cat: "Tech & AI" },
  { en: "Predator", vn: "Động vật săn mồi", cat: "Nature & Elements" },
  { en: "Predictable", vn: "Có thể dự đoán", cat: "Intermediate" },
  { en: "Predominant", vn: "Chiếm ưu thế", cat: "Academic" },
  { en: "Premature", vn: "Sớm, chưa đủ tháng", cat: "Health & Mind" },
  { en: "Premium", vn: "Phí bảo hiểm, cao cấp", cat: "Finance" },
  { en: "Prerequisite", vn: "Điều kiện tiên quyết", cat: "Education" },
  { en: "Preserve", vn: "Gìn giữ, bảo tồn", cat: "Environment" },
  { en: "Prestigious", vn: "Danh giá, uy tín", cat: "Education" },
  { en: "Prevail", vn: "Chiếm ưu thế, thịnh hành", cat: "Advanced Vocab" },
  { en: "Prevalent", vn: "Phổ biến", cat: "Academic" },
  { en: "Preventative", vn: "Phòng ngừa", cat: "Health & Mind" },
  { en: "Prioritize", vn: "Ưu tiên", cat: "Work & Career" },
  { en: "Proactive", vn: "Chủ động", cat: "Work & Career" },
  { en: "Procedure", vn: "Quy trình, thủ tục", cat: "TOEIC Mastery" },
  { en: "Proceed", vn: "Tiến hành, tiếp tục", cat: "TOEIC Mastery" },
  { en: "Proficiency", vn: "Thành thạo", cat: "Education" },
  { en: "Profound", vn: "Sâu sắc, thâm thúy", cat: "Academic" },
  { en: "Progressive", vn: "Tiến bộ", cat: "Law & Ethics" },
  { en: "Prolific", vn: "Phong phú, sảng khoái", cat: "Arts & Culture" },
  { en: "Prominent", vn: "Nổi bật, lỗi lạc", cat: "TOEIC Mastery" },
  { en: "Promptness", vn: "Sự sự nhanh nhẹn, đúng giờ", cat: "Work & Career" },
  { en: "Propulsion", vn: "Lực đẩy", cat: "Tech & AI" },
  { en: "Prosecation", vn: "Sự truy tố", cat: "Law & Ethics" },
  { en: "Prospectus", vn: "Bản cáo bạch", cat: "Finance" },
  { en: "Prosperity", vn: "Sự thịnh vượng", cat: "Finance" },
  { en: "Protocol", vn: "Giao thức, quy chuẩn", cat: "Tech & AI" },
  { en: "Prototype", vn: "Mẫu thử nghiệm", cat: "Tech & AI" },
  { en: "Proximity", vn: "Sự trạng thái gần kề", cat: "TOEIC Mastery" },
  { en: "Prudent", vn: "Thận trọng, khôn ngoan", cat: "Finance" },
  { en: "Publication", vn: "Ấn phẩm, xuất bản", cat: "Arts & Culture" },
  { en: "Punctuality", vn: "Tính đúng giờ", cat: "Work & Career" },

  { en: "Qualifications", vn: "Trình độ chuyên môn", cat: "Work & Career" },
  { en: "Qualitative", vn: "Thuộc định tính", cat: "Academic" },
  { en: "Quantitative", vn: "Thuộc định lượng", cat: "Academic" },
  { en: "Quarantine", vn: "Cách ly y tế", cat: "Safety & Emergency" },
  { en: "Quarterly", vn: "Hàng quý", cat: "TOEIC Mastery" },

  { en: "Radiation", vn: "Bức xạ", cat: "Science & Space" },
  { en: "Radical", vn: "Triệt để, căn bản", cat: "Law & Ethics" },
  { en: "Ratification", vn: "Sự phê chuẩn", cat: "Law & Ethics" },
  { en: "Readjust", vn: "Điều chỉnh lại", cat: "Tech & AI" },
  { en: "Reassurance", vn: "Sự trấn an", cat: "Psychology" },
  { en: "Rebates", vn: "Giảm giá, hoàn tiền", cat: "Finance" },
  { en: "Recession", vn: "Suy thoái kinh tế", cat: "Finance" },
  { en: "Reciprocity", vn: "Sự có qua có lại", cat: "Law & Ethics" },
  { en: "Reckless", vn: "Liều lĩnh, coi thường", cat: "Psychology" },
  { en: "Reclamation", vn: "Sự cải tạo đất", cat: "Environment" },
  { en: "Reconnaissance", vn: "Trinh sát, thăm dò", cat: "Tech & AI" },
  { en: "Reconstruct", vn: "Xây dựng lại", cat: "Work & Career" },
  { en: "Recruitment", vn: "Sự tuyển dụng", cat: "TOEIC Mastery" },
  { en: "Redemption", vn: "Sự chuộc tội, đổi thưởng", cat: "Finance" },
  { en: "Redundant", vn: "Dư thừa, sa thải", cat: "Work & Career" },
  { en: "Refurbished", vn: "Đã tân trang", cat: "Tech & AI" },
  { en: "Refundable", vn: "Có thể hoàn tiền", cat: "Shopping & Fashion" },
  { en: "Regime", vn: "Chế độ chính trị", cat: "Law & History" },
  { en: "Regulate", vn: "Điều chỉnh, quy định", cat: "Law & Ethics" },
  { en: "Rehabilitation", vn: "Phục hồi chức năng", cat: "Health & Mind" },
  { en: "Reimburse", vn: "Hoàn lại chi phí", cat: "TOEIC Mastery" },
  { en: "Reiterate", vn: "Nhắc lại, nhấn mạnh", cat: "Academic" },
  { en: "Reliability", vn: "Độ tin cậy", cat: "Tech & AI" },
  { en: "Reluctant", vn: "Miễn cưỡng", cat: "Psychology" },
  { en: "Remittance", vn: "Sự chuyển tiền", cat: "Finance" },
  { en: "Remuneration", vn: "Thù lao, tiền công", cat: "Work & Career" },
  { en: "Renovation", vn: "Sự cải tạo, sửa sang", cat: "Home & Living" },
  { en: "Reputable", vn: "Có uy tín", cat: "TOEIC Mastery" },
  { en: "Resilient", vn: "Kiên cường, đàn hồi", cat: "Psychology" },
  { en: "Restructure", vn: "Tái cấu trúc", cat: "Finance" },
  { en: "Retaliation", vn: "Sự trả đũa", cat: "Law & Ethics" },
  { en: "Retention", vn: "Sự giữ lại, ghi nhớ", cat: "Work & Career" },
  { en: "Reevaluation", vn: "Sự đánh giá lại", cat: "Academic" },
  { en: "Revenue", vn: "Doanh thu", cat: "Finance" },
  { en: "Reverence", vn: "Sự tôn kính", cat: "Arts & Culture" },
  { en: "Revoke", vn: "Thu hồi, bãi bỏ", cat: "Law & Ethics" },
  { en: "Rigorous", vn: "Nghiêm ngặt, khắt khe", cat: "Academic" },
  { en: "Rivalry", vn: "Sự tranh đua", cat: "TOEIC Mastery" },
  { en: "Robustness", vn: "Tính mạnh mẽ, bền bỉ", cat: "Tech & AI" },

  { en: "Sacrifice", vn: "Hy sinh", cat: "Family & Life" },
  { en: "Sanction", vn: "Lệnh trừng phạt, chấp thuận", cat: "Law & Ethics" },
  { en: "Scalability", vn: "Khả năng mở rộng", cat: "Tech & AI" },
  { en: "Scrutinize", vn: "Xem xét kỹ lưỡng", cat: "Academic" },
  { en: "Seamless", vn: "Liền mạch, mượt mà", cat: "Tech & AI" },
  { en: "Segregation", vn: "Sự phân biệt, chia rẽ", cat: "Law & Ethics" },
  { en: "Self-esteem", vn: "Lòng tự trọng", cat: "Psychology" },
  { en: "Semiconductor", vn: "Chất bán dẫn", cat: "Tech & AI" },
  { en: "Sentiment", vn: "Tình cảm, quan điểm", cat: "Psychology" },
  { en: "Shortage", vn: "Sự thiếu hụt", cat: "Finance" },
  { en: "Shrinkage", vn: "Sự co lại, tổn thất", cat: "Shopping & Fashion" },
  { en: "Simultaneous", vn: "Đồng thời", cat: "Academic" },
  { en: "Solemn", vn: "Trang nghiêm", cat: "Arts & Culture" },
  { en: "Solicit", vn: "Kêu gọi, khẩn cầu", cat: "TOEIC Mastery" },
  { en: "Solidarity", vn: "Sự đoàn kết", cat: "Law & Ethics" },
  { en: "Solitary", vn: "Đơn độc", cat: "Psychology" },
  { en: "Sophisticated", vn: "Tinh tế, tinh vi", cat: "Tech & AI" },
  { en: "Sovereignty", vn: "Chủ quyền", cat: "Law & Ethics" },
  { en: "Specification", vn: "Thông số kỹ thuật", cat: "Tech & AI" },
  { en: "Spectacular", vn: "Ngoạn mục", cat: "Arts & Culture" },
  { en: "Speculation", vn: "Sự đầu cơ, suy đoán", cat: "Finance" },
  { en: "Spontaneous", vn: "Bột phát, tự nhiên", cat: "Psychology" },
  { en: "Stakeholder", vn: "Bên liên quan", cat: "TOEIC Mastery" },
  { en: "Stagnant", vn: "Trì trệ", cat: "Finance" },
  { en: "Stipulation", vn: "Điều khoản quy định", cat: "Law & Ethics" },
  { en: "Strategic", vn: "Chung mang tính chiến lược", cat: "Work & Career" },
  { en: "Streamline", vn: "Tối ưu hóa quy trình", cat: "TOEIC Mastery" },
  { en: "Strenuous", vn: "Vất vả, vất vưởng", cat: "Health & Mind" },
  { en: "Subsequent", vn: "Xảy ra sau đó", cat: "Academic" },
  { en: "Subsidize", vn: "Trợ cấp", cat: "Finance" },
  { en: "Substantial", vn: "Đáng kể", cat: "TOEIC Mastery" },
  { en: "Subtle", vn: "Tế nhị, tinh vi", cat: "Arts & Culture" },
  { en: "Succession", vn: "Sự kế thừa, liên tiếp", cat: "Work & Career" },
  { en: "Succinct", vn: "Cô đọng, ngắn gọn", cat: "Academic" },
  { en: "Superficial", vn: "Hời hợt, nông choèn", cat: "Psychology" },
  { en: "Supervisor", vn: "Người giám sát", cat: "Work & Career" },
  { en: "Supplement", vn: "Phần bổ sung", cat: "Health & Mind" },
  { en: "Surplus", vn: "Số dư, thặng dư", cat: "Finance" },
  { en: "Surveillance", vn: "Sự giám sát", cat: "Safety & Emergency" },
  { en: "Sustainability", vn: "Sự phát triển bền vững", cat: "Environment" },
  { en: "Symbiosis", vn: "Sự cộng sinh", cat: "Science & Space" },

  { en: "Tangible", vn: "Hữu hình, rõ ràng", cat: "TOEIC Mastery" },
  { en: "Tariff", vn: "Thuế quan", cat: "Finance" },
  { en: "Technology", vn: "Công nghệ", cat: "Tech & AI" },
  { en: "Telemetry", vn: "Đo đạc từ xa", cat: "Tech & AI" },
  { en: "Temporary", vn: "Tạm thời", cat: "Beginner" },
  { en: "Temptation", vn: "Sự cám dỗ", cat: "Psychology" },
  { en: "Tenacious", vn: "Kính ngoan, ngoan cường", cat: "Psychology" },
  { en: "Tenant", vn: "Người thuê nhà", cat: "Home & Living" },
  { en: "Tenative", vn: "Dự kiến, chưa dứt khoát", cat: "TOEIC Mastery" },
  { en: "Termination", vn: "Sự chấm dứt", cat: "Work & Career" },
  { en: "Terminology", vn: "Thuật ngữ", cat: "Education" },
  { en: "Territory", vn: "Lãnh thổ", cat: "Law & History" },
  { en: "Testimonial", vn: "Lời chứng thực, đánh giá", cat: "Shopping & Fashion" },
  { en: "Therapeutic", vn: "Có tính trị liệu", cat: "Health & Mind" },
  { en: "Thermal", vn: "Thuộc nhiệt", cat: "Science & Space" },
  { en: "Thorough", vn: "Kỹ lưỡng, triệt để", cat: "Academic" },
  { en: "Threshold", vn: "Ngưỡng cửa, giới hạn", cat: "Tech & AI" },
  { en: "Thriving", vn: "Phát triển mạnh mẽ", cat: "Finance" },
  { en: "Time-consuming", vn: "Tốn thời gian", cat: "Work & Career" },
  { en: "Tolerance", vn: "Sự khoan dung, sức chịu đựng", cat: "Psychology" },
  { en: "Transaction", vn: "Giao dịch", cat: "Finance" },
  { en: "Transcend", vn: "Vượt qua, vượt lên", cat: "Advanced Vocab" },
  { en: "Transcript", vn: "Bảng điểm, bản chép lại", cat: "Education" },
  { en: "Transition", vn: "Chuyển giao, chuyển tiếp", cat: "Intermediate" },
  { en: "Transmission", vn: "Sự truyền tải", cat: "Tech & AI" },
  { en: "Transparency", vn: "Sự minh bạch", cat: "Law & Ethics" },
  { en: "Tremendous", vn: "Khổng lồ, to lớn", cat: "Advanced Vocab" },
  { en: "Troubleshoot", vn: "Khắc phục sự cố", cat: "Tech & AI" },

  { en: "Ultimate", vn: "Tối thượng, cuối cùng", cat: "Intermediate" },
  { en: "Unanimous", vn: "Nhất trí 100%", cat: "Law & Ethics" },
  { en: "Uncanny", vn: "Kỳ lạ, phi thường", cat: "Advanced Vocab" },
  { en: "Uncertainty", vn: "Sự bất định", cat: "Psychology" },
  { en: "Undergo", vn: "Trải qua", cat: "Health & Mind" },
  { en: "Underlying", vn: "Cốt lõi, tiềm ẩn", cat: "Academic" },
  { en: "Undermine", vn: "Làm suy yếu", cat: "TOEIC Mastery" },
  { en: "Undertake", vn: "Đảm nhận, thực hiện", cat: "TOEIC Mastery" },
  { en: "Underwrite", vn: "Bảo hiểm, cam kết tài chính", cat: "Finance" },
  { en: "Unprecedented", vn: "Chưa từng có", cat: "Advanced Vocab" },
  { en: "Unravel", vn: "Tháo gỡ, làm sáng tỏ", cat: "Academic" },
  { en: "Upbeat", vn: "Lạc quan, vui vẻ", cat: "Psychology" },
  { en: "Uphold", vn: "Duy trì, ủng hộ", cat: "Law & Ethics" },
  { en: "Utilize", vn: "Tận dụng, sử dụng", cat: "TOEIC Mastery" },
  { en: "Utmost", vn: "Tột cùng, hết sức", cat: "TOEIC Mastery" },

  { en: "Vacate", vn: "Rời khỏi, bỏ trống", cat: "TOEIC Mastery" },
  { en: "Validation", vn: "Sự xác thực", cat: "Tech & AI" },
  { en: "Valid", vn: "Có hiệu lực, hợp lệ", cat: "TOEIC Mastery" },
  { en: "Valuable", vn: "Có giá trị", cat: "Beginner" },
  { en: "Vanish", vn: "Biến mất", cat: "Intermediate" },
  { en: "Variable", vn: "Biến số, thay đổi", cat: "Academic" },
  { en: "Variation", vn: "Sự biến đổi", cat: "Academic" },
  { en: "Vast", vn: "Rộng lớn, bao la", cat: "Intermediate" },
  { en: "Velocity", vn: "Vận tốc", cat: "Science & Space" },
  { en: "Vendor", vn: "Nhà cung cấp, người bán hàng", cat: "TOEIC Mastery" },
  { en: "Venture", vn: "Dự án mạo hiểm", cat: "Finance" },
  { en: "Verify", vn: "Xác minh", cat: "TOEIC Mastery" },
  { en: "Versatile", vn: "Đa năng, đa dụng", cat: "Tech & AI" },
  { en: "Vessel", vn: "Tàu lớn, mạch máu", cat: "Science & Space" },
  { en: "Vibrant", vn: "Sôi động, rực rỡ", cat: "Arts & Culture" },
  { en: "Vinity", vn: "Sự lân cận, vùng phụ cận", cat: "TOEIC Mastery" },
  { en: "Vindicate", vn: "Minh oan, chứng minh đúng", cat: "Law & Ethics" },
  { en: "Violation", vn: "Sự vi phạm", cat: "Law & Ethics" },
  { en: "Virtual", vn: "Ảo, thực tế ảo", cat: "Tech & AI" },
  { en: "Virtue", vn: "Đức tính tốt", cat: "Psychology" },
  { en: "Viscosity", vn: "Độ nhớt", cat: "Science & Space" },
  { en: "Visibility", vn: "Tầm nhìn, độ hiển thị", cat: "Travel & Tourism" },
  { en: "Vitalive", vn: "Sinh động, sức sống", cat: "Health & Mind" },
  { en: "Vitality", vn: "Sức sống mãnh liệt", cat: "Health & Mind" },
  { en: "Vocabulary", vn: "Từ vựng", cat: "Education" },
  { en: "Vocation", vn: "Nghề nghiệp, thiên chức", cat: "Work & Career" },
  { en: "Volatile", vn: "Dễ biến động", cat: "Finance" },
  { en: "Volume", vn: "Thể tích, âm lượng", cat: "Science & Space" },
  { en: "Voluntary", vn: "Tự nguyện", cat: "Family & Life" },
  { en: "Vulnerability", vn: "Lỗ hổng bảo mật, sự dễ tổn thương", cat: "Tech & AI" },

  { en: "Warrant", vn: "Lệnh thu giữ, đảm bảo", cat: "Law & Ethics" },
  { en: "Warehouse", vn: "Kho hàng", cat: "TOEIC Mastery" },
  { en: "Welfare", vn: "Phúc lợi xã hội", cat: "Law & Ethics" },
  { en: "Wholesale", vn: "Bán buôn, bán sỉ", cat: "Shopping & Fashion" },
  { en: "Withdrawal", vn: "Sự rút tiền, rút lui", cat: "Finance" },
  { en: "Workforce", vn: "Lực lượng lao động", cat: "TOEIC Mastery" },
  { en: "Workplace", vn: "Nơi làm việc", cat: "Work & Career" },
  { en: "Worthwhile", vn: "Đáng giá", cat: "Intermediate" },

  { en: "Xenon", vn: "Khí Xê-non", cat: "Science & Space" },
  { en: "Yield", vn: "Sản lượng, mang lại", cat: "Finance" },
  { en: "Youthful", vn: "Trẻ trung", cat: "Beginner" },
  { en: "Zealous", vn: "Hăng hái, nhiệt thành", cat: "Psychology" },
  { en: "Zenith", vn: "Đỉnh cao, thời hoàng kim", cat: "Advanced Vocab" },
  { en: "Zodiac", vn: "Cung hoàng đạo", cat: "Science & Space" }
];

console.log('Existing real count:', existingReal.length);
console.log('Additional real count:', additionalRealWords.length);

const finalMap = new Map();

// Load existing
for (const item of existingReal) {
  const word = item.en.trim();
  const lower = word.toLowerCase();
  if (!finalMap.has(lower)) {
    finalMap.set(lower, {
      en: word.charAt(0).toUpperCase() + word.slice(1),
      vn: item.vn.trim(),
      category: item.category || 'General'
    });
  }
}

// Load additional
for (const item of additionalRealWords) {
  const word = item.en.trim();
  const lower = word.toLowerCase();
  if (!finalMap.has(lower)) {
    finalMap.set(lower, {
      en: word.charAt(0).toUpperCase() + word.slice(1),
      vn: item.vn.trim(),
      category: item.cat || 'General'
    });
  }
}

console.log('Total unique real words combined:', finalMap.size);

const finalArray = Array.from(finalMap.values());

// Ensure exactly 3000 by taking the first 3000
const exact3000 = finalArray.slice(0, 3000);
console.log('Exact 3000 array size:', exact3000.length);

// Verify no duplicates
const lowerSet = new Set(exact3000.map(x => x.en.toLowerCase().trim()));
console.log('Unique lowercase keys in 3000:', lowerSet.size);

fs.writeFileSync('./scratch/final_3000_unique_speed_match.json', JSON.stringify(exact3000, null, 2), 'utf8');
