import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Build 3000 core common words data file
const common3000Path = path.join(__dirname, '../src/data/common-3000-words.js');

// Seed words list covering A1-C2, TOEIC, IELTS, and all 25 Life Topics
const categories = [
  "Family & Life", "Home & Living", "Work & Career", "Education", "Food & Dining",
  "Health & Mind", "Travel & Tourism", "Shopping & Style", "Sports & Hobbies",
  "Tech & AI", "Environment", "Finance", "Arts & Culture", "Science & Space",
  "News & Society", "Law & Ethics", "Psychology", "Future & Goals", "Pets & Animals",
  "History & World", "Public Speaking", "Safety & Emergency", "Festivals", "Philosophy"
];

const cefrLevels = ["Beginner", "Intermediate", "Advanced", "TOEIC", "IELTS"];

// Core 3000 English Words Bank generator
console.log("Generating 3000 Core Vocabulary Bank...");

// We will construct 3000 high-frequency English-Vietnamese vocabulary pairs
const wordsList = [];

// Base vocabulary list (1000 high frequency base)
const baseWords = [
  { en: "ability", vn: "khả năng, năng lực", cat: "Education", level: "Intermediate" },
  { en: "able", vn: "có thể, có khả năng", cat: "Education", level: "Beginner" },
  { en: "about", vn: "về, khoảng", cat: "Daily Life", level: "Beginner" },
  { en: "above", vn: "ở trên, phía trên", cat: "Daily Life", level: "Beginner" },
  { en: "abroad", vn: "ở nước ngoài", cat: "Travel & Tourism", level: "Intermediate" },
  { en: "absence", vn: "sự vắng mặt", cat: "Work & Career", level: "Intermediate" },
  { en: "absolute", vn: "tuyệt đối, hoàn toàn", cat: "Psychology", level: "Intermediate" },
  { en: "absorb", vn: "hấp thụ, thẩm thấu", cat: "Science & Space", level: "Intermediate" },
  { en: "abstract", vn: "trừu tượng", cat: "Arts & Culture", level: "Advanced" },
  { en: "abundant", vn: "dồi dào, phong phú", cat: "Environment", level: "Intermediate" },
  { en: "academic", vn: "thuộc học thuật", cat: "Education", level: "Intermediate" },
  { en: "accelerate", vn: "gia tốc, làm nhanh hơn", cat: "Tech & AI", level: "Advanced" },
  { en: "accent", vn: "giọng điệu", cat: "Public Speaking", level: "Intermediate" },
  { en: "accept", vn: "chấp nhận, đồng ý", cat: "Psychology", level: "Beginner" },
  { en: "acceptable", vn: "có thể chấp nhận", cat: "Work & Career", level: "Intermediate" },
  { en: "access", vn: "quyền truy cập, tiếp cận", cat: "Tech & AI", level: "Intermediate" },
  { en: "accessible", vn: "dễ tiếp cận, có thể sử dụng", cat: "Tech & AI", level: "Intermediate" },
  { en: "accident", vn: "tai nạn, sự cố", cat: "Safety & Emergency", level: "Beginner" },
  { en: "accommodate", vn: "cung cấp chỗ ở, đáp ứng", cat: "Travel & Tourism", level: "TOEIC" },
  { en: "accommodation", vn: "chỗ ở, nơi lưu trú", cat: "Travel & Tourism", level: "TOEIC" },
  { en: "accompany", vn: "đi cùng, đồng hành", cat: "Family & Life", level: "Intermediate" },
  { en: "accomplish", vn: "hoàn thành, đạt được", cat: "Work & Career", level: "TOEIC" },
  { en: "accordance", vn: "sự phù hợp, theo đúng", cat: "Law & Ethics", level: "Advanced" },
  { en: "according", vn: "theo như", cat: "News & Society", level: "Beginner" },
  { en: "account", vn: "tài khoản, bản kê khai", cat: "Finance", level: "Beginner" },
  { en: "accountant", vn: "nhân viên kế toán", cat: "Work & Career", level: "TOEIC" },
  { en: "accumulate", vn: "tích lũy, tích tụ", cat: "Finance", level: "Advanced" },
  { en: "accuracy", vn: "sự chính xác", cat: "Science & Space", level: "Intermediate" },
  { en: "accurate", vn: "chính xác, chuẩn xác", cat: "Science & Space", level: "Intermediate" },
  { en: "achieve", vn: "đạt được, thành công", cat: "Future & Goals", level: "Intermediate" },
  { en: "achievement", vn: "thành tựu, kết quả đạt được", cat: "Future & Goals", level: "Intermediate" },
  { en: "acknowledge", vn: "công nhận, thừa nhận", cat: "Public Speaking", level: "Advanced" },
  { en: "acquire", vn: "thu được, có được", cat: "Education", level: "Intermediate" },
  { en: "acquisition", vn: "sự thâu tóm, sự có được", cat: "Finance", level: "TOEIC" },
  { en: "across", vn: "băng qua, phía bên kia", cat: "Travel & Tourism", level: "Beginner" },
  { en: "action", vn: "hành động", cat: "Daily Life", level: "Beginner" },
  { en: "active", vn: "năng động, chủ động", cat: "Health & Mind", level: "Beginner" },
  { en: "activity", vn: "hoạt động", cat: "Daily Life", level: "Beginner" },
  { en: "actor", vn: "nam diễn viên", cat: "Arts & Culture", level: "Beginner" },
  { en: "actress", vn: "nữ diễn viên", cat: "Arts & Culture", level: "Beginner" },
  { en: "actual", vn: "thực tế, thực sự", cat: "Daily Life", level: "Intermediate" },
  { en: "adapt", vn: "thích nghi, thích ứng", cat: "Psychology", level: "Intermediate" },
  { en: "addition", vn: "sự thêm vào, phép cộng", cat: "Education", level: "Beginner" },
  { en: "additional", vn: "bổ sung, thêm vào", cat: "Work & Career", level: "TOEIC" },
  { en: "address", vn: "địa chỉ, bài phát biểu", cat: "Public Speaking", level: "Beginner" },
  { en: "adequate", vn: "đầy đủ, thỏa đáng", cat: "Health & Mind", level: "Intermediate" },
  { en: "adjust", vn: "điều chỉnh, chỉnh sửa", cat: "Tech & AI", level: "Intermediate" },
  { en: "administer", vn: "quản lý, điều hành", cat: "Work & Career", level: "TOEIC" },
  { en: "administration", vn: "sự quản lý, ban quản trị", cat: "Work & Career", level: "TOEIC" },
  { en: "admire", vn: "khâm phục, ngưỡng mộ", cat: "Psychology", level: "Intermediate" },
  { en: "admission", vn: "sự nhận vào, vé vào cửa", cat: "Education", level: "TOEIC" },
  { en: "admit", vn: "thừa nhận, nhận vào", cat: "Law & Ethics", level: "Intermediate" },
  { en: "adopt", vn: "nhận làm con nuôi, áp dụng", cat: "Family & Life", level: "Intermediate" },
  { en: "adult", vn: "người trưởng thành", cat: "Family & Life", level: "Beginner" },
  { en: "advance", vn: "tiến bộ, ứng trước", cat: "Future & Goals", level: "Intermediate" },
  { en: "advanced", vn: "nâng cao, tiên tiến", cat: "Tech & AI", level: "Intermediate" },
  { en: "advantage", vn: "lợi thế, ưu điểm", cat: "Work & Career", level: "Intermediate" },
  { en: "adventure", vn: "chuyến phiêu lưu", cat: "Travel & Tourism", level: "Beginner" },
  { en: "advertisement", vn: "quảng cáo", cat: "Shopping & Style", level: "TOEIC" },
  { en: "advice", vn: "lời khuyên", cat: "Family & Life", level: "Beginner" },
  { en: "advise", vn: "khuyên bảo, tư vấn", cat: "Work & Career", level: "Beginner" },
  { en: "advocate", vn: "ủng hộ, người biện hộ", cat: "Law & Ethics", level: "Advanced" },
  { en: "aesthetic", vn: "thuộc thẩm mỹ", cat: "Arts & Culture", level: "Advanced" },
  { en: "affair", vn: "việc, sự vụ", cat: "News & Society", level: "Intermediate" },
  { en: "affect", vn: "ảnh hưởng đến", cat: "Health & Mind", level: "Intermediate" },
  { en: "affection", vn: "sự yêu thương, tình cảm", cat: "Family & Life", level: "Intermediate" },
  { en: "afford", vn: "có đủ khả năng chi trả", cat: "Finance", level: "Beginner" },
  { en: "affordable", vn: "giá cả phải chăng", cat: "Shopping & Style", level: "TOEIC" },
  { en: "afraid", vn: "lo sợ, e ngại", cat: "Psychology", level: "Beginner" },
  { en: "afternoon", vn: "buổi chiều", cat: "Daily Life", level: "Beginner" },
  { en: "agency", vn: "đại lý, cơ quan", cat: "Work & Career", level: "TOEIC" },
  { en: "agenda", vn: "chương trình nghị sự", cat: "Work & Career", level: "TOEIC" },
  { en: "agent", vn: "người đại diện, tác nhân", cat: "Work & Career", level: "TOEIC" },
  { en: "aggressive", vn: "hung hăng, quyết đoán", cat: "Psychology", level: "Intermediate" },
  { en: "agile", vn: "nhanh nhẹn, linh hoạt", cat: "Tech & AI", level: "Advanced" },
  { en: "agreement", vn: "hợp đồng, sự thỏa thuận", cat: "Law & Ethics", level: "TOEIC" },
  { en: "agriculture", vn: "nông nghiệp", cat: "Environment", level: "Intermediate" },
  { en: "ahead", vn: "phía trước", cat: "Travel & Tourism", level: "Beginner" },
  { en: "aircraft", vn: "máy bay, phi cơ", cat: "Travel & Tourism", level: "Intermediate" },
  { en: "airline", vn: "hãng hàng không", cat: "Travel & Tourism", level: "Beginner" },
  { en: "airport", vn: "sân bay", cat: "Travel & Tourism", level: "Beginner" },
  { en: "alarm", vn: "chuông báo động", cat: "Safety & Emergency", level: "Beginner" },
  { en: "algorithm", vn: "thuật toán", cat: "Tech & AI", level: "Advanced" },
  { en: "alien", vn: "người ngoài hành tinh, xa lạ", cat: "Science & Space", level: "Intermediate" },
  { en: "alignment", vn: "sự căn chỉnh, liên minh", cat: "Tech & AI", level: "Advanced" },
  { en: "allegation", vn: "sự cáo buộc", cat: "Law & Ethics", level: "Advanced" },
  { en: "alleviate", vn: "xoa dịu, giảm bớt", cat: "Health & Mind", level: "Advanced" },
  { en: "alliance", vn: "sự liên minh", cat: "News & Society", level: "Advanced" },
  { en: "allocate", vn: "phân bổ, phân phối", cat: "Finance", level: "TOEIC" },
  { en: "allowance", vn: "tiền trợ cấp, phụ cấp", cat: "Finance", level: "TOEIC" },
  { en: "ally", vn: "đồng minh", cat: "History & World", level: "Intermediate" },
  { en: "almost", vn: "hầu như, gần như", cat: "Daily Life", level: "Beginner" },
  { en: "alone", vn: "một mình, cô đơn", cat: "Psychology", level: "Beginner" },
  { en: "alongside", vn: "bên cạnh, cùng với", cat: "Daily Life", level: "Intermediate" },
  { en: "alphabet", vn: "bảng chữ cái", cat: "Education", level: "Beginner" },
  { en: "alteration", vn: "sự thay đổi, chỉnh sửa", cat: "Shopping & Style", level: "Intermediate" },
  { en: "alternative", vn: "lựa chọn thay thế", cat: "Future & Goals", level: "Intermediate" },
  { en: "altitude", vn: "độ cao so với mặt nước biển", cat: "Science & Space", level: "Advanced" },
  { en: "altogether", vn: "nhìn chung, hoàn toàn", cat: "Daily Life", level: "Intermediate" },
  { en: "altruism", vn: "lòng vị tha", cat: "Philosophy", level: "Advanced" },
  { en: "aluminum", vn: "nhôm", cat: "Science & Space", level: "Intermediate" },
  { en: "amateur", vn: "nghiệp dư", cat: "Sports & Hobbies", level: "Intermediate" },
  { en: "amazement", vn: "sự kinh ngạc", cat: "Psychology", level: "Intermediate" },
  { en: "ambassador", vn: "đại sứ", cat: "News & Society", level: "Advanced" },
  { en: "ambiguity", vn: "sự mơ hồ, không rõ ràng", cat: "Philosophy", level: "Advanced" },
  { en: "ambiguous", vn: "mơ hồ, nhập nhằng", cat: "Philosophy", level: "Advanced" },
  { en: "ambition", vn: "tham vọng, hoài bão", cat: "Future & Goals", level: "Intermediate" },
  { en: "ambitious", vn: "có tham vọng lớn", cat: "Future & Goals", level: "Intermediate" },
  { en: "ambulance", vn: "xe cấp cứu", cat: "Safety & Emergency", level: "Beginner" },
  { en: "amend", vn: "sửa đổi, bổ sung (luật)", cat: "Law & Ethics", level: "Advanced" },
  { en: "amendment", vn: "tu chính án, sự sửa đổi", cat: "Law & Ethics", level: "Advanced" },
  { en: "amenity", vn: "tiện nghi (khách sạn, khu nhà)", cat: "Travel & Tourism", level: "TOEIC" },
  { en: "amiable", vn: "hòa nhã, dễ thương", cat: "Psychology", level: "Advanced" },
  { en: "amount", vn: "số lượng, khoản tiền", cat: "Finance", level: "Beginner" },
  { en: "ample", vn: "dồi dào, dư dả", cat: "Home & Living", level: "Advanced" },
  { en: "analogy", vn: "sự tương tự, phép ví von", cat: "Public Speaking", level: "Advanced" },
  { en: "analyse", vn: "phân tích", cat: "Science & Space", level: "Intermediate" },
  { en: "analysis", vn: "bản phân tích", cat: "Science & Space", level: "Intermediate" },
  { en: "analyst", vn: "chuyên viên phân tích", cat: "Work & Career", level: "TOEIC" },
  { en: "analytical", vn: "có tính phân tích", cat: "Education", level: "Intermediate" },
  { en: "anarchy", vn: "tình trạng vô chính phủ", cat: "History & World", level: "Advanced" },
  { en: "anatomy", vn: "giải phẫu học", cat: "Health & Mind", level: "Advanced" },
  { en: "ancestor", vn: "ông bà tổ tiên", cat: "History & World", level: "Intermediate" },
  { en: "anchorage", vn: "nơi neo đậu tàu thuyền", cat: "Travel & Tourism", level: "Advanced" },
  { en: "ancient", vn: "cổ kính, cổ xưa", cat: "History & World", level: "Intermediate" },
  { en: "anecdote", vn: "câu chuyện phiếm, giai thoại", cat: "Public Speaking", level: "Advanced" },
  { en: "anesthesia", vn: "sự gây mê, thuốc mê", cat: "Health & Mind", level: "Advanced" },
  { en: "angel", vn: "thiên thần", cat: "Festivals", level: "Beginner" },
  { en: "angle", vn: "góc độ", cat: "Science & Space", level: "Intermediate" },
  { en: "anguish", vn: "sự đau đớn dằn dặt", cat: "Psychology", level: "Advanced" },
  { en: "animal", vn: "động vật", cat: "Pets & Animals", level: "Beginner" },
  { en: "animation", vn: "phim hoạt hình, hiệu ứng động", cat: "Arts & Culture", level: "Intermediate" },
  { en: "ankle", vn: "cổ chân", cat: "Health & Mind", level: "Beginner" },
  { en: "anniversary", vn: "ngày kỷ niệm", cat: "Festivals", level: "Intermediate" },
  { en: "announce", vn: "thông báo, tuyên bố", cat: "Public Speaking", level: "Intermediate" },
  { en: "announcement", vn: "lời thông báo", cat: "Work & Career", level: "TOEIC" },
  { en: "annoyance", vn: "sự phiền hà, bực mình", cat: "Psychology", level: "Intermediate" },
  { en: "annual", vn: "hàng năm", cat: "Work & Career", level: "TOEIC" },
  { en: "annually", vn: "mỗi năm một lần", cat: "Work & Career", level: "TOEIC" },
  { en: "anonymous", vn: "ẩn danh, giấu tên", cat: "Tech & AI", level: "Advanced" },
  { en: "answer", vn: "câu trả lời", cat: "Education", level: "Beginner" },
  { en: "antagonism", vn: "sự phản kháng, đối đầu", cat: "Psychology", level: "Advanced" },
  { en: "anticipate", vn: "dự đoán, lường trước", cat: "Future & Goals", level: "TOEIC" },
  { en: "anticipation", vn: "sự mong đợi, dự đoán", cat: "Future & Goals", level: "TOEIC" },
  { en: "anxiety", vn: "sự lo âu, trăn trở", cat: "Psychology", level: "Intermediate" },
  { en: "anxious", vn: "lo âu, sốt sắng", cat: "Psychology", level: "Intermediate" },
  { en: "apartment", vn: "căn hộ", cat: "Home & Living", level: "Beginner" },
  { en: "apologize", vn: "xin lỗi", cat: "Family & Life", level: "Beginner" },
  { en: "apology", vn: "lời xin lỗi", cat: "Family & Life", level: "Intermediate" },
  { en: "apparatus", vn: "thiết bị, bộ máy", cat: "Science & Space", level: "Advanced" },
  { en: "apparent", vn: "rõ ràng, hiển nhiên", cat: "Science & Space", level: "Intermediate" },
  { en: "appeal", vn: "sự lôi cuốn, sự kháng cáo", cat: "Law & Ethics", level: "Intermediate" },
  { en: "appear", vn: "xuất hiện, hình như", cat: "Daily Life", level: "Beginner" },
  { en: "appearance", vn: "nội ngoại hình, sự xuất hiện", cat: "Shopping & Style", level: "Intermediate" },
  { en: "appetite", vn: "sự thèm ăn, khẩu vị", cat: "Food & Dining", level: "Intermediate" },
  { en: "applaud", vn: "vỗ tay tán thưởng", cat: "Arts & Culture", level: "Intermediate" },
  { en: "applause", vn: "tiếng vỗ tay", cat: "Arts & Culture", level: "Intermediate" },
  { en: "apple", vn: "quả táo", cat: "Food & Dining", level: "Beginner" },
  { en: "appliance", vn: "thiết bị gia dụng", cat: "Home & Living", level: "TOEIC" },
  { en: "applicant", vn: "ứng viên xin việc", cat: "Work & Career", level: "TOEIC" },
  { en: "application", vn: "đơn xin việc, ứng dụng", cat: "Tech & AI", level: "Beginner" },
  { en: "apply", vn: "nộp đơn, áp dụng", cat: "Work & Career", level: "Beginner" },
  { en: "appoint", vn: "bổ nhiệm, chỉ định", cat: "Work & Career", level: "TOEIC" },
  { en: "appointment", vn: "cuộc hẹn, sự bổ nhiệm", cat: "Work & Career", level: "TOEIC" },
  { en: "appraisal", vn: "sự đánh giá, thẩm định", cat: "Work & Career", level: "TOEIC" },
  { en: "appreciate", vn: "trân trọng, đánh giá cao", cat: "Family & Life", level: "Intermediate" },
  { en: "appreciation", vn: "sự trân trọng, biết ơn", cat: "Family & Life", level: "Intermediate" },
  { en: "apprehension", vn: "sự e sợ, mối e ngại", cat: "Psychology", level: "Advanced" },
  { en: "approach", vn: "tiếp cận, phương pháp", cat: "Work & Career", level: "Intermediate" },
  { en: "appropriate", vn: "thích hợp, phù hợp", cat: "Education", level: "Intermediate" },
  { en: "approval", vn: "sự phê duyệt, chấp thuận", cat: "Work & Career", level: "TOEIC" },
  { en: "approve", vn: "phê duyệt, tán thành", cat: "Work & Career", level: "TOEIC" },
  { en: "approximate", vn: "xấp xỉ, ước chừng", cat: "Finance", level: "Intermediate" },
  { en: "aptitude", vn: "năng khiếu, tố chất", cat: "Education", level: "Advanced" },
  { en: "aquarium", vn: "thủy cung, bể cá", cat: "Pets & Animals", level: "Beginner" },
  { en: "arbitrary", vn: "tùy hứng, độc đoán", cat: "Philosophy", level: "Advanced" },
  { en: "arbitration", vn: "sự trọng tài phân xử", cat: "Law & Ethics", level: "Advanced" },
  { en: "archaeology", vn: "khảo cổ học", cat: "History & World", level: "Advanced" },
  { en: "architect", vn: "kiến trúc sư", cat: "Home & Living", level: "Intermediate" },
  { en: "architecture", vn: "kiến trúc", cat: "Home & Living", level: "Intermediate" },
  { en: "archive", vn: "kho lưu trữ", cat: "Tech & AI", level: "Intermediate" },
  { en: "arduous", vn: "gian gian, cực khổ", cat: "Work & Career", level: "Advanced" },
  { en: "arguable", vn: "có thể gây tranh cãi", cat: "Public Speaking", level: "Advanced" },
  { en: "argue", vn: "tranh luận, cãi nhau", cat: "Public Speaking", level: "Beginner" },
  { en: "argument", vn: "lập luận, sự tranh cãi", cat: "Public Speaking", level: "Intermediate" },
  { en: "arise", vn: "nảy sinh, mọc lên", cat: "Work & Career", level: "Intermediate" },
  { en: "aristocracy", vn: "tầng lớp quý tộc", cat: "History & World", level: "Advanced" },
  { en: "arithmetic", vn: "số học", cat: "Education", level: "Intermediate" },
  { en: "aroma", vn: "hương thơm dễ chịu", cat: "Food & Dining", level: "Advanced" },
  { en: "arouse", vn: "gợi lên, khơi dậy", cat: "Psychology", level: "Advanced" },
  { en: "arrange", vn: "sắp xếp, thu xếp", cat: "Work & Career", level: "Beginner" },
  { en: "arrangement", vn: "sự sắp đặt, thỏa thuận", cat: "Work & Career", level: "TOEIC" },
  { en: "array", vn: "mảng, danh sách dài", cat: "Tech & AI", level: "Advanced" },
  { en: "arrest", vn: "bắt giữ", cat: "Law & Ethics", level: "Intermediate" },
  { en: "arrival", vn: "sự đến nơi", cat: "Travel & Tourism", level: "Beginner" },
  { en: "arrive", vn: "đến nơi", cat: "Travel & Tourism", level: "Beginner" },
  { en: "arrogant", vn: "kiêu ngạo, ngạo mạn", cat: "Psychology", level: "Intermediate" },
  { en: "article", vn: "bài báo, điều khoản", cat: "News & Society", level: "Beginner" },
  { en: "articulate", vn: "diễn đạt trôi chảy, rõ ràng", cat: "Public Speaking", level: "Advanced" },
  { en: "artificial", vn: "nhân tạo", cat: "Tech & AI", level: "Intermediate" },
  { en: "artist", vn: "họa sĩ, nghệ sĩ", cat: "Arts & Culture", level: "Beginner" },
  { en: "artistic", vn: "có tính nghệ thuật", cat: "Arts & Culture", level: "Intermediate" },
  { en: "ascend", vn: "trèo lên, thăng tiến", cat: "Sports & Hobbies", level: "Advanced" },
  { en: "ascertain", vn: "xác minh, tìm hiểu chắc chắn", cat: "Science & Space", level: "Advanced" },
  { en: "ashamed", vn: "hổ thẹn, xấu hổ", cat: "Psychology", level: "Intermediate" },
  { en: "aside", vn: "sang một bên", cat: "Daily Life", level: "Beginner" },
  { en: "aspect", vn: "khía cạnh", cat: "Education", level: "Intermediate" },
  { en: "aspiration", vn: "khát vọng, ước nguyện", cat: "Future & Goals", level: "Advanced" },
  { en: "aspire", vn: "khao khao, hướng tới", cat: "Future & Goals", level: "Advanced" },
  { en: "assault", vn: "sự tấn công, hành hung", cat: "Law & Ethics", level: "Advanced" },
  { en: "assemble", vn: "lắp ráp, tập hợp", cat: "Work & Career", level: "TOEIC" },
  { en: "assembly", vn: "hội đồng, sự lắp ráp", cat: "Work & Career", level: "TOEIC" },
  { en: "assert", vn: "khẳng định, quả quyết", cat: "Public Speaking", level: "Advanced" },
  { en: "assertion", vn: "sự khẳng định", cat: "Public Speaking", level: "Advanced" },
  { en: "assess", vn: "đánh giá, định giá", cat: "Education", level: "TOEIC" },
  { en: "assessment", vn: "bài đánh giá, sự định giá", cat: "Education", level: "TOEIC" },
  { en: "asset", vn: "tài sản, thế mạnh", cat: "Finance", level: "TOEIC" },
  { en: "assign", vn: "giao việc, phân công", cat: "Work & Career", level: "TOEIC" },
  { en: "assignment", vn: "nhiệm vụ, bài tập", cat: "Education", level: "Beginner" },
  { en: "assimilate", vn: "đồng hóa, tiếp thu", cat: "News & Society", level: "Advanced" },
  { en: "assist", vn: "hỗ trợ, giúp đỡ", cat: "Work & Career", level: "Beginner" },
  { en: "assistance", vn: "sự hỗ trợ", cat: "Work & Career", level: "TOEIC" },
  { en: "assistant", vn: "trợ lý", cat: "Work & Career", level: "Beginner" },
  { en: "associate", vn: "liên kết, đối tác", cat: "Work & Career", level: "TOEIC" },
  { en: "association", vn: "hiệp hội, sự liên kết", cat: "News & Society", level: "TOEIC" },
  { en: "assume", vn: "cho rằng, đảm nhận", cat: "Work & Career", level: "Intermediate" },
  { en: "assumption", vn: "giả định, sự thừa nhận", cat: "Philosophy", level: "Intermediate" },
  { en: "assurance", vn: "sự cam đoan, bảo đảm", cat: "Law & Ethics", level: "TOEIC" },
  { en: "assure", vn: "cam đoan, quả quyết", cat: "Work & Career", level: "TOEIC" },
  { en: "astonish", vn: "làm kinh ngạc", cat: "Psychology", level: "Intermediate" },
  { en: "astronomy", vn: "thiên văn học", cat: "Science & Space", level: "Advanced" },
  { en: "astrophysics", vn: "vật lý thiên văn", cat: "Science & Space", level: "Advanced" },
  { en: "athlete", vn: "vận động viên", cat: "Sports & Hobbies", level: "Beginner" },
  { en: "athletic", vn: "khỏe khoắn, điền kinh", cat: "Sports & Hobbies", level: "Intermediate" },
  { en: "atmosphere", vn: "bầu không khí", cat: "Environment", level: "Intermediate" },
  { en: "atom", vn: "nguyên tử", cat: "Science & Space", level: "Intermediate" },
  { en: "atomic", vn: "thuộc nguyên tử", cat: "Science & Space", level: "Advanced" },
  { en: "atrocity", vn: "tội ác dã man", cat: "History & World", level: "Advanced" },
  { en: "attach", vn: "đính kèm, dán vào", cat: "Tech & AI", level: "Beginner" },
  { en: "attachment", vn: "tệp đính kèm, sự gắn bó", cat: "Tech & AI", level: "TOEIC" },
  { en: "attack", vn: "tấn công", cat: "Safety & Emergency", level: "Beginner" },
  { en: "attain", vn: "đạt được, tới mức", cat: "Future & Goals", level: "TOEIC" },
  { en: "attempt", vn: "nỗ lực, sự thử sức", cat: "Future & Goals", level: "Intermediate" },
  { en: "attend", vn: "tham dự, chú ý", cat: "Work & Career", level: "Beginner" },
  { en: "attendance", vn: "sự có mặt, điểm danh", cat: "Education", level: "TOEIC" },
  { en: "attendant", vn: "tiếp viên, người phục vụ", cat: "Travel & Tourism", level: "TOEIC" },
  { en: "attention", vn: "sự chú ý", cat: "Daily Life", level: "Beginner" },
  { en: "attitude", vn: "thái độ", cat: "Psychology", level: "Intermediate" },
  { en: "attorney", vn: "luật sư", cat: "Law & Ethics", level: "TOEIC" },
  { en: "attract", vn: "thu hút, hấp dẫn", cat: "Shopping & Style", level: "Intermediate" },
  { en: "attraction", vn: "điểm tham quan, sự thu hút", cat: "Travel & Tourism", level: "Intermediate" },
  { en: "attractive", vn: "hấp dẫn, lôi cuốn", cat: "Shopping & Style", level: "Beginner" },
  { en: "attribute", vn: "thuộc tính, cho là do", cat: "Science & Space", level: "Advanced" },
  { en: "auction", vn: "buổi đấu giá", cat: "Finance", level: "TOEIC" },
  { en: "audience", vn: "thính giả, khán giả", cat: "Public Speaking", level: "Intermediate" },
  { en: "audit", vn: "kiểm toán, sự kiểm tra", cat: "Finance", level: "TOEIC" },
  { en: "auditorium", vn: "hội trường lớn", cat: "Education", level: "TOEIC" },
  { en: "augment", vn: "tăng cường, gia tăng", cat: "Tech & AI", level: "Advanced" },
  { en: "authentic", vn: "dính thực, đích thực", cat: "Arts & Culture", level: "Advanced" },
  { en: "authenticity", vn: "tính chân thực", cat: "Arts & Culture", level: "Advanced" },
  { en: "author", vn: "tác giả", cat: "Arts & Culture", level: "Beginner" },
  { en: "authority", vn: "chính quyền, quyền lực", cat: "Law & Ethics", level: "Intermediate" },
  { en: "authorization", vn: "sự cấp phép, ủy quyền", cat: "Law & Ethics", level: "TOEIC" },
  { en: "authorize", vn: "ủy quyền, cho phép", cat: "Law & Ethics", level: "TOEIC" },
  { en: "auto", vn: "tự động, ô tô", cat: "Tech & AI", level: "Beginner" },
  { en: "autobiography", vn: "tự truyện", cat: "Arts & Culture", level: "Advanced" },
  { en: "automate", vn: "tự động hóa", cat: "Tech & AI", level: "TOEIC" },
  { en: "automated", vn: "được tự động hóa", cat: "Tech & AI", level: "TOEIC" },
  { en: "automatic", vn: "tự động", cat: "Tech & AI", level: "Intermediate" },
  { en: "automation", vn: "sự tự động hóa", cat: "Tech & AI", level: "Advanced" },
  { en: "automobile", vn: "xe hơi, ô tô", cat: "Travel & Tourism", level: "Intermediate" },
  { en: "autonomous", vn: "tự chủ, tự hành", cat: "Tech & AI", level: "Advanced" },
  { en: "autonomy", vn: "quyền tự chủ", cat: "Philosophy", level: "Advanced" },
  { en: "availability", vn: "sự có sẵn, khả năng đáp ứng", cat: "Work & Career", level: "TOEIC" },
  { en: "available", vn: "có sẵn, rảnh rỗi", cat: "Work & Career", level: "Beginner" },
  { en: "avalanche", vn: "tuyết lở", cat: "Safety & Emergency", level: "Advanced" },
  { en: "avenue", vn: "đại lộ", cat: "Home & Living", level: "Intermediate" },
  { en: "average", vn: "trung bình", cat: "Math", level: "Beginner" },
  { en: "avert", vn: "ngăn chặn, đẩy lùi", cat: "Safety & Emergency", level: "Advanced" },
  { en: "aviation", vn: "ngành hàng không", cat: "Travel & Tourism", level: "Advanced" },
  { en: "avoid", vn: "tránh né", cat: "Health & Mind", level: "Beginner" },
  { en: "avoidance", vn: "sự tránh né", cat: "Health & Mind", level: "Intermediate" },
  { en: "await", vn: "chờ đợi", cat: "Future & Goals", level: "Intermediate" },
  { en: "awake", vn: "thức giấc, tỉnh táo", cat: "Health & Mind", level: "Beginner" },
  { en: "award", vn: "thưởng, giải thưởng", cat: "Arts & Culture", level: "Beginner" },
  { en: "aware", vn: "nhận thức được", cat: "Psychology", level: "Intermediate" },
  { en: "awareness", vn: "sự nhận thức", cat: "Psychology", level: "Intermediate" },
  { en: "awesome", vn: "tuyệt vời, đáng ngạc nhiên", cat: "Daily Life", level: "Beginner" },
  { en: "awful", vn: "tồi tệ, kinh khủng", cat: "Daily Life", level: "Beginner" },
  { en: "awkward", vn: "ngượng ngùng, vụng về", cat: "Psychology", level: "Intermediate" }
];

console.log("Base Words Loaded:", baseWords.length);
