import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const targetPath = path.join(__dirname, '../src/data/games-data.js');

const expansionCode = `
// Supplemental Large Vocabulary & Verb Transformations Bank for 3000+ Training
export const IRREGULAR_VERBS_BANK = [
  { en: 'arise - arose - arisen', vn: 'nảy sinh, mọc lên', category: 'Irregular Verbs' },
  { en: 'awake - awoke - awoken', vn: 'thức giấc', category: 'Irregular Verbs' },
  { en: 'bear - bore - borne', vn: 'chịu đựng, mang', category: 'Irregular Verbs' },
  { en: 'beat - beat - beaten', vn: 'đánh, đập', category: 'Irregular Verbs' },
  { en: 'become - became - become', vn: 'trở thành', category: 'Irregular Verbs' },
  { en: 'begin - began - begun', vn: 'bắt đầu', category: 'Irregular Verbs' },
  { en: 'bend - bent - bent', vn: 'bẻ cong, cúi xuống', category: 'Irregular Verbs' },
  { en: 'bet - bet - bet', vn: 'đánh cược', category: 'Irregular Verbs' },
  { en: 'bind - bound - bound', vn: 'trói, buộc, gắn kết', category: 'Irregular Verbs' },
  { en: 'bite - bit - bitten', vn: 'cắn, ngoạm', category: 'Irregular Verbs' },
  { en: 'bleed - bled - bled', vn: 'chảy máu', category: 'Irregular Verbs' },
  { en: 'blow - blew - blown', vn: 'thổi', category: 'Irregular Verbs' },
  { en: 'break - broke - broken', vn: 'làm vỡ, bẻ gãy', category: 'Irregular Verbs' },
  { en: 'breed - bred - bred', vn: 'nuôi dưỡng, sinh sản', category: 'Irregular Verbs' },
  { en: 'bring - brought - brought', vn: 'mang lại, mang đến', category: 'Irregular Verbs' },
  { en: 'broadcast - broadcast - broadcast', vn: 'phát sóng truyền hình', category: 'Irregular Verbs' },
  { en: 'build - built - built', vn: 'xây dựng', category: 'Irregular Verbs' },
  { en: 'burn - burnt - burnt', vn: 'đốt cháy', category: 'Irregular Verbs' },
  { en: 'buy - bought - bought', vn: 'mua', category: 'Irregular Verbs' },
  { en: 'catch - caught - caught', vn: 'bắt lấy, nắm bắt', category: 'Irregular Verbs' },
  { en: 'choose - chose - chosen', vn: 'lựa chọn', category: 'Irregular Verbs' },
  { en: 'cling - clung - clung', vn: 'bám chặt, khăng khăng', category: 'Irregular Verbs' },
  { en: 'come - came - come', vn: 'đến, tới', category: 'Irregular Verbs' },
  { en: 'cost - cost - cost', vn: 'có giá là', category: 'Irregular Verbs' },
  { en: 'creep - crept - crept', vn: 'bò, trườn', category: 'Irregular Verbs' },
  { en: 'cut - cut - cut', vn: 'cắt, thái', category: 'Irregular Verbs' },
  { en: 'deal - dealt - dealt', vn: 'giao dịch, giải quyết', category: 'Irregular Verbs' },
  { en: 'dig - dug - dug', vn: 'đào đất', category: 'Irregular Verbs' },
  { en: 'do - did - done', vn: 'làm, thực hiện', category: 'Irregular Verbs' },
  { en: 'draw - drew - drawn', vn: 'vẽ, kéo', category: 'Irregular Verbs' },
  { en: 'dream - dreamt - dreamt', vn: 'mơ ước', category: 'Irregular Verbs' },
  { en: 'drink - drank - drunk', vn: 'uống', category: 'Irregular Verbs' },
  { en: 'drive - drove - driven', vn: 'lái xe', category: 'Irregular Verbs' },
  { en: 'eat - ate - eaten', vn: 'ăn', category: 'Irregular Verbs' },
  { en: 'fall - fell - fallen', vn: 'rơi, ngã', category: 'Irregular Verbs' },
  { en: 'feed - fed - fed', vn: 'cho ăn', category: 'Irregular Verbs' },
  { en: 'feel - felt - felt', vn: 'cảm thấy', category: 'Irregular Verbs' },
  { en: 'fight - fought - fought', vn: 'chiến đấu', category: 'Irregular Verbs' },
  { en: 'find - found - found', vn: 'tìm thấy', category: 'Irregular Verbs' },
  { en: 'flee - fled - fled', vn: 'chạy trốn', category: 'Irregular Verbs' },
  { en: 'fly - flew - flown', vn: 'bay', category: 'Irregular Verbs' },
  { en: 'forbid - forbade - forbidden', vn: 'cấm đoán', category: 'Irregular Verbs' },
  { en: 'forget - forgot - forgotten', vn: 'quên', category: 'Irregular Verbs' },
  { en: 'forgive - forgave - forgiven', vn: 'tha thứ', category: 'Irregular Verbs' },
  { en: 'freeze - froze - frozen', vn: 'đóng băng', category: 'Irregular Verbs' },
  { en: 'get - got - gotten', vn: 'có được, nhận được', category: 'Irregular Verbs' },
  { en: 'give - gave - given', vn: 'cho, tặng', category: 'Irregular Verbs' },
  { en: 'go - went - gone', vn: 'đi', category: 'Irregular Verbs' },
  { en: 'grow - grew - grown', vn: 'phát triển, trồng', category: 'Irregular Verbs' },
  { en: 'hang - hung - hung', vn: 'treo lên', category: 'Irregular Verbs' },
  { en: 'have - had - had', vn: 'có', category: 'Irregular Verbs' },
  { en: 'hear - heard - heard', vn: 'nghe thấy', category: 'Irregular Verbs' },
  { en: 'hide - hid - hidden', vn: 'trốn, giấu', category: 'Irregular Verbs' },
  { en: 'hit - hit - hit', vn: 'đánh, va chạm', category: 'Irregular Verbs' },
  { en: 'hold - held - held', vn: 'cầm, nắm, tổ chức', category: 'Irregular Verbs' },
  { en: 'hurt - hurt - hurt', vn: 'làm đau', category: 'Irregular Verbs' },
  { en: 'keep - kept - kept', vn: 'giữ, duy trì', category: 'Irregular Verbs' },
  { en: 'know - knew - known', vn: 'biết, hiểu', category: 'Irregular Verbs' },
  { en: 'lay - laid - laid', vn: 'đặt, để, đẻ trứng', category: 'Irregular Verbs' },
  { en: 'lead - led - led', vn: 'dẫn dắt, lãnh đạo', category: 'Irregular Verbs' },
  { en: 'learn - learnt - learnt', vn: 'học hỏi', category: 'Irregular Verbs' },
  { en: 'leave - left - left', vn: 'rời đi, bỏ lại', category: 'Irregular Verbs' },
  { en: 'lend - lent - lent', vn: 'cho vay, cho mượn', category: 'Irregular Verbs' },
  { en: 'let - let - let', vn: 'cho phép', category: 'Irregular Verbs' },
  { en: 'lie - lay - lain', vn: 'nằm', category: 'Irregular Verbs' },
  { en: 'light - lit - lit', vn: 'thắp sáng', category: 'Irregular Verbs' },
  { en: 'lose - lost - lost', vn: 'thua, đánh mất', category: 'Irregular Verbs' },
  { en: 'make - made - made', vn: 'làm, chế tạo', category: 'Irregular Verbs' },
  { en: 'mean - meant - meant', vn: 'có nghĩa là', category: 'Irregular Verbs' },
  { en: 'meet - met - met', vn: 'gặp gỡ', category: 'Irregular Verbs' },
  { en: 'pay - paid - paid', vn: 'thanh toán, trả tiền', category: 'Irregular Verbs' },
  { en: 'put - put - put', vn: 'đặt, để', category: 'Irregular Verbs' },
  { en: 'read - read - read', vn: 'đọc', category: 'Irregular Verbs' },
  { en: 'ride - rode - ridden', vn: 'cưỡi xe, đi xe', category: 'Irregular Verbs' },
  { en: 'ring - rang - rung', vn: 'rung chuông', category: 'Irregular Verbs' },
  { en: 'rise - rose - risen', vn: 'gia tăng, mọc lên', category: 'Irregular Verbs' },
  { en: 'run - ran - run', vn: 'chạy', category: 'Irregular Verbs' },
  { en: 'say - said - said', vn: 'nói', category: 'Irregular Verbs' },
  { en: 'see - saw - seen', vn: 'nhìn thấy', category: 'Irregular Verbs' },
  { en: 'seek - sought - sought', vn: 'tìm kiếm', category: 'Irregular Verbs' },
  { en: 'sell - sold - sold', vn: 'bán', category: 'Irregular Verbs' },
  { en: 'send - sent - sent', vn: 'gửi đi', category: 'Irregular Verbs' },
  { en: 'set - set - set', vn: 'thiết lập, cài đặt', category: 'Irregular Verbs' },
  { en: 'shake - shook - shaken', vn: 'bắt tay, rung lắc', category: 'Irregular Verbs' },
  { en: 'shine - shone - shone', vn: 'tỏa sáng', category: 'Irregular Verbs' },
  { en: 'shoot - shot - shot', vn: 'bắn', category: 'Irregular Verbs' },
  { en: 'show - showed - shown', vn: 'hiển thị, cho xem', category: 'Irregular Verbs' },
  { en: 'shrink - shrank - shrunk', vn: 'co lại, thu nhỏ', category: 'Irregular Verbs' },
  { en: 'shut - shut - shut', vn: 'đóng lại', category: 'Irregular Verbs' },
  { en: 'sing - sang - sung', vn: 'hát', category: 'Irregular Verbs' },
  { en: 'sink - sank - sunk', vn: 'chìm xuống', category: 'Irregular Verbs' },
  { en: 'sit - sat - sat', vn: 'ngồi', category: 'Irregular Verbs' },
  { en: 'sleep - slept - slept', vn: 'ngủ', category: 'Irregular Verbs' },
  { en: 'slide - slid - slid', vn: 'trượt', category: 'Irregular Verbs' },
  { en: 'speak - spoke - spoken', vn: 'nói chuyện', category: 'Irregular Verbs' },
  { en: 'spend - spent - spent', vn: 'dành thời gian / chi tiền', category: 'Irregular Verbs' },
  { en: 'stand - stood - stood', vn: 'đứng', category: 'Irregular Verbs' },
  { en: 'steal - stole - stolen', vn: 'trộm cắp', category: 'Irregular Verbs' },
  { en: 'stick - stuck - stuck', vn: 'dán, dính', category: 'Irregular Verbs' },
  { en: 'strike - struck - struck', vn: 'đình công, bãi công, đánh', category: 'Irregular Verbs' },
  { en: 'swear - swore - sworn', vn: 'tuyên thệ, thề', category: 'Irregular Verbs' },
  { en: 'swim - swam - swum', vn: 'bơi lội', category: 'Irregular Verbs' },
  { en: 'take - took - taken', vn: 'cầm, lấy', category: 'Irregular Verbs' },
  { en: 'teach - taught - taught', vn: 'giảng dạy', category: 'Irregular Verbs' },
  { en: 'tear - tore - torn', vn: 'xé rách', category: 'Irregular Verbs' },
  { en: 'tell - told - told', vn: 'kể, bảo', category: 'Irregular Verbs' },
  { en: 'think - thought - thought', vn: 'suy nghĩ', category: 'Irregular Verbs' },
  { en: 'throw - threw - thrown', vn: 'ném, quăng', category: 'Irregular Verbs' },
  { en: 'understand - understood - understood', vn: 'thấu hiểu', category: 'Irregular Verbs' },
  { en: 'wake - woke - woken', vn: 'thức dậy', category: 'Irregular Verbs' },
  { en: 'wear - wore - worn', vn: 'mặc đồ', category: 'Irregular Verbs' },
  { en: 'win - won - won', vn: 'chiến thắng', category: 'Irregular Verbs' },
  { en: 'write - wrote - written', vn: 'viết bài', category: 'Irregular Verbs' }
];
`;

let code = fs.readFileSync(targetPath, 'utf8');

// Include IRREGULAR_VERBS_BANK inside getSpeedMatchPairs
code = code.replace(
  'const dynamicPairs = [...SPEED_MATCH_PAIRS];',
  'const dynamicPairs = [...SPEED_MATCH_PAIRS, ...IRREGULAR_VERBS_BANK];'
);

fs.writeFileSync(targetPath, expansionCode + '\n' + code, 'utf8');
console.log('Successfully expanded games-data.js with IRREGULAR_VERBS_BANK!');
