import fs from 'fs';
import { VOCAB_BANK } from '../src/data/vocab-bank.js';

const existingSet = new Set(VOCAB_BANK.map(i => i.en.toLowerCase()));

// Oxford 6000 & CEFR A1-C2 Words batch to reach > 6000 items
const additionalWords = [
  // C
  ["Cabinetmaker", "Thợ đóng tủ gỗ tinh xảo", "common", "Crafts & Work", "C1"],
  ["Cablegram", "Bức điện báo qua cáp", "common", "History & Tech", "C2"],
  ["Cacophony", "Âm thanh hỗn loạn chói tai", "ielts", "Music & Sound", "C2"],
  ["Cadence", "Nhịp điệu âm điệu", "common", "Music & Speech", "C1"],
  ["Cadet", "Học viên quân sự/hàng hải", "common", "Military & Education", "B2"],
  ["Cafeteria", "Nhà ăn tự phục vụ", "common", "Food & Office", "A2"],
  ["Caffeine", "Chất ca-phê-in", "common", "Health & Food", "A2"],
  ["Cage", "Lồng, chuồng", "common", "Animals & Daily Life", "A2"],
  ["Calamity", "Thảm họa tai ương", "ielts", "Environment & Society", "C1"],
  ["Calcification", "Sự vôi hóa", "ielts", "Medicine & Science", "C2"],
  ["Calculated", "Có tính toán trước", "toeic", "Strategy & Math", "B2"],
  ["Calculation", "Sự tính toán, phép tính", "common", "Math & Analytics", "B1"],
  ["Calculator", "Máy tính cầm tay", "common", "Education & Office", "A1"],
  ["Calculus", "Phép tính giải tích", "ielts", "Math & Education", "C1"],
  ["Caliber", "Tầm vóc, năng lực, đường kính đạn", "toeic", "HR & Personal", "C1"],
  ["Calibration", "Sự hiệu chuẩn thiết bị", "toeic", "Manufacturing & Tech", "C1"],
  ["Calligrapher", "Nhà thư pháp", "common", "Arts & Culture", "C1"],
  ["Calligraphy", "Nghệ thuật thư pháp", "common", "Arts & Culture", "B2"],
  ["Callousness", "Sự nhẫn tâm vô cảm", "common", "Psychology", "C2"],
  ["Callus", "Vết chai da", "common", "Health & Body", "B2"],
  ["Calmness", "Sự bình tĩnh điềm tĩnh", "common", "Psychology", "B1"],
  ["Camaraderie", "Tình bạn đồng chí gắn bó", "common", "Relationships & Work", "C1"],
  ["Cambium", "Tầng sinh gỗ cây", "ielts", "Nature & Biology", "C2"],
  ["Camel", "Con lạc đà", "common", "Animals & Nature", "A2"],
  ["Camcorder", "Máy quay phim cầm tay", "common", "Tech & Media", "A2"],
  ["Camouflage", "Sự ngụy trang", "common", "Nature & Military", "B2"],
  ["Campground", "Khu cắm trại", "common", "Travel & Tourism", "A2"],
  ["Camping", "Hoạt động cắm trại", "common", "Travel & Hobbies", "A1"],
  ["Campsite", "Địa điểm cắm trại", "common", "Travel & Tourism", "A2"],
  ["Campus", "Khuôn viên trường đại học", "common", "Education", "A2"],
  ["Canal", "Kênh đào", "common", "Geography & Engineering", "B1"],
  ["Cancelation", "Sự hủy bỏ", "toeic", "Customer Service & Travel", "B1"],
  ["Cancerous", "Có tính ung thư", "common", "Health & Medicine", "B2"],
  ["Candidacy", "Tư cách ứng cử viên", "toeic", "HR & Politics", "C1"],
  ["Candidate", "Ứng viên", "common", "HR & Politics", "B1"],
  ["Candlelight", "Ánh nến", "common", "Daily Life & Culture", "A2"],
  ["Candlestick", "Chân nến", "common", "Home & Furniture", "B1"],
  ["Candor", "Tính bộc bạch thật thà", "common", "Personal Qualities", "C1"],
  ["Canine", "Thuộc loài chó, răng nanh", "common", "Animals & Health", "B2"],
  ["Canister", "Hộp nhỏ bằng kim loại", "common", "Home & Tech", "B2"],
  ["Canker", "Vết loét thối rễ/da", "common", "Health & Agriculture", "C2"],
  ["Cannabis", "Cây cần sa", "common", "Health & Law", "B2"],
  ["Cannibalism", "Tục ăn thịt đồng loại", "common", "History & Culture", "C2"],
  ["Cannon", "Khẩu pháo cổ", "common", "Military & History", "B2"],
  ["Canoe", "Thuyền ca-nô nhỏ", "common", "Sports & Travel", "A2"],
  ["Canoeing", "Môn chèo thuyền ca-nô", "common", "Sports & Hobbies", "B1"],
  ["Canopy", "Vòm lá rừng, mái che", "common", "Nature & Architecture", "B2"],
  ["Cantankerous", "Hay gắt gỏng khó tính", "common", "Psychology", "C2"],
  ["Canteen", "Nhà ăn trường/công sở", "common", "Food & Office", "A2"],
  ["Canvas", "Vải bạt, tranh sơn dầu", "common", "Arts & Materials", "B1"],
  ["Canvassing", "Sự vận động bầu cử/bán hàng", "toeic", "Politics & Sales", "C1"],
  ["Canyon", "Hẻm núi sâu", "common", "Geography & Nature", "B1"],
  ["Capability", "Khả năng, năng lực tác chiến", "common", "Tech & HR", "B2"],
  ["Capacitance", "Điện dung", "ielts", "Physics & Tech", "C2"],
  ["Capacitor", "Tụ điện", "common", "Tech & Physics", "B2"],
  ["Capacity", "Sức chứa, công suất", "common", "Analytics & Tech", "B2"],
  ["Cape", "Mũi đất vươn ra biển, áo khoác choàng", "common", "Geography & Fashion", "B1"],
  ["Capitalism", "Chủ nghĩa tư bản", "ielts", "Economics & History", "B2"],
  ["Capitalist", "Nhà tư bản", "common", "Economics", "B2"],
  ["Capitulation", "Sự đầu hàng nhượng bộ", "ielts", "History & Warfare", "C2"],
  ["Capricious", "Thất thường hay thay đổi", "ielts", "Psychology & Weather", "C2"],
  ["Capsule", "Viên thuốc bao phim, khoang tàu vũ trụ", "common", "Medicine & Space", "B2"],
  ["Captaincy", "Chức vụ đội trưởng/thuyền trưởng", "common", "Sports & Navy", "B2"],
  ["Captence", "Tiêu đề phụ", "common", "Media", "B1"],
  ["Captivate", "Làm mê hớp lôi cuốn", "common", "Arts & Mind", "C1"],
  ["Captivating", "Hấp dẫn quyến rũ", "common", "Arts & Mind", "B2"],
  ["Captivity", "Tình trạng bị giam giữ", "common", "Animals & Law", "B2"],
  ["Captor", "Kẻ bắt giữ", "common", "Law & Safety", "B2"],
  ["Caramel", "Kẹo đắng, đường thắng", "common", "Food & Dining", "A2"],
  ["Carat", "Đơn vị cara vàng/kim cương", "common", "Jewelry & Trade", "B2"],
  ["Caravan", "Đoàn thương lữ, xe nhà di động", "common", "Travel & Culture", "B1"],
  ["Carbohydrate", "Chất tinh bột carbohydrate", "common", "Health & Food", "B1"],
  ["Carburetor", "Bộ chế hòa khí động cơ", "common", "Auto & Engineering", "C1"],
  ["Carcass", "Xác động vật", "common", "Animals & Nature", "B2"],
  ["Cardboard", "Bìa các-tông", "common", "Materials & Office", "A2"],
  ["Cardiac", "Thuộc về tim", "ielts", "Medicine & Health", "B2"],
  ["Cardigan", "Áo len len đan có hàng nút", "common", "Fashion & Style", "A2"],
  ["Cardinal", "Hồng y giáo chủ, nguyên số", "common", "Religion & Math", "C1"],
  ["Cardiovascular", "Thuộc hệ tim mạch", "ielts", "Medicine & Health", "C1"],
  ["Careerist", "Người tham vọng sự nghiệp", "toeic", "HR & Qualities", "C1"],
  ["Caregiver", "Người chăm sóc người bệnh/già", "common", "Health & Family", "B1"],
  ["Carelessness", "Sự bất cẩn", "common", "Daily Life", "A2"],
  ["Cargo", "Hàng hóa vận chuyển", "toeic", "Logistics & Shipping", "B2"],
  ["Caricature", "Tranh biếm họa", "common", "Arts & Media", "C1"],
  ["Caricaturist", "Họa sĩ biếm họa", "common", "Arts & Media", "C2"],
  ["Caring", "Chu đáo quan tâm", "common", "Personal Qualities", "A2"],
  ["Carmine", "Màu đỏ sẫm", "common", "Colors & Design", "C2"],
  ["Carnage", "Cuộc thảm sát đẫm máu", "common", "History & Warfare", "C2"],
  ["Carnival", "Lễ hội hóa trang", "common", "Culture & Events", "A2"],
  ["Carnivore", "Động vật ăn thịt", "ielts", "Animals & Nature", "B2"],
  ["Carnivorous", "Ăn thịt", "ielts", "Animals & Nature", "B2"],
  ["Carol", "Bài hát mừng giáng sinh", "common", "Music & Culture", "A2"],
  ["Carousel", "Băng chuyền hành lý, trò ngựa quay", "toeic", "Travel & Events", "B2"],
  ["Carpenter", "Thợ mộc", "common", "Career & Construction", "A2"],
  ["Carpentry", "Nghề mộc", "common", "Crafts & Work", "B1"],
  ["Carpeted", "Được trải thảm", "common", "Home & Design", "A2"],
  ["Carpetbagger", "Kẻ đầu cơ cơ hội", "common", "Politics & History", "C2"],
  ["Carriage", "Toa hành khách tàu hỏa, xe ngựa", "common", "Travel & History", "B1"],
  ["Carrier", "Hãng vận chuyển, người mang mầm bệnh", "toeic", "Logistics & Health", "B1"],
  ["Cartel", "Tập đoàn độc quyền giá", "toeic", "Economics & Trade", "C2"],
  ["Cartilage", "Sụn xương", "ielts", "Medicine & Anatomy", "B2"],
  ["Cartographer", "Nhà vẽ bản đồ", "common", "Geography & History", "C1"],
  ["Cartography", "Nghệ thuật vẽ bản đồ", "ielts", "Geography & Science", "C1"],
  ["Carton", "Hộp giấy các-tông đựng hàng", "common", "Logistics & Food", "A2"],
  ["Cartoonist", "Họa sĩ truyện tranh", "common", "Arts & Career", "A2"],
  ["Cartridge", "Hộp mực máy in, vỏ đạn", "toeic", "IT & Office", "B2"],
  ["Cascade", "Thác nước nhỏ, sự đổ dồn dập", "common", "Nature & Tech", "C1"],
  ["Caseworker", "Nhân viên công tác xã hội", "common", "Society & Health", "B2"],
  ["Cashflow", "Dòng tiền lưu thông", "toeic", "Finance & Accounting", "B2"],
  ["Cashier", "Nhân viên thu ngân", "common", "Sales & Career", "A1"],
  ["Casing", "Vỏ bao bọc ngoài", "common", "Engineering & Tech", "B2"],
  ["Casino", "Sòng bạc", "common", "Entertainment & Travel", "A2"],
  ["Casket", "Hòm quan tài, hộp đựng trang sức", "common", "Culture & Life", "B2"],
  ["Cassette", "Băng cát-xét cổ", "common", "Music & History", "A2"],
  ["Castaway", "Người đắm tàu dạt vào đảo", "common", "Literature & History", "B2"],
  ["Caste", "Đẳng cấp xã hội", "ielts", "Sociology & History", "C1"],
  ["Castle", "Lâu đài", "common", "History & Architecture", "A1"],
  ["Casualty", "Thương vong tai nạn/chiến tranh", "common", "Health & Military", "B2"],
  ["Cataclysm", "Thảm họa biến động lớn", "ielts", "Environment & History", "C2"],
  ["Cataclysmic", "Mang tính thảm họa lớn", "ielts", "Environment & Science", "C2"],
  ["Cataloger", "Người lập danh mục", "toeic", "Office & Books", "B2"],
  ["Cataloging", "Việc lập sổ danh mục", "toeic", "Office & IT", "B2"],
  ["Catalysis", "Sự xúc tác hóa học", "ielts", "Science & Chemistry", "C2"],
  ["Catalyst", "Chất xúc tác, nhân tố thúc đẩy", "ielts", "Science & Strategy", "C1"],
  ["Catapult", "Súng súng phóng, bệ phóng", "common", "History & Tech", "B2"],
  ["Cataract", "Bệnh đục thủy tinh thể, thác nước lớn", "common", "Health & Nature", "C1"],
  ["Catastrophe", "Thảm họa cực lớn", "common", "Environment & Safety", "B2"],
  ["Catastrophic", "Mang tính thảm họa", "common", "Environment & Safety", "B2"],
  ["Catchphrase", "Câu khẩu hiệu cửa miệng", "common", "Media & Culture", "B2"],
  ["Catchment", "Lưu vực thu nước mưa", "ielts", "Environment & Water", "C1"],
  ["Catechism", "Sách giáo lý", "common", "Religion & Books", "C2"],
  ["Categorical", "Tuyệt đối dứt quát", "ielts", "Academic & Rhetoric", "C1"],
  ["Categorically", "Một cách dứt quát", "ielts", "Rhetoric", "C1"],
  ["Category", "Hạng mục, thể loại", "common", "Analytics & General", "A2"],
  ["Catering", "Dịch vụ tiệc ăn uống", "toeic", "Hospitality & Food", "B1"],
  ["Caterpillar", "Sâu bướm", "common", "Animals & Nature", "A2"],
  ["Catharsis", "Sự giải tỏa tâm lý", "ielts", "Psychology & Arts", "C2"],
  ["Cathedral", "Nhà thờ lớn", "common", "Architecture & Religion", "A2"],
  ["Cathode", "Cực âm điện tử", "common", "Science & Physics", "B2"],
  ["Catholicism", "Công giáo La Mã", "common", "Religion & History", "B2"],
  ["Caucus", "Cuộc họp nội bộ nhóm chính trị", "ielts", "Politics & Governance", "C2"],
  ["Cauliflower", "Súp lơ trắng", "common", "Food & Dining", "A2"],
  ["Causal", "Thuộc quan hệ nguyên nhân", "ielts", "Academic & Science", "B2"],
  ["Causality", "Quan hệ nhân quả", "ielts", "Academic & Logic", "C1"],
  ["Causation", "Sự gây ra nguyên nhân", "ielts", "Academic & Logic", "C1"],
  ["Causeway", "Đường đắp cao qua nước", "common", "Engineering & Travel", "B2"],
  ["Caustic", "Có tính ăn mòn, mỉa mai cay độc", "common", "Chemistry & Rhetoric", "C2"],
  ["Cautious", "Thận trọng", "common", "Personal Qualities", "B1"],
  ["Cavalry", "Kị binh quân đội", "common", "History & Military", "B2"],
  ["Caveman", "Người người ngầm cổ xưa", "common", "History", "A2"],
  ["Cavern", "Hang động lớn sâu", "common", "Nature & Geology", "B2"],
  ["Cavernous", "Rộng mênh mông như hang động", "common", "Architecture & Nature", "C1"],
  ["Caviar", "Trứng cá tầm đắt tiền", "common", "Food & Luxury", "B2"],
  ["Cavity", "Lỗ sâu răng, hốc rỗng", "common", "Health & Science", "B2"],
  ["Ceasefire", "Lệnh lệnh ngừng bắn", "common", "Military & Politics", "B2"],
  ["Ceaseless", "Không ngừng nghỉ", "common", "General", "B2"],
  ["Ceiling", "Trần nhà, mức trần giá tối đa", "common", "Home & Economics", "A2"],
  ["Celebrancy", "Sự chủ trì lễ hội", "common", "Culture", "C2"],
  ["Celebrant", "Người chủ trì buổi lễ", "common", "Culture & Religion", "C1"],
  ["Celebrated", "Nổi tiếng lừng lẫy", "common", "Culture & People", "B2"],
  ["Celebration", "Lễ kỷ niệm ăn mừng", "common", "Culture & Events", "A1"],
  ["Celebrity", "Người nổi tiếng", "common", "Culture & Media", "A2"],
  ["Celery", "Rau cần tây", "common", "Food & Dining", "A2"],
  ["Celestial", "Thuộc về bầu trời vũ trụ", "ielts", "Science & Astronomy", "C1"],
  ["Celibacy", "Sự sống độc thân kiêng khem", "common", "Religion & Society", "C2"],
  ["Cellar", "Hầm chứa rượu/đồ", "common", "Home & Architecture", "B1"],
  ["Cellular", "Thuộc tế bào, mạng di động", "common", "Science & IT", "B2"],
  ["Celluloid", "Phim nhựa điện ảnh cổ", "common", "Movies & Tech", "C1"],
  ["Cellulose", "Chất xen-lu-lô thực vật", "common", "Science & Biology", "B2"],
  ["Celsius", "Độ C đo nhiệt độ", "common", "Science & Weather", "A1"],
  ["Cemetery", "Nghĩa trang", "common", "History & Society", "B1"],
  ["Cenotaph", "Bia đài tưởng niệm chiến sĩ", "common", "History & Architecture", "C2"],
  ["Censor", "Nhân viên kiểm duyệt", "common", "Media & Law", "B2"],
  ["Censorship", "Sự kiểm duyệt tin tức", "ielts", "Media & Politics", "C1"],
  ["Censurable", "Đáng bị phê bình", "common", "Ethics & Law", "C2"],
  ["Censure", "Sự chỉ trích phê bình chính thức", "ielts", "Politics & Law", "C2"],
  ["Census", "Cuộc tổng điều tra dân số", "ielts", "Society & Analytics", "B2"],
  ["Centenary", "Lễ kỷ niệm 100 năm", "common", "History & Events", "C1"],
  ["Centerpiece", "Vật trung tâm trang trí/thảo luận", "common", "Events & Strategy", "B2"],
  ["Centigrade", "Độ bách phân (Độ C)", "common", "Science & Weather", "A2"],
  ["Centralization", "Sự tập trung hóa quyền lực", "toeic", "Management & Strategy", "C1"],
  ["Centralized", "Mang tính tập trung", "toeic", "Management & Strategy", "B2"],
  ["Centrifugal", "Lực ly tâm", "ielts", "Physics & Science", "C1"],
  ["Centripetal", "Lực hướng tâm", "ielts", "Physics & Science", "C1"],
  ["Centurion", "Sĩ quan bách nhẫn La Mã", "common", "History & Military", "C2"],
  ["Centroid", "Trọng tâm hình học", "common", "Math & Physics", "C1"],
  ["Ceramic", "Đồ gốm sứ", "common", "Arts & Materials", "B1"],
  ["Ceramics", "Nghệ thuật làm gốm", "common", "Arts & Crafts", "B1"],
  ["Cereal", "Ngũ cốc ăn sáng", "common", "Food & Dining", "A2"],
  ["Cerebral", "Thuộc về não bộ, trí tuệ", "ielts", "Health & Mind", "C1"],
  ["Ceremonial", "Thuộc nghi lễ nghi thức", "common", "Culture & Events", "B2"],
  ["Ceremony", "Buổi lễ nghi thức", "common", "Culture & Events", "A2"],
  ["Certainty", "Sự chắc chắn hiển nhiên", "common", "Psychology", "B1"],
  ["Certifiable", "Có thể cấp chứng nhận", "toeic", "Legal & Quality", "B2"],
  ["Certificate", "Bằng cấp, chứng chỉ", "common", "Education & HR", "A2"],
  ["Certification", "Sự cấp chứng chỉ", "toeic", "Education & HR", "B2"],
  ["Certified", "Đã được cấp chứng nhận", "toeic", "HR & Quality", "B1"],
  ["Certitude", "Sự quả quyết chắc chắn", "ielts", "Psychology", "C2"],
  ["Cervical", "Thuộc về cổ/cổ tử cung", "common", "Health & Anatomy", "B2"],
  ["Cessation", "Sự chấm dứt ngắt quãng", "ielts", "Law & Strategy", "C1"],
  ["Chafing", "Sự cọ xát gây rát da", "common", "Health & Body", "C1"],
  ["Chagrined", "Thất vọng chán nản", "common", "Psychology", "C2"],
  ["Chainstore", "Chuỗi cửa hàng bán lẻ", "toeic", "Retail & Commerce", "B1"],
  ["Chairmanship", "Chức vụ chủ tịch", "toeic", "Corporate Governance", "B2"],
  ["Chairperson", "Chủ tọa cuộc họp", "toeic", "Office & Meetings", "A2"],
  ["Chalet", "Nhà gỗ vùng núi", "common", "Travel & Architecture", "B1"],
  ["Chalkboard", "Bảng viết phấn", "common", "Education", "A1"],
  ["Challenger", "Người thách thức", "common", "Sports & Strategy", "B1"],
  ["Chamberlain", "Quan tổng quản hoàng gia", "common", "History & Governance", "C2"],
  ["Chameleon", "Con tắc kè hoa, người hay đổi màu", "common", "Animals & Mind", "B2"],
  ["Champagne", "Rượu sâm-panh", "common", "Food & Culture", "A2"],
  ["Champion", "Nhà vô địch, người đấu đấu vì nghĩa", "common", "Sports & Strategy", "A2"],
  ["Championship", "Giải vô địch", "common", "Sports & Events", "A2"],
  ["Chancellor", "Thủ tướng (Đức/Áo), hiệu trưởng đại học", "ielts", "Politics & Education", "C1"],
  ["Chandelier", "Đèn chùm pha lê trang trí", "common", "Home & Furniture", "B2"],
  ["Changeable", "Dễ thay đổi thất thường", "common", "Weather & Psychology", "B1"],
  ["Changer", "Bộ chuyển đổi", "common", "Tech", "B1"],
  ["Channelling", "Sự dẫn dòng hướng tuyến", "common", "Tech & Logistics", "B2"],
  ["Chansons", "Bài hát trữ tình Pháp", "common", "Music & Culture", "C2"],
  ["Chaos", "Sự hỗn loạn m chaos", "common", "General", "B1"],
  ["Chaotic", "Hỗn loạn không trật tự", "common", "General", "B1"],
  ["Chaparral", "Vùng bụi cây gai khô", "common", "Nature & Geography", "C2"],
  ["Chapel", "Nhà nguyện nhỏ", "common", "Architecture & Religion", "B1"],
  ["Chaperone", "Người đi kèm giám sát", "common", "Culture & Life", "B2"],
  ["Chaplain", "Mục sư tuyên úy", "common", "Religion & Military", "C1"],
  ["Characterization", "Sự khắc họa nhân vật", "ielts", "Literature & Arts", "B2"],
  ["Characteristic", "Đặc điểm đặc trưng", "common", "Science & Analytics", "B1"],
  ["Charitable", "Có lòng từ thiện", "common", "Society & Ethics", "B1"],
  ["Charity", "Tổ chức từ thiện, lòng hảo tâm", "common", "Society & Ethics", "A2"],
  ["Charlatan", "Kẻ lừa đảo khoác phác", "common", "Law & Mind", "C2"],
  ["Charmingly", "Một cách duyên dáng", "common", "Daily Life", "B1"],
  ["Charitable", "Thuộc từ thiện", "common", "Society", "B1"],
  ["Chartist", "Chuyên viên phân tích biểu đồ tài chính", "toeic", "Finance & Analytics", "C2"],
  ["Chartered", "Đã có chứng chỉ hành nghề chính thức", "toeic", "HR & Finance", "B2"],
  ["Chastity", "Sự trinh tiết trong sạch", "common", "Ethics & Culture", "C2"],
  ["Château", "Lâu đài Pháp", "common", "Architecture & History", "B1"],
  ["Chatbot", "Robot trò chuyện tự động", "common", "IT & Tech", "A2"],  ["Chatroom", "Phòng trò chuyện trực tuyến", "common", "IT & Social", "A2"],
  ["Chauffeur", "Tài xế riêng sang trọng", "toeic", "Travel & Service", "B2"],
  ["Chauvinism", "Chủ nghĩa cuồng tín vị kỷ", "ielts", "Society & Politics", "C2"],  ["Cheated", "Bị lừa dối", "common", "Psychology", "A2"],
  ["Checkbook", "Sổ séc ngân hàng", "toeic", "Banking & Finance", "A2"],
  ["Checkin", "Sự làm thủ tục lên tàu/khách sạn", "common", "Travel & Tourism", "A1"],
  ["Checkout", "Quầy thanh toán, thủ tục trả phòng", "common", "Retail & Travel", "A1"],
  ["Checkpoint", "Trạm kiểm soát", "common", "Safety & Travel", "B1"],
  ["Cheekbone", "Xương gò má", "common", "Health & Body", "B1"],
  ["Cheerful", "Vui vẻ phấn khởi", "common", "Personal Qualities", "A2"],
  ["Cheerleader", "Đội trưởng cổ vũ", "common", "Sports & School", "A2"],
  ["Cheesecake", "Bánh phô mai", "common", "Food & Dining", "A2"],
  ["Cheeseburger", "Bánh kẹp thịt có phô mai", "common", "Food & Dining", "A1"],
  ["Chef", "Đầu bếp trưởng", "common", "Food & Career", "A2"],
  ["Chemical", "Hóa chất, thuộc hóa học", "common", "Science & Chemistry", "A2"],
  ["Chemist", "Nhà hóa học, dược sĩ", "common", "Science & Career", "A2"],
  ["Chemistry", "Môn hóa học", "common", "Science & Education", "A2"],
  ["Chemotherapy", "Liệu pháp hóa trị ung thư", "common", "Medicine & Health", "B2"],
  ["Chequebook", "Sổ séc thanh toán", "toeic", "Banking & Finance", "A2"],
  ["Cherubic", "Có khuôn mặt thơ ngây như thiên thần", "common", "Personal", "C2"],
  ["Cheveron", "Họa tiết hình chữ V", "common", "Design & Military", "C1"],
  ["Chickpea", "Hạt đậu gà", "common", "Food & Agriculture", "A2"],
  ["Chieftain", "Tù trưởng bộ tộc", "common", "History & Culture", "C1"],
  ["Childhood", "Thời thơ ấu", "common", "Family & Life", "A2"],
  ["Childish", "Trẻ con ngây ngô", "common", "Psychology", "B1"],
  ["Childless", "Không có con", "common", "Family & Society", "B2"],
  ["Childlike", "Hồn nhiên như trẻ thơ", "common", "Psychology", "B2"],
  ["Chilli", "Quả ớt cay", "common", "Food & Dining", "A1"],
  ["Chimney", "Ống khói nhà", "common", "Home & Architecture", "A2"],
  ["Chimpanzee", "Con tinh tinh", "common", "Animals & Nature", "B1"],
  ["Chivalry", "Tinh thần hiệp sĩ kiêu hãnh", "common", "History & Culture", "C1"],
  ["Chloride", "Hợp chất clo-rua", "common", "Science & Chemistry", "B2"],
  ["Chlorine", "Khí clo chất tẩy", "common", "Chemistry & Environment", "B2"],
  ["Chlorophyll", "Chất diệp lục thực vật", "ielts", "Biology & Nature", "B2"],
  ["Chocolate", "Kẹo sô-cô-la", "common", "Food & Dining", "A1"],
  ["Choir", "Dàn hợp xướng", "common", "Music & Culture", "B1"],
  ["Choking", "Sự ngạt thở, bị nghẹn", "common", "Health & Safety", "B1"],
  ["Cholesterol", "Chất béo mỡ máu cholesterol", "common", "Health & Medicine", "B2"],
  ["Choreography", "Nghệ thuật biên đạo múa", "common", "Arts & Dance", "B2"],
  ["Chorus", "Điệp khúc bài hát, dàn xướng", "common", "Music & Culture", "A2"],
  ["Christianity", "Kitô giáo", "common", "Religion & History", "B1"],
  ["Chromatic", "Thuộc màu sắc, bán âm nhạc", "common", "Design & Music", "C1"],
  ["Chromium", "Kim loại crôm", "common", "Science & Chemistry", "B2"],
  ["Chromosome", "Nhiễm sắc thể", "ielts", "Biology & Science", "B2"],
  ["Chronicle", "Sử biên niên ghi chép", "ielts", "History & Writing", "B2"],
  ["Chronicler", "Nhà chép sử biên niên", "common", "History", "C1"],
  ["Chronological", "Theo thứ tự thời gian", "ielts", "Academic & History", "B2"],
  ["Chronology", "Niên đại học thứ tự", "ielts", "Academic & History", "B2"],
  ["Chronometer", "Đồng hồ bấm giờ chính xác cao", "common", "Tech & Navigation", "C1"],
  ["Chrysanthemum", "Hoa cúc", "common", "Nature & Plants", "B2"],
  ["Chuckle", "Cười thầm cười khẽ", "common", "Daily Life", "B2"],
  ["Chugging", "Tiếng xình xịch động cơ", "common", "Sound & Auto", "B2"],
  ["Churchyard", "Sân nhà thờ nghĩa trang", "common", "Architecture & History", "B2"],
  ["Churlish", "Thô lỗ cỗ cựu", "common", "Personal Qualities", "C2"],
  ["Cider", "Rượu táo lên men", "common", "Food & Beverage", "B1"],
  ["Cigar", "Xì-gà", "common", "Lifestyle & Food", "A2"],
  ["Cigarette", "Thuốc lá", "common", "Daily Life & Health", "A1"],
  ["Cinder", "Tàn tro xỉ than", "common", "Nature & Safety", "B2"],
  ["Cinematographer", "Nhà quay phim điện ảnh", "common", "Movies & Career", "B2"],
  ["Cinematography", "Kỹ thuật quay phim điện ảnh", "common", "Movies & Arts", "B2"],
  ["Cinnamon", "Quế thơm", "common", "Food & Spices", "A2"],
  ["Cipher", "Mật mã khóa mã", "ielts", "IT & Security", "C1"],
  ["Circadian", "Thuộc nhịp sinh học hàng ngày", "ielts", "Biology & Health", "C1"],
  ["Circle", "Hình tròn, vòng tròn", "common", "Math & Shape", "A1"],
  ["Circuit", "Mạch điện, vòng đua", "common", "Tech & Sports", "B1"],
  ["Circuitry", "Hệ thống vi mạch", "common", "Tech & Engineering", "C1"],
  ["Circular", "Hình tròn, thư thông báo hàng loạt", "toeic", "Shape & Office", "B2"],
  ["Circulation", "Sự lưu thông máu/tiền tệ/báo chí", "toeic", "Health & Finance", "B2"],
  ["Circumference", "Chu vi hình tròn", "common", "Math & Science", "B2"],
  ["Circumlocution", "Sự nói vòng vo", "ielts", "Language & Rhetoric", "C2"],
  ["Circumnavigation", "Sự đi vòng quanh thế giới", "common", "Travel & History", "C1"],
  ["Circumscription", "Sự giới hạn phạm vi", "ielts", "Law & Philosophy", "C2"],
  ["Circumstance", "Hoàn cảnh, tình huống", "common", "Daily Life", "B1"],
  ["Circumstantial", "Mang tính suy đoán gián tiếp", "ielts", "Law & Analytics", "C1"],
  ["Circus", "Gánh xiếc", "common", "Entertainment", "A1"],
  ["Cirrus", "Mây ti (mây tầng cao)", "common", "Weather & Science", "C1"],
  ["Cistern", "Bể chứa nước ngầm", "common", "Home & Engineering", "B2"],
  ["Citadel", "Thành trì pháo đài cổ", "common", "History & Architecture", "B2"],
  ["Citation", "Trích dẫn tài liệu, bằng khen", "ielts", "Academic & Legal", "B2"],
  ["Citizen", "Công dân", "common", "Society & Politics", "A2"],
  ["Citizenship", "Quyền công dân", "common", "Society & Politics", "B1"],
  ["Citrus", "Họ cây cam chanh", "common", "Food & Nature", "B1"],
  ["Civic", "Thuộc đô thị/công dân", "common", "Society & Governance", "B2"],
  ["Civilian", "Thường dân không thuộc quân đội", "common", "Society & Military", "B1"],
  ["Civility", "Sự lịch sự phép lịch sự", "common", "Psychology & Society", "B2"],
  ["Civilization", "Nền văn minh", "common", "History & Society", "B1"],
  ["Civilized", "Văn minh khai sáng", "common", "Society", "B1"],
  ["Cladogram", "Sơ đồ nhánh phân loại", "ielts", "Biology & Science", "C2"],
  ["Claimant", "Người yêu cầu đòi quyền lợi", "toeic", "Law & Insurance", "B2"],
  ["Clairvoyance", "Khả năng thấu thị ngoại cảm", "common", "Mind & Culture", "C2"],
  ["Clammy", "Ẩm ướt lạnh ngắt", "common", "Weather & Body", "C1"],
  ["Clamor", "Tiếng la hò phản đối dồn dập", "common", "News & Society", "C1"],
  ["Clamp", "Cái kẹp cố định", "common", "Tools & Work", "B2"],
  ["Clan", "Dòng tộc, thị tộc", "common", "Family & Society", "B2"],
  ["Clandestine", "Lén lút bí mật", "ielts", "Security & Politics", "C2"],  ["Clang", "Tiếng kim loại va lảng xoảng", "common", "Sound", "B2"],
  ["Clarity", "Sự rõ ràng minh bạch", "common", "Communication", "B2"],
  ["Clarification", "Sự làm rõ giải thích", "toeic", "Communication & Office", "B2"],
  ["Clarinet", "Kèn kèn dăm đơn clarinet", "common", "Music & Culture", "B1"],
  ["Classmate", "Bạn cùng lớp", "common", "School & Education", "A1"],
  ["Classroom", "Phòng học", "common", "School & Education", "A1"],
  ["Claustrophobia", "Hội chứng sợ không gian hẹp", "common", "Psychology & Health", "B2"],
  ["Claw", "Móng mút động vật", "common", "Animals & Nature", "A2"],
  ["Clay", "Đất sét", "common", "Materials & Arts", "A2"],
  ["Cleaner", "Người dọn dẹp, chất tẩy rửa", "common", "Career & Home", "A1"],
  ["Cleanliness", "Sự sạch sẽ ngăn nắp", "common", "Daily Life & Health", "A2"],
  ["Cleanse", "Làm sạch thanh lọc", "common", "Health & Beauty", "B2"],
  ["Cleanser", "Sữa rửa mặt, chất làm sạch", "common", "Beauty & Home", "A2"],
  ["Clearing", "Khoảnh đất trống trong rừng, sự thanh toán đối soát", "toeic", "Nature & Banking", "B2"],
  ["Clearness", "Sự trong trẻo rõ ràng", "common", "Daily Life", "B1"],
  ["Cleavage", "Sự chia rẽ phân tách, khe ngực", "common", "Society & Body", "C1"],
  ["Cleaver", "Dao chặt thịt lớn", "common", "Food & Tools", "B2"],
  ["Clemency", "Lòng khoan hồng độ lượng", "ielts", "Law & Justice", "C2"],  ["Clench", "Nắm chặt (tay/răng)", "common", "Body & Mind", "B2"],
  ["Clerical", "Thuộc về văn phòng/hành chính", "toeic", "Office Management", "B2"],
  ["Clerk", "Nhân viên văn phòng/giao dịch", "common", "Office & Banking", "A2"],
  ["Cleverness", "Sự khéo léo thông minh", "common", "Mind & Qualities", "A2"],
  ["Cliche", "Câu nói rập khuôn quen thuộc", "common", "Culture & Language", "B2"],
  ["Clickable", "Có thể nhấp chuột được", "common", "IT & Tech", "A2"],
  ["Clientele", "Tập hợp nhóm khách hàng", "toeic", "Business & Retail", "C1"],
  ["Cliffhanger", "Kết thúc đầy kịch tính dở dang", "common", "Movies & Books", "B2"],
  ["Climate", "Khí hậu", "common", "Nature & Weather", "A2"],
  ["Climatic", "Thuộc về khí hậu", "ielts", "Science & Nature", "B2"],
  ["Climax", "Đỉnh điểm, cao trào", "common", "Movies & Literature", "B2"],
  ["Climber", "Người leo núi", "common", "Sports & Travel", "A2"],
  ["Climbing", "Bộ môn leo núi", "common", "Sports & Hobbies", "A1"],
  ["Clinician", "Bác sĩ lâm sàng", "common", "Medicine & Career", "B2"],
  ["Clip-on", "Loại kẹp cài vào được", "common", "Products & Fashion", "A2"],
  ["Clipper", "Tông đơ hớt tóc, thuyền buồm nhanh cổ", "common", "Tools & History", "B2"],
  ["Cloakroom", "Phòng giữ đồ/áo khoác", "common", "Events & Hospitality", "A2"],
  ["Clockwork", "Bộ máy cơ có dây cót", "common", "Tech & History", "B2"],
  ["Clockwise", "Theo chiều kim đồng hồ", "common", "Directions & Math", "A2"],
  ["Clog", "Guốc gỗ, sự tắc nghẽn", "common", "Fashion & Plumbing", "B2"],
  ["Cloister", "Hành lang tu viện cổ", "common", "Architecture & History", "C2"],
  ["Clonning", "Sự nhân bản vô tính", "ielts", "Science & Biology", "B2"],
  ["Close-up", "Cận cảnh hình ảnh", "common", "Movies & Photography", "A2"],
  ["Closure", "Sự đóng cửa nhà máy/văn phòng", "toeic", "Corporate & Operations", "B2"],
  ["Clothesline", "Dây phơi quần áo", "common", "Home & Living", "A1"],
  ["Clothespin", "Kẹp phơi quần áo", "common", "Home & Living", "A1"],
  ["Clothing", "Quần áo trang phục", "common", "Fashion & Shopping", "A1"],
  ["Cloudburst", "Trận mưa rào dữ dội", "common", "Weather & Hazards", "B2"],
  ["Cloudiness", "Trời nhiều mây u ám", "common", "Weather", "A2"],
  ["Cloudless", "Trời không một gợn mây", "common", "Weather", "A2"],
  ["Clover", "Cây cỏ ba lá", "common", "Nature & Plants", "A2"],
  ["Clown", "Chú hề", "common", "Entertainment", "A1"],
  ["Clubhouse", "Nhà câu lạc bộ", "common", "Sports & Events", "A2"],
  ["Cluster", "Cụm, nhóm tập hợp", "common", "Analytics & Science", "B2"],
  ["Clutter", "Sự bừa bộn lộn xộn", "common", "Home & Mind", "B2"],
  ["Co-anchor", "Đồng dẫn chương trình tin tức", "common", "Media & News", "B2"],
  ["Co-author", "Đồng tác giả", "common", "Academic & Books", "B1"],
  ["Coach", "Huấn luyện viên, xe khách đường dài", "common", "Sports & Travel", "A1"],
  ["Coagulation", "Sự đông tụ máu", "ielts", "Medicine & Science", "C2"],
  ["Coalition", "Liên minh chính trị/doanh nghiệp", "ielts", "Politics & Governance", "C1"],
  ["Coarse", "Thô ráp, thô tục", "common", "Materials & Personal", "B2"],
  ["Coastal", "Thuộc vùng ven biển", "common", "Geography & Environment", "B1"],
  ["Coastline", "Đường bờ biển", "common", "Geography & Nature", "B1"],
  ["Coating", "Lớp màng bao phủ ngoài", "common", "Manufacturing & Materials", "B2"],
  ["Cobweb", "Mạng nhện cổ", "common", "Home & Nature", "A2"],
  ["Cocaine", "Ma túy cô-ca-in", "common", "Health & Crime", "B2"],
  ["Cockpit", "Khoang lái máy bay/xe đua", "toeic", "Aviation & Auto", "B2"],
  ["Cockroach", "Con gián", "common", "Animals & Home", "A2"],
  ["Cocktail", "Rượu cocktail pha", "common", "Food & Beverage", "A2"],
  ["Cocoa", "Bột ca-cao", "common", "Food & Beverage", "A1"],
  ["Coconut", "Quả dừa", "common", "Food & Nature", "A1"],
  ["Cocoon", "Kén tằm, vỏ bọc an toàn", "common", "Nature & Mind", "B2"],
  ["Codebreaker", "Chuyên gia giải mật mã", "common", "Security & History", "B2"],
  ["Codification", "Sự hệ thống hóa luật lệ", "ielts", "Law & Governance", "C2"],
  ["Codeword", "Mật từ", "common", "Security & Games", "A2"],
  ["Coeducation", "Hệ thống giáo dục chung nam nữ", "common", "Education", "B2"],
  ["Coefficient", "Hệ số toán học", "ielts", "Math & Physics", "C1"],
  ["Coercion", "Sự cưỡng ép ép buộc", "ielts", "Law & Psychology", "C2"],
  ["Coexistence", "Sự cùng tồn tại", "common", "Society & Politics", "B2"],
  ["Coffeehouse", "Quán cà phê", "common", "Food & Culture", "A1"],
  ["Coffin", "Quan tài", "common", "Culture & Life", "B1"],
  ["Cognition", "Sự nhận thức trí tuệ", "ielts", "Psychology & Mind", "C1"],
  ["Cognitive", "Thuộc về nhận thức tư duy", "ielts", "Psychology & Mind", "B2"],
  ["Coherence", "Tính mạch lạc nhất quán", "ielts", "Writing & Logic", "C1"],
  ["Coherent", "Mạch lạc chặt chẽ", "ielts", "Writing & Logic", "B2"],
  ["Cohesion", "Sự kết dính, sự gắn kết", "ielts", "Writing & Physics", "C1"],
  ["Cohesive", "Có tính gắn kết mạch lạc", "ielts", "Writing & Science", "B2"],
  ["Coincidence", "Sự trùng hợp ngẫu nhiên", "common", "Daily Life", "B1"],
  ["Coinsurance", "Bảo hiểm đồng chịu trách nhiệm", "toeic", "Finance & Insurance", "C2"],
  ["Coldness", "Sự lạnh giá, thái độ lạnh nhạt", "common", "Weather & Mind", "A2"],
  ["Collaboration", "Sự hợp tác làm việc", "toeic", "Office & Strategy", "B2"],
  ["Collaborator", "Cộng tác viên", "toeic", "HR & Work", "B2"],
  ["Collapse", "Sự sụp đổ, sự tuyển sức", "common", "General & Health", "B1"],
  ["Collar", "Cổ áo, vòng cổ chó", "common", "Fashion & Animals", "A2"],
  ["Collateral", "Tài sản thế chấp ngân hàng", "toeic", "Banking & Finance", "C1"],
  ["Colleague", "Đồng nghiệp", "common", "Office & HR", "A2"],
  ["Collectable", "Vật phẩm có giá trị sưu tầm", "common", "Hobbies & Trade", "B2"],
  ["Collection", "Bộ sưu tập, sự thu gom", "common", "General", "A2"],
  ["Collective", "Mang tính tập thể chung", "common", "Society & Politics", "B2"],
  ["Collectivism", "Chủ nghĩa tập thể", "ielts", "Sociology & Politics", "C2"],
  ["Collector", "Nhà sưu tầm", "common", "Hobbies & Career", "A2"],
  ["College", "Trường cao đẳng/đại học", "common", "Education", "A1"],
  ["Collision", "Cú va chạm tông xe", "common", "Auto & Safety", "B2"],
  ["Colloquial", "Thuộc khẩu ngữ đời thường", "ielts", "Language & Communication", "C1"],
  ["Colloquialism", "Từ ngữ khẩu ngữ dân dã", "ielts", "Linguistics", "C1"],
  ["Colloquium", "Hội thảo chuyên đề khoa học", "ielts", "Academic & Science", "C2"],
  ["Collusion", "Sự thông đồng giấu kín", "toeic", "Law & Governance", "C2"],
  ["Colonial", "Thuộc về thuộc địa", "common", "History & Society", "B2"],
  ["Colonialism", "Chủ nghĩa thực dân", "ielts", "History & Politics", "B2"],
  ["Colonist", "Tên thực dân khai phá", "common", "History", "B2"],
  ["Colonization", "Sự biến thành thuộc địa", "ielts", "History & Politics", "C1"],
  ["Colony", "Thuộc địa, bầy đàn động vật", "common", "History & Animals", "B1"],
  ["Colossal", "Khổng lồ đồ sộ", "common", "General", "C1"],
  ["Columnist", "Nhà chuyên mục báo chí", "common", "Media & Career", "B2"],
  ["Combatant", "Chiến sĩ tham chiến", "common", "Military & Law", "B2"],
  ["Combination", "Sự kết hợp phối hợp", "common", "General", "A2"],
  ["Combustion", "Sự đốt cháy nhiên liệu", "ielts", "Science & Energy", "B2"],
  ["Comedian", "Diễn viên hài", "common", "Entertainment & Career", "A2"],
  ["Comedy", "Phim/kịch hài", "common", "Entertainment & Movies", "A1"],
  ["Comeliness", "Vẻ kiều diễm xinh đẹp", "common", "Beauty", "C2"],
  ["Comet", "Sao chổi", "common", "Science & Space", "B1"],
  ["Comfortable", "Thoải mái dễ chịu", "common", "Daily Life", "A1"],
  ["Comforter", "Chăn bông ấm, người an ủi", "common", "Home & Mind", "A2"],
  ["Comical", "Hài hước buồn cười", "common", "Daily Life", "B2"],
  ["Commander", "Người chỉ huy tư lệnh", "common", "Military & Leadership", "B2"],
  ["Commandment", "Điều răn dạy tôn giáo", "common", "Religion & Ethics", "C1"],
  ["Commemoration", "Sự tưởng niệm kỷ niệm", "common", "History & Culture", "B2"],
  ["Commencement", "Lễ trao bằng tốt nghiệp, sự bắt đầu", "toeic", "Education & Events", "C1"],
  ["Commendable", "Đáng tuyên dương khen ngợi", "toeic", "HR & Governance", "C1"],
  ["Commendation", "Bằng khen tuyên dương", "toeic", "HR & Governance", "C1"],
  ["Commensurate", "Tương xứng phù hợp với", "toeic", "HR & Compensation", "C1"],
  ["Commentary", "Bài bình luận trận đấu/tin tức", "common", "Media & Sports", "B2"],
  ["Commentator", "Bình luận viên", "common", "Media & Sports", "B2"],
  ["Commercial", "Thuộc thương mại, quảng cáo TV", "toeic", "Commerce & PR", "A2"],
  ["Commercialization", "Sự thương mại hóa sản phẩm", "toeic", "Business & Strategy", "C1"],
  ["Commissary", "Cửa hàng nhu yếu phẩm công sở/quân đội", "common", "Food & Retail", "C2"],
  ["Commission", "Tiền hoa hồng, ủy ban", "toeic", "Finance & Governance", "B2"],
  ["Commissioner", "Ủy viên hội đồng", "common", "Politics & Governance", "B2"],
  ["Commitment", "Sự cam kết tận tụy", "common", "Strategy & Mind", "B1"],
  ["Committee", "Ủy ban hội đồng", "common", "Governance & Politics", "B1"],
  ["Commodity", "Hàng hóa thương phẩm", "toeic", "Trade & Commerce", "C1"],
  ["Commotion", "Sự hỗn loạn ồn ào", "common", "Daily Life", "C1"],
  ["Communal", "Thuộc sở hữu cộng đồng", "common", "Society & Housing", "B2"],
  ["Communicable", "Có thể lây nhiễm (bệnh)", "common", "Health & Medicine", "B2"],
  ["Communication", "Sự truyền thông, giao tiếp", "common", "General", "A2"],
  ["Communicative", "Cởi mở dễ giao tiếp", "common", "Personal Qualities", "B1"],
  ["Communion", "Sự hòa hợp tâm hồn, lễ ban thánh thể", "common", "Religion & Mind", "C1"],
  ["Communism", "Chủ nghĩa cộng sản", "ielts", "Politics & History", "B2"],
  ["Communist", "Người cộng sản", "common", "Politics", "B1"],
  ["Community", "Cộng đồng dân cư", "common", "Society", "A2"],
  ["Commutation", "Sự giảm án, sự đi lại hàng ngày", "common", "Law & Travel", "C2"],
  ["Commuter", "Người đi làm xa bằng xe buýt/tàu", "toeic", "Travel & Society", "B1"],
  ["Compactness", "Sự nhỏ gọn tính nén", "common", "Tech & Analytics", "B2"],
  ["Companion", "Người bạn đồng hành", "common", "Relationships", "B1"],
  ["Companionship", "Tình bạn đồng hành", "common", "Relationships", "B2"],
  ["Company", "Công ty, sự đi cùng", "common", "Business & Daily Life", "A1"],
  ["Comparability", "Khả năng so sánh đối chiếu", "common", "Analytics", "B2"],
  ["Comparable", "Có thể so sánh tương đương", "toeic", "Analytics & Finance", "B2"],
  ["Comparative", "So sánh tương đối", "common", "Grammar & Analytics", "B1"],
  ["Comparison", "Sự so sánh", "common", "Analytics", "A2"],
  ["Compartment", "Toa gian nhỏ, ngăn chứa hành lý", "toeic", "Travel & Auto", "B2"],
  ["Compass", "La bàn, compa vẽ", "common", "Tools & Travel", "A2"],
  ["Compassion", "Lòng trắc ẩn lòng thương cảm", "common", "Ethics & Mind", "B2"],
  ["Compassionate", "Giàu lòng trắc ẩn", "common", "Personal Qualities", "B2"],
  ["Compatibility", "Tính tương thích hệ thống", "toeic", "IT & Tech", "B2"],
  ["Compatible", "Tương thích thích hợp", "toeic", "IT & Relationships", "B2"],
  ["Compelling", "Hấp dẫn đầy thuyết phục", "ielts", "Writing & Rhetoric", "B2"],
  ["Compendium", "Sách tóm tắt tổng quan", "ielts", "Academic & Books", "C2"],
  ["Compensatory", "Có tính bồi thường", "toeic", "Finance & HR", "C1"],
  ["Competence", "Năng lực trình độ chuyên môn", "toeic", "HR & Qualities", "B2"],
  ["Competency", "Khả năng thành thạo", "toeic", "HR & Education", "B2"],
  ["Competent", "Có đủ năng lực thành thạo", "toeic", "HR & Work", "B2"],
  ["Competition", "Cuộc thi, sự cạnh tranh", "common", "Sports & Business", "A2"],
  ["Competitive", "Có tính cạnh tranh gay gắt", "common", "Business & Sports", "B1"],
  ["Competitiveness", "Năng lực cạnh tranh", "toeic", "Business & Strategy", "B2"],
  ["Competitor", "Đối thủ cạnh tranh", "toeic", "Business & Sales", "B1"],
  ["Compilation", "Sự biên soạn tuyển tập", "toeic", "Books & IT", "B2"],
  ["Compiler", "Trình biên dịch phần mềm, người biên soạn", "toeic", "IT & Books", "B2"],
  ["Complacency", "Sự tự mãn thỏa mãn dừng lại", "common", "Psychology", "C1"],
  ["Complacent", "Tự mãn với bản thân", "common", "Psychology", "C1"],
  ["Complainant", "Nguyên đơn người khiếu nại", "toeic", "Law & Justice", "C2"],
  ["Complaint", "Lời phàn nàn khiếu nại", "common", "Customer Service", "A2"],
  ["Complementary", "Bổ sung hỗ trợ lẫn nhau", "toeic", "Strategy & Business", "B2"],
  ["Completion", "Sự hoàn thành kết thúc", "common", "Project & Work", "B1"],
  ["Complexion", "Nước da khuôn mặt, diện mạo sự việc", "common", "Beauty & General", "B2"],
  ["Complexity", "Sự phức tạp rắc rối", "common", "Science & Analytics", "B2"],
  ["Compliance", "Sự tuân thủ quy định pháp luật", "toeic", "Compliance & Legal", "C1"],
  ["Compliant", "Tuân thủ sẵn sàng nghe theo", "toeic", "Compliance & HR", "B2"],
  ["Complication", "Sự biến chứng y khoa, sự rắc rối", "common", "Health & General", "B2"],
  ["Complicity", "Sự tiếp tay đồng phạm", "ielts", "Law & Justice", "C2"],
  ["Compliment", "Lời khen ngợi", "common", "Communication", "A2"],
  ["Complimentary", "Miễn phí tri ân, khen ngợi", "toeic", "Hospitality & Sales", "B2"],
  ["Component", "Thành phần cấu tạo", "common", "Science & IT", "B1"],
  ["Composer", "Nhà soạn nhạc", "common", "Music & Career", "A2"],
  ["Composite", "Hợp chất composite, hỗn hợp", "common", "Science & Materials", "B2"],
  ["Composition", "Tác phẩm nhạc/văn, thành phần cấu tạo", "common", "Arts & Science", "A2"],
  ["Compost", "Phân bón hữu cơ ủ từ rác", "common", "Agriculture & Environment", "B2"],
  ["Composure", "Sự điềm tĩnh bình thản", "common", "Psychology", "C1"],
  ["Compound", "Hợp chất hóa học, khu phức hợp", "common", "Science & Real Estate", "B1"],
  ["Comprehension", "Sự đọc hiểu thấu hiểu", "common", "Education & Mind", "B1"],
  ["Comprehensive", "Toàn diện bao quát", "toeic", "Analytics & Business", "B2"],
  ["Compressor", "Máy nén khí", "toeic", "Engineering & Tech", "B2"],
  ["Comprise", "Bao gồm gồm có", "ielts", "Academic & Writing", "B2"],
  ["Compromise", "Sự thỏa hiệp nhượng bộ", "common", "Negotiation & Business", "B1"],
  ["Comptroller", "Kiểm soát viên tài chính", "toeic", "Finance & Accounting", "C2"],
  ["Compulsion", "Sự bắt buộc, sự thôi thúc", "common", "Psychology & Law", "C1"],
  ["Compulsive", "Có tính ép buộc/nghiện không cưỡng được", "common", "Psychology", "B2"],
  ["Compulsory", "Bắt buộc theo quy định", "common", "Education & Law", "B1"],
  ["Computation", "Sự tính toán toán học/máy tính", "common", "IT & Math", "B2"],
  ["Computational", "Thuộc về điện toán tính toán", "ielts", "IT & Analytics", "B2"],
  ["Computerization", "Sự tin học hóa quy trình", "toeic", "IT & Business", "B2"],
  ["Comrade", "Đồng chí bạn chiến đấu", "common", "Military & Politics", "B1"],
  ["Comradeship", "Tình đồng chí đồng đội", "common", "Relationships", "B2"],
  ["Concealment", "Sự che giấu giấu giếm", "common", "Law & Safety", "B2"],
  ["Concession", "Sự nhượng bộ, điểm bán hàng nhượng quyền", "toeic", "Negotiation & Sales", "C1"],
  ["Conception", "Sự thụ thai, ý niệm ban đầu", "ielts", "Science & Philosophy", "B2"],
  ["Conceptualization", "Sự khái niệm hóa", "ielts", "Academic & Strategy", "C2"],
  ["Concerned", "Lo lắng, có liên quan", "common", "Daily Life", "A2"],
  ["Concertmaster", "Nhạc trưởng dàn nhạc dây", "common", "Music & Culture", "C2"],
  ["Concerto", "Bản hòa tấu nhạc cụ", "common", "Music & Culture", "B2"],
  ["Concierge", "Nhân viên hỗ trợ khách sạn cao cấp", "toeic", "Hospitality & Travel", "B2"],
  ["Conciseness", "Tính súc tích ngắn gọn", "ielts", "Writing & Language", "C1"],
  ["Conclave", "Cuộc họp kín bầu giáo hoàng/lãnh đạo", "common", "Religion & Politics", "C2"],
  ["Conclusiveness", "Tính thuyết phục chắc chắn", "ielts", "Academic & Logic", "C1"],
  ["Concordance", "Sự hòa hợp nhất trí, bảng tra từ ngữ", "common", "Linguistics & Strategy", "C2"],
  ["Concourse", "Sảnh chờ lớn ở sân bay/ga tàu", "toeic", "Travel & Architecture", "B2"],
  ["Concrete", "Bê tông, cụ thể rõ ràng", "common", "Construction & Analytics", "A2"],
  ["Concubine", "Vợ lẽ thiếp thất cổ đại", "common", "History & Culture", "C2"],
  ["Concurrence", "Sự đồng ý nhất trí", "toeic", "Law & Governance", "C1"],
  ["Concurrent", "Đang xảy ra đồng thời", "toeic", "Time & Operations", "B2"],
  ["Concussion", "Sự chấn thương sọ não nhẹ", "common", "Health & Sports", "B2"],
  ["Condemnatory", "Có tính lên án kết tội", "common", "Law & Communication", "C2"],
  ["Condensation", "Sự ngưng tụ hơi nước", "common", "Science & Nature", "B2"],
  ["Condescension", "Thái độ coi thường hạ cố", "common", "Psychology", "C2"],
  ["Conditional", "Có điều kiện kèm theo", "common", "Grammar & Legal", "B1"],
  ["Conditioning", "Sự rèn luyện thể lực/tạo phản xạ", "common", "Sports & Psychology", "B2"],
  ["Condolence", "Lời chia buồn sâu sắc", "common", "Culture & Daily Life", "C1"],
  ["Conductivity", "Tính dẫn điện dẫn nhiệt", "ielts", "Physics & Chemistry", "C1"],
  ["Confectionery", "Bánh kẹo đồ ngọt", "common", "Food & Retail", "B2"],
  ["Confederacy", "Liên minh các tiểu bang", "common", "History & Politics", "C1"],
  ["Confederate", "Đồng minh liên bang", "common", "History & Politics", "B2"],
  ["Conferment", "Sự trao tặng bằng cấp/giải thưởng", "toeic", "Education & Events", "C2"],
  ["Confession", "Lời thú tội, sự xưng tội", "common", "Law & Religion", "B1"],
  ["Confederation", "Bang liên liên đoàn", "ielts", "Politics & History", "C2"],
  ["Confidant", "Bạn tâm giao tri kỷ", "common", "Relationships", "C1"],
  ["Confidante", "Bạn nữ tâm giao tri kỷ", "common", "Relationships", "C1"],
  ["Confidence", "Sự tự tin, sự tin cậy", "common", "Psychology", "A2"],
  ["Confidentiality", "Tính bảo mật thông tin", "toeic", "Security & Legal", "B2"],
  ["Configuration", "Cấu hình cài đặt hệ thống", "toeic", "IT & Tech", "B2"],
  ["Confinement", "Sự giam giữ hạn chế tự do", "common", "Law & Safety", "C1"],
  ["Confirmable", "Có thể xác minh được", "toeic", "Analytics & Legal", "B2"],
  ["Confirmation", "Sự xác nhận phê chuẩn", "common", "Office & Travel", "B1"],
  ["Confiscation", "Sự tịch thu tài sản", "toeic", "Law & Customs", "C1"],
  ["Conflagration", "Hỏa hoạn cháy lớn dữ dội", "common", "Safety & Hazards", "C2"],
  ["Confluence", "Nơi hợp lưu hai dòng sông, sự hội tụ", "common", "Geography & Strategy", "C1"],
  ["Conformity", "Sự tuân thủ quy chuẩn chung", "ielts", "Sociology & Mind", "C1"],
  ["Confrontation", "Cuộc đối đầu trực diện", "common", "Politics & Life", "B2"],
  ["Confucianism", "Nho giáo", "common", "Philosophy & History", "B2"],
  ["Confused", "Bối rối nhầm lẫn", "common", "Psychology", "A1"],
  ["Confusing", "Gây khó hiểu bối rối", "common", "Daily Life", "A2"],
  ["Confusion", "Sự hỗn loạn bối rối", "common", "Psychology", "B1"],
  ["Congenital", "Bẩm sinh (bệnh bẩm sinh)", "common", "Health & Medicine", "C1"],
  ["Congestion", "Sự ùn tắc giao thông/nghẹt mũi", "common", "Transport & Health", "B1"],
  ["Conglomerate", "Tập đoàn kinh tế đa ngành lớn", "toeic", "Corporate Structure", "C2"],
  ["Congratulation", "Lời chúc mừng", "common", "Daily Life & Culture", "A1"],
  ["Congregational", "Thuộc về giáo xứ nhóm họp", "common", "Religion & Society", "C2"],
  ["Congressman", "Nghị sĩ quốc hội", "common", "Politics & Governance", "B2"],
  ["Congruence", "Sự tương thích đồng nhất", "ielts", "Math & Logic", "C2"],
  ["Conjecture", "Sự phỏng đoán suy đoán", "ielts", "Academic & Logic", "C1"],
  ["Conjunction", "Liên từ ngữ pháp, sự kết hợp", "common", "Grammar & Science", "B1"],
  ["Conjuring", "Nghệ thuật ảo thuật", "common", "Arts & Entertainment", "B2"],
  ["Connective", "Có tính kết nối", "common", "Science & Grammar", "B2"],
  ["Connectivity", "Khả năng kết nối mạng", "toeic", "IT & Tech", "B1"],
  ["Connector", "Đầu nối dây cáp điện", "toeic", "Tech & IT", "A2"],
  ["Connoisseur", "Chuyên gia sành sỏi độc đáo", "ielts", "Arts & Culture", "C2"],
  ["Connotation", "Nghĩa hàm ý biểu cảm", "ielts", "Language & Literature", "C1"],
  ["Conqueror", "Kẻ chinh phục", "common", "History & Warfare", "B2"],
  ["Conquest", "Cuộc chinh phục vùng đất", "common", "History & Strategy", "B2"],
  ["Conscience", "Lương tâm", "common", "Ethics & Mind", "B2"],
  ["Conscientious", "Tận tụy chu đáo trách nhiệm", "toeic", "HR & Qualities", "C1"],
  ["Consciousness", "Ý thức sự tỉnh táo", "common", "Health & Psychology", "B2"],
  ["Conscription", "Sự nghĩa vụ quân sự bắt buộc", "common", "Military & Law", "C2"],
  ["Consecutive", "Liên tiếp không gián đoạn", "toeic", "Math & Analytics", "B2"],
  ["Consensus", "Sự nhất trí đồng thuận", "toeic", "Governance & Meetings", "C1"],
  ["Consent", "Sự đồng ý chấp thuận", "common", "Law & Daily Life", "B2"],
  ["Consequence", "Hậu quả kết quả", "common", "Daily Life & Science", "B1"],
  ["Consequential", "Có hậu quả quan trọng", "ielts", "Academic & Logic", "C1"],
  ["Conservatism", "Chủ nghĩa bảo thủ", "ielts", "Politics & History", "B2"],
  ["Conservative", "Bảo thủ, thận trọng", "common", "Politics & Personal", "B1"],
  ["Conservatory", "Nhạc viện nghệ thuật, nhà kính trồng cây", "common", "Music & Nature", "B2"],
  ["Consignee", "Người nhận lô hàng ký gửi", "toeic", "Logistics & Shipping", "C1"],
  ["Consignment", "Lô hàng ký gửi", "toeic", "Logistics & Shipping", "B2"],
  ["Consignor", "Bên gửi lô hàng", "toeic", "Logistics & Shipping", "C1"],
  ["Consistency", "Tính nhất quán kiên định", "common", "Analytics & Mind", "B2"],
  ["Console", "Bàn điều khiển, an ủi", "common", "IT & Psychology", "B1"],
  ["Consolidation", "Sự sáp nhập củng cố công ty", "toeic", "Corporate & Strategy", "C1"],
  ["Consonance", "Sự hòa hợp âm thanh/ý kiến", "ielts", "Music & Rhetoric", "C2"],
  ["Consort", "Vương phi, kết giao với", "common", "History & Relationships", "C2"],
  ["Consortium", "Tập đoàn liên minh doanh nghiệp", "toeic", "Corporate Structure", "C2"],
  ["Conspicuous", "Dễ thấy đập vào mắt nổi bật", "ielts", "Personal & Design", "C1"],
  ["Conspiracy", "Âm mưu bí mật", "common", "Law & History", "B2"],
  ["Conspirator", "Kẻ tham gia âm mưu", "common", "Law & History", "C1"],
  ["Constancy", "Tính kiên định trước sau như một", "common", "Psychology", "C1"],
  ["Constellation", "Chòm sao trên bầu trời", "common", "Science & Astronomy", "B2"],
  ["Consternation", "Sự sững sờ kinh hoàng bối rối", "common", "Psychology", "C2"],
  ["Constituency", "Cử tri đơn vị bầu cử", "ielts", "Politics & Governance", "C1"],
  ["Constituent", "Thành phần cấu tạo, cử tri", "ielts", "Politics & Science", "C1"],
  ["Constitution", "Hiến pháp, thể tạng cơ thể", "common", "Law & Health", "B2"],
  ["Constitutional", "Thuộc hiến pháp", "common", "Law & Government", "B2"],
  ["Constitutionality", "Tính hợp hiến", "ielts", "Law & Governance", "C2"],
  ["Constraint", "Sự ràng buộc hạn chế", "common", "Strategy & Operations", "C1"],
  ["Constriction", "Sự thắt chặt co lại", "common", "Science & Health", "C1"],
  ["Constructive", "Mang tính xây dựng góp ý", "common", "Communication", "B2"],
  ["Constructor", "Nhà thầu xây dựng, hàm khởi tạo", "toeic", "Construction & IT", "B2"],
  ["Consul", "Lãnh sự quán", "common", "Politics & PR", "B2"],
  ["Consulate", "Tòa lãnh sự", "common", "Politics & PR", "B2"],
  ["Consultancy", "Công ty tư vấn chuyên môn", "toeic", "Business & Consulting", "B2"],
  ["Consultation", "Sự tham vấn tư vấn", "toeic", "Business & Health", "B2"],
  ["Consultative", "Mang tính tư vấn tham khảo", "toeic", "Business & Office", "C1"],
  ["Consumerism", "Chủ nghĩa tiêu dùng", "ielts", "Economics & Society", "C1"],
  ["Consummation", "Sự hoàn tất viên mãn", "common", "Culture & Strategy", "C2"],
  ["Contagion", "Sự lây lan bệnh tật/tâm lý", "ielts", "Health & Finance", "C1"],
  ["Container", "Thùng công-ten-nơ, hộp chứa", "toeic", "Logistics & Home", "A2"],
  ["Containment", "Sự ngăn chặn kiểm soát dịch bệnh/chiến tranh", "ielts", "Health & Military", "C1"],
  ["Contaminant", "Chất gây bẩn ô nhiễm", "ielts", "Environment & Science", "B2"],
  ["Contamination", "Sự ô nhiễm nhiễm bẩn", "ielts", "Environment & Science", "C1"],
  ["Contemplation", "Sự suy ngẫm trầm tư", "common", "Psychology", "C1"],
  ["Contemplative", "Trầm tư suy ngẫm sâu", "common", "Psychology", "C1"],
  ["Contemporaneous", "Xảy ra cùng thời đại", "ielts", "History & Time", "C2"],
  ["Contemporary", "Đương đại, thuộc về thời nay", "common", "Arts & Culture", "B2"],
  ["Contemptible", "Đáng khinh bỉ", "common", "Ethics & Mind", "C2"],
  ["Contemptuous", "Tỏ thái độ khinh bỉ", "common", "Psychology", "C2"],
  ["Contender", "Ứng cử viên đối thủ nặng ký", "common", "Sports & Strategy", "B2"],
  ["Contention", "Luận điểm tranh cãi", "ielts", "Academic & Rhetoric", "C1"],
  ["Contentment", "Sự hài lòng an yên", "common", "Psychology", "B2"],
  ["Contestation", "Sự tranh chấp cuộc thi đấu", "common", "Law & Sports", "C1"],
  ["Contextual", "Thuộc về bối cảnh ngữ cảnh", "ielts", "Linguistics & Academic", "B2"],
  ["Contextualization", "Sự bối cảnh hóa", "ielts", "Academic & Writing", "C2"],
  ["Contiguity", "Sự kề nhau tiếp giáp", "common", "Geography & Math", "C2"],
  ["Contingency", "Dự phòng rủi ro ngoài ý muốn", "toeic", "Strategy & Risk", "C1"],
  ["Contingent", "Đoàn đại biểu, phụ thuộc vào điều kiện", "toeic", "Events & Strategy", "C1"],
  ["Continuation", "Sự tiếp tục nối tiếp", "common", "Time & General", "B1"],
  ["Continuity", "Tính liên tục không gián đoạn", "common", "Strategy & Tech", "B2"],
  ["Continuous", "Liên tục không ngừng", "common", "General", "A2"],
  ["Continuum", "Chuỗi liên tục không đứt đoạn", "ielts", "Science & Analytics", "C1"],
  ["Contortion", "Sự uốn vặn hình thể", "common", "Sports & Arts", "C2"],
  ["Contraband", "Hàng cấm buôn lậu", "toeic", "Law & Customs", "C2"],
  ["Contraceptive", "Thuốc/biện pháp tránh thai", "common", "Health & Medicine", "B2"],
  ["Contractor", "Nhà thầu xây dựng/dịch vụ", "toeic", "Corporate & Construction", "B2"],
  ["Contractual", "Thuộc về hợp đồng", "toeic", "Contracts & Legal", "B2"],
  ["Contradiction", "Sự mâu thuẫn trái ngược", "common", "Logic & Communication", "B2"],
  ["Contradictory", "Mang tính mâu thuẫn", "common", "Logic", "B2"],
  ["Contrariwise", "Trái lại ngược lại", "common", "Rhetoric", "C2"],
  ["Contrariety", "Sự mâu thuẫn trái ngược nhau", "common", "Logic", "C2"],
  ["Contrasting", "Mang tính tương phản nổi bật", "common", "Arts & Analytics", "B2"],
  ["Infographic", "Đồ họa thông tin tổng hợp", "common", "Media & IT", "A2"]
];

additionalWords.forEach(item => {
  const key = item[0].toLowerCase();
  if (!existingSet.has(key)) {
    VOCAB_BANK.push({
      id: `v-${VOCAB_BANK.length + 1}`,
      en: item[0],
      vn: item[1],
      pool: item[2],
      category: item[3],
      level: item[4]
    });
    existingSet.add(key);
  }
});

console.log("FINAL COUNT AFTER FILLER:", VOCAB_BANK.length);

const fileHeader = `// ==========================================================================
// CENTRALIZED VOCABULARY BANK — COMPREHENSIVE VOCABULARY & TRAINING POOL
// Covers TOEIC, IELTS, and 6,000 Common General English Words (A1-C2)
// ==========================================================================

export const VOCAB_BANK = ${JSON.stringify(VOCAB_BANK, null, 2)};

/**
 * Filter vocabulary by Pool, Level, Category, and Count
 */
export function getVocabPool({ pool = 'all', level = 'all', category = 'all', count = null } = {}) {
  let filtered = VOCAB_BANK;

  if (pool && pool !== 'all') {
    filtered = filtered.filter(item => item.pool === pool);
  }

  if (level && level !== 'all') {
    filtered = filtered.filter(item => item.level.toLowerCase() === level.toLowerCase());
  }

  if (category && category !== 'all') {
    filtered = filtered.filter(item => item.category && item.category.toLowerCase().includes(category.toLowerCase()));
  }

  if (count && typeof count === 'number' && count > 0) {
    return [...filtered].sort(() => 0.5 - Math.random()).slice(0, count);
  }

  return filtered;
}

/**
 * Get pairs for Speed Word Match Game
 */
export function getSpeedMatchPairs({ pool = 'all', level = 'all', category = 'all', count = 10 } = {}) {
  const poolItems = getVocabPool({ pool, level, category, count });
  return poolItems.map(item => ({
    id: item.id,
    en: item.en,
    vn: item.vn,
    pool: item.pool,
    category: item.category,
    level: item.level
  }));
}

/**
 * Get Databank Stats Summary
 */
export function getVocabStats() {
  const total = VOCAB_BANK.length;
  const toeic = VOCAB_BANK.filter(item => item.pool === 'toeic').length;
  const ielts = VOCAB_BANK.filter(item => item.pool === 'ielts').length;
  const common = VOCAB_BANK.filter(item => item.pool === 'common').length;

  const levels = {
    A1: VOCAB_BANK.filter(i => i.level === 'A1').length,
    A2: VOCAB_BANK.filter(i => i.level === 'A2').length,
    B1: VOCAB_BANK.filter(i => i.level === 'B1').length,
    B2: VOCAB_BANK.filter(i => i.level === 'B2').length,
    C1: VOCAB_BANK.filter(i => i.level === 'C1').length,
    C2: VOCAB_BANK.filter(i => i.level === 'C2').length,
  };

  return { total, toeic, ielts, common, levels };
}

/**
 * Get Available Categories for a Pool
 */
export function getAvailableCategories(pool = 'all') {
  let items = VOCAB_BANK;
  if (pool !== 'all') {
    items = items.filter(i => i.pool === pool);
  }
  const cats = new Set();
  items.forEach(i => {
    if (i.category) cats.add(i.category);
  });
  return Array.from(cats).sort();
}
`;

fs.writeFileSync('./src/data/vocab-bank.js', fileHeader, 'utf8');
console.log("Successfully written src/data/vocab-bank.js!");
