import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Helper data arrays for generating 3000 high-quality training words
const prefixes = ["re", "un", "dis", "in", "im", "non", "over", "under", "pre", "sub", "super", "inter", "trans", "anti", "auto", "micro", "multi", "poly"];
const suffixes = ["able", "ible", "al", "ance", "ence", "ant", "ent", "ary", "ate", "ation", "ed", "en", "er", "est", "ful", "ic", "ify", "ing", "ish", "ism", "ist", "ity", "ive", "ize", "less", "ly", "ment", "ness", "ous", "ship", "tion", "ty"];

const wordList = [
  // A
  { en: "ability", vn: "khả năng, năng lực", cat: "Education" },
  { en: "abolish", vn: "bãi bỏ, hủy bỏ", cat: "Law & Ethics" },
  { en: "abundant", vn: "dồi dào, phong phú", cat: "Environment" },
  { en: "academic", vn: "thuộc học thuật", cat: "Education" },
  { en: "accelerate", vn: "gia tốc, làm nhanh hơn", cat: "Tech & AI" },
  { en: "accent", vn: "giọng điệu, trọng âm", cat: "Public Speaking" },
  { en: "accept", vn: "chấp nhận, đồng ý", cat: "Psychology" },
  { en: "acceptable", vn: "có thể chấp nhận", cat: "Work & Career" },
  { en: "access", vn: "quyền truy cập, tiếp cận", cat: "Tech & AI" },
  { en: "accessible", vn: "dễ tiếp cận, có sẵn", cat: "Tech & AI" },
  { en: "accident", vn: "tai nạn, sự cố", cat: "Safety & Emergency" },
  { en: "accommodate", vn: "cung cấp chỗ ở, đáp ứng", cat: "Travel & Tourism" },
  { en: "accommodation", vn: "chỗ ở, phòng nghỉ", cat: "Travel & Tourism" },
  { en: "accompany", vn: "đi cùng, đồng hành", cat: "Family & Life" },
  { en: "accomplish", vn: "hoàn thành, đạt được", cat: "Work & Career" },
  { en: "accordance", vn: "sự phù hợp, làm theo", cat: "Law & Ethics" },
  { en: "account", vn: "tài khoản, bản kê khai", cat: "Finance" },
  { en: "accountant", vn: "nhân viên kế toán", cat: "Work & Career" },
  { en: "accumulate", vn: "tích lũy, dồn lại", cat: "Finance" },
  { en: "accuracy", vn: "sự chính xác", cat: "Science & Space" },
  { en: "accurate", vn: "chính xác, chuẩn xác", cat: "Science & Space" },
  { en: "achieve", vn: "đạt được, thành công", cat: "Future & Goals" },
  { en: "achievement", vn: "thành tựu, kết quả", cat: "Future & Goals" },
  { en: "acknowledge", vn: "công nhận, thừa nhận", cat: "Public Speaking" },
  { en: "acquire", vn: "thu được, có được", cat: "Education" },
  { en: "acquisition", vn: "sự thâu tóm, thu mua", cat: "Finance" },
  { en: "action", vn: "hành động", cat: "Daily Life" },
  { en: "activate", vn: "kích hoạt", cat: "Tech & AI" },
  { en: "active", vn: "năng động, chủ động", cat: "Health & Mind" },
  { en: "activity", vn: "hoạt động", cat: "Daily Life" },
  { en: "adapt", vn: "thích nghi, thích ứng", cat: "Psychology" },
  { en: "addition", vn: "sự thêm vào, phép cộng", cat: "Education" },
  { en: "additional", vn: "bổ sung, thêm vào", cat: "Work & Career" },
  { en: "address", vn: "địa chỉ, phát biểu", cat: "Public Speaking" },
  { en: "adequate", vn: "đầy đủ, thỏa đáng", cat: "Health & Mind" },
  { en: "adjust", vn: "điều chỉnh, sửa lại", cat: "Tech & AI" },
  { en: "administer", vn: "quản lý, điều hành", cat: "Work & Career" },
  { en: "administration", vn: "sự quản lý, ban quản trị", cat: "Work & Career" },
  { en: "admire", vn: "khâm phục, ngưỡng mộ", cat: "Psychology" },
  { en: "admission", vn: "sự nhận vào, vé vào cửa", cat: "Education" },
  { en: "adopt", vn: "nhận nuôi, áp dụng", cat: "Family & Life" },
  { en: "advance", vn: "tiến bộ, phát triển", cat: "Future & Goals" },
  { en: "advantage", vn: "lợi thế, ưu điểm", cat: "Work & Career" },
  { en: "adventure", vn: "chuyến phiêu lưu", cat: "Travel & Tourism" },
  { en: "advertisement", vn: "quảng cáo", cat: "Shopping & Style" },
  { en: "advice", vn: "lời khuyên", cat: "Family & Life" },
  { en: "advocate", vn: "ủng hộ, người biện hộ", cat: "Law & Ethics" },
  { en: "aesthetic", vn: "thuộc thẩm mỹ", cat: "Arts & Culture" },
  { en: "afford", vn: "chi trả được", cat: "Finance" },
  { en: "affordable", vn: "giá cả phải chăng", cat: "Shopping & Style" },
  { en: "agency", vn: "đại lý, cơ quan", cat: "Work & Career" },
  { en: "agenda", vn: "chương trình họp", cat: "Work & Career" },
  { en: "agent", vn: "người đại diện", cat: "Work & Career" },
  { en: "aggressive", vn: "hung hăng, hăng hái", cat: "Psychology" },
  { en: "agile", vn: "nhanh nhẹn, linh hoạt", cat: "Tech & AI" },
  { en: "agreement", vn: "hợp đồng, thỏa thuận", cat: "Law & Ethics" },
  { en: "agriculture", vn: "nông nghiệp", cat: "Environment" },
  { en: "aircraft", vn: "máy bay", cat: "Travel & Tourism" },
  { en: "airline", vn: "hãng hàng không", cat: "Travel & Tourism" },
  { en: "airport", vn: "sân bay", cat: "Travel & Tourism" },
  { en: "alarm", vn: "chuông báo động", cat: "Safety & Emergency" },
  { en: "algorithm", vn: "thuật toán", cat: "Tech & AI" },
  { en: "alien", vn: "ngoài hành tinh, xa lạ", cat: "Science & Space" },
  { en: "alignment", vn: "sự căn chỉnh, liên minh", cat: "Tech & AI" },
  { en: "alleviate", vn: "xoa dịu, giảm nhẹ", cat: "Health & Mind" },
  { en: "alliance", vn: "sự liên minh", cat: "News & Society" },
  { en: "allocate", vn: "phân bổ", cat: "Finance" },
  { en: "allowance", vn: "tiền trợ cấp", cat: "Finance" },
  { en: "alteration", vn: "sự thay đổi", cat: "Shopping & Style" },
  { en: "alternative", vn: "lựa chọn thay thế", cat: "Future & Goals" },
  { en: "altitude", vn: "độ cao", cat: "Science & Space" },
  { en: "altruism", vn: "lòng vị tha", cat: "Philosophy" },
  { en: "amateur", vn: "nghiệp dư", cat: "Sports & Hobbies" },
  { en: "ambassador", vn: "đại sứ", cat: "News & Society" },
  { en: "ambiguity", vn: "sự mơ hồ", cat: "Philosophy" },
  { en: "ambiguous", vn: "mơ hồ, nhập nhằng", cat: "Philosophy" },
  { en: "ambition", vn: "tham vọng, hoài bão", cat: "Future & Goals" },
  { en: "ambitious", vn: "có tham vọng", cat: "Future & Goals" },
  { en: "ambulance", vn: "xe cấp cứu", cat: "Safety & Emergency" },
  { en: "amend", vn: "sửa đổi (luật)", cat: "Law & Ethics" },
  { en: "amendment", vn: "tu chính án", cat: "Law & Ethics" },
  { en: "amenity", vn: "tiện nghi", cat: "Travel & Tourism" },
  { en: "amount", vn: "số lượng, số tiền", cat: "Finance" },
  { en: "analogy", vn: "phép ví von, tương tự", cat: "Public Speaking" },
  { en: "analyse", vn: "phân tích", cat: "Science & Space" },
  { en: "analysis", vn: "bản phân tích", cat: "Science & Space" },
  { en: "analyst", vn: "chuyên viên phân tích", cat: "Work & Career" },
  { en: "analytical", vn: "có tính phân tích", cat: "Education" },
  { en: "anarchy", vn: "vô chính phủ", cat: "History & World" },
  { en: "anatomy", vn: "giải phẫu học", cat: "Health & Mind" },
  { en: "ancestor", vn: "tổ tiên", cat: "History & World" },
  { en: "ancient", vn: "cổ kính", cat: "History & World" },
  { en: "anecdote", vn: "giai thoại", cat: "Public Speaking" },
  { en: "angle", vn: "góc độ", cat: "Science & Space" },
  { en: "anguish", vn: "sự dằn dặt", cat: "Psychology" },
  { en: "animal", vn: "động vật", cat: "Pets & Animals" },
  { en: "animation", vn: "hoạt hình", cat: "Arts & Culture" },
  { en: "anniversary", vn: "ngày kỷ niệm", cat: "Festivals" },
  { en: "announce", vn: "thông báo", cat: "Public Speaking" },
  { en: "announcement", vn: "bản thông báo", cat: "Work & Career" },
  { en: "annual", vn: "hàng năm", cat: "Work & Career" },
  { en: "annually", vn: "mỗi năm", cat: "Work & Career" },
  { en: "anonymous", vn: "ẩn danh", cat: "Tech & AI" },
  { en: "anticipate", vn: "dự đoán, lường trước", cat: "Future & Goals" },
  { en: "anticipation", vn: "sự mong đợi", cat: "Future & Goals" },
  { en: "anxiety", vn: "sự lo âu", cat: "Psychology" },
  { en: "anxious", vn: "lo âu", cat: "Psychology" },
  { en: "apartment", vn: "căn hộ", cat: "Home & Living" },
  { en: "apologize", vn: "xin lỗi", cat: "Family & Life" },
  { en: "apology", vn: "lời xin lỗi", cat: "Family & Life" },
  { en: "apparent", vn: "rõ ràng", cat: "Science & Space" },
  { en: "appeal", vn: "sự lôi cuốn, kháng cáo", cat: "Law & Ethics" },
  { en: "appearance", vn: "ngoại hình", cat: "Shopping & Style" },
  { en: "appetite", vn: "khẩu vị, thèm ăn", cat: "Food & Dining" },
  { en: "applaud", vn: "vỗ tay tán thưởng", cat: "Arts & Culture" },
  { en: "applause", vn: "tiếng vỗ tay", cat: "Arts & Culture" },
  { en: "appliance", vn: "thiết bị gia dụng", cat: "Home & Living" },
  { en: "applicant", vn: "ứng viên", cat: "Work & Career" },
  { en: "application", vn: "ứng dụng, đơn từ", cat: "Tech & AI" },
  { en: "apply", vn: "nộp đơn, áp dụng", cat: "Work & Career" },
  { en: "appoint", vn: "bổ nhiệm", cat: "Work & Career" },
  { en: "appointment", vn: "cuộc hẹn", cat: "Work & Career" },
  { en: "appraisal", vn: "sự đánh giá", cat: "Work & Career" },
  { en: "appreciate", vn: "trân trọng", cat: "Family & Life" },
  { en: "appreciation", vn: "sự trân trọng", cat: "Family & Life" },
  { en: "approach", vn: "tiếp cận, phương pháp", cat: "Work & Career" },
  { en: "appropriate", vn: "phù hợp", cat: "Education" },
  { en: "approval", vn: "sự phê duyệt", cat: "Work & Career" },
  { en: "approve", vn: "phê duyệt", cat: "Work & Career" },
  { en: "approximate", vn: "xấp xỉ", cat: "Finance" },
  { en: "aptitude", vn: "năng khiếu", cat: "Education" },
  { en: "aquarium", vn: "thủy cung", cat: "Pets & Animals" },
  { en: "arbitrary", vn: "tùy hứng", cat: "Philosophy" },
  { en: "archaeology", vn: "khảo cổ học", cat: "History & World" },
  { en: "architect", vn: "kiến trúc sư", cat: "Home & Living" },
  { en: "architecture", vn: "kiến trúc", cat: "Home & Living" },
  { en: "archive", vn: "kho lưu trữ", cat: "Tech & AI" },
  { en: "arduous", vn: "gian gian", cat: "Work & Career" },
  { en: "argue", vn: "tranh luận", cat: "Public Speaking" },
  { en: "argument", vn: "lập luận", cat: "Public Speaking" },
  { en: "arise", vn: "nảy sinh", cat: "Work & Career" },
  { en: "arithmetic", vn: "số học", cat: "Education" },
  { en: "aroma", vn: "hương thơm", cat: "Food & Dining" },
  { en: "arrange", vn: "sắp xếp", cat: "Work & Career" },
  { en: "arrangement", vn: "sự sắp xếp", cat: "Work & Career" },
  { en: "array", vn: "mảng, danh sách", cat: "Tech & AI" },
  { en: "arrest", vn: "bắt giữ", cat: "Law & Ethics" },
  { en: "arrival", vn: "sự đến nơi", cat: "Travel & Tourism" },
  { en: "arrive", vn: "đến nơi", cat: "Travel & Tourism" },
  { en: "arrogant", vn: "kiêu ngạo", cat: "Psychology" },
  { en: "article", vn: "bài báo", cat: "News & Society" },
  { en: "articulate", vn: "diễn đạt trôi chảy", cat: "Public Speaking" },
  { en: "artificial", vn: "nhân tạo", cat: "Tech & AI" },
  { en: "artist", vn: "họa sĩ", cat: "Arts & Culture" },
  { en: "artistic", vn: "có tính nghệ thuật", cat: "Arts & Culture" },
  { en: "ascertain", vn: "xác minh", cat: "Science & Space" },
  { en: "aspect", vn: "khía cạnh", cat: "Education" },
  { en: "aspiration", vn: "khát vọng", cat: "Future & Goals" },
  { en: "aspire", vn: "khao khát", cat: "Future & Goals" },
  { en: "assemble", vn: "lắp ráp", cat: "Work & Career" },
  { en: "assembly", vn: "hội đồng, sự lắp ráp", cat: "Work & Career" },
  { en: "assert", vn: "khẳng định", cat: "Public Speaking" },
  { en: "assertion", vn: "sự khẳng định", cat: "Public Speaking" },
  { en: "assess", vn: "đánh giá", cat: "Education" },
  { en: "assessment", vn: "bài đánh giá", cat: "Education" },
  { en: "asset", vn: "tài sản", cat: "Finance" },
  { en: "assign", vn: "giao việc", cat: "Work & Career" },
  { en: "assignment", vn: "nhiệm vụ", cat: "Education" },
  { en: "assimilate", vn: "đồng hóa, tiếp thu", cat: "News & Society" },
  { en: "assist", vn: "hỗ trợ", cat: "Work & Career" },
  { en: "assistance", vn: "sự hỗ trợ", cat: "Work & Career" },
  { en: "assistant", vn: "trợ lý", cat: "Work & Career" },
  { en: "associate", vn: "đối tác, liên kết", cat: "Work & Career" },
  { en: "association", vn: "hiệp hội", cat: "News & Society" },
  { en: "assume", vn: "cho rằng, đảm nhận", cat: "Work & Career" },
  { en: "assumption", vn: "giả định", cat: "Philosophy" },
  { en: "assurance", vn: "sự bảo đảm", cat: "Law & Ethics" },
  { en: "assure", vn: "cam đoan", cat: "Work & Career" },
  { en: "astronomy", vn: "thiên văn học", cat: "Science & Space" },
  { en: "astrophysics", vn: "vật lý thiên văn", cat: "Science & Space" },
  { en: "athlete", vn: "vận động viên", cat: "Sports & Hobbies" },
  { en: "atmosphere", vn: "bầu không khí", cat: "Environment" },
  { en: "atom", vn: "nguyên tử", cat: "Science & Space" },
  { en: "attach", vn: "đính kèm", cat: "Tech & AI" },
  { en: "attachment", vn: "tệp đính kèm", cat: "Tech & AI" },
  { en: "attain", vn: "đạt được", cat: "Future & Goals" },
  { en: "attempt", vn: "nỗ lực", cat: "Future & Goals" },
  { en: "attend", vn: "tham dự", cat: "Work & Career" },
  { en: "attendance", vn: "sự tham dự", cat: "Education" },
  { en: "attendant", vn: "tiếp viên", cat: "Travel & Tourism" },
  { en: "attention", vn: "sự chú ý", cat: "Daily Life" },
  { en: "attitude", vn: "thái độ", cat: "Psychology" },
  { en: "attorney", vn: "luật sư", cat: "Law & Ethics" },
  { en: "attract", vn: "thu hút", cat: "Shopping & Style" },
  { en: "attraction", vn: "điểm thu hút", cat: "Travel & Tourism" },
  { en: "attractive", vn: "hấp dẫn", cat: "Shopping & Style" },
  { en: "attribute", vn: "thuộc tính", cat: "Science & Space" },
  { en: "auction", vn: "buổi đấu giá", cat: "Finance" },
  { en: "audience", vn: "khán giả", cat: "Public Speaking" },
  { en: "audit", vn: "kiểm toán", cat: "Finance" },
  { en: "auditorium", vn: "hội trường", cat: "Education" },
  { en: "augment", vn: "tăng cường", cat: "Tech & AI" },
  { en: "authentic", vn: "chân thực", cat: "Arts & Culture" },
  { en: "author", vn: "tác giả", cat: "Arts & Culture" },
  { en: "authority", vn: "chính quyền, thẩm quyền", cat: "Law & Ethics" },
  { en: "authorization", vn: "sự ủy quyền", cat: "Law & Ethics" },
  { en: "authorize", vn: "ủy quyền", cat: "Law & Ethics" },
  { en: "automate", vn: "tự động hóa", cat: "Tech & AI" },
  { en: "automatic", vn: "tự động", cat: "Tech & AI" },
  { en: "automation", vn: "sự tự động hóa", cat: "Tech & AI" },
  { en: "automobile", vn: "xe hơi", cat: "Travel & Tourism" },
  { en: "autonomous", vn: "tự chủ, tự hành", cat: "Tech & AI" },
  { en: "autonomy", vn: "quyền tự chủ", cat: "Philosophy" },
  { en: "availability", vn: "sự có sẵn", cat: "Work & Career" },
  { en: "available", vn: "có sẵn", cat: "Work & Career" },
  { en: "avalanche", vn: "tuyết lở", cat: "Safety & Emergency" },
  { en: "avenue", vn: "đại lộ", cat: "Home & Living" },
  { en: "average", vn: "trung bình", cat: "Education" },
  { en: "avert", vn: "ngăn chặn", cat: "Safety & Emergency" },
  { en: "aviation", vn: "ngành hàng không", cat: "Travel & Tourism" },
  { en: "avoid", vn: "tránh né", cat: "Health & Mind" },
  { en: "avoidance", vn: "sự tránh né", cat: "Health & Mind" },
  { en: "await", vn: "chờ đợi", cat: "Future & Goals" },
  { en: "awake", vn: "thức giấc", cat: "Health & Mind" },
  { en: "award", vn: "giải thưởng", cat: "Arts & Culture" },
  { en: "aware", vn: "nhận thức được", cat: "Psychology" },
  { en: "awareness", vn: "sự nhận thức", cat: "Psychology" }
];

console.log("Seed words count:", wordList.length);
