import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const gamesDataPath = path.join(__dirname, '../src/data/games-data.js');

// Base list of categories and prefix/suffix root combinations to generate 3000+ distinct English-Vietnamese vocabulary pairs
const baseWords = [
  // A
  { en: "Abandon", vn: "Từ bỏ, ruồng bỏ", cat: "General" },
  { en: "Abbreviate", vn: "Viết tắt, rút ngắn", cat: "Academic" },
  { en: "Abdicating", vn: "Từ vị, nhường ngôi", cat: "Law & History" },
  { en: "Abdomen", vn: "Vùng bụng", cat: "Health & Medical" },
  { en: "Abduct", vn: "Bắt cóc, bắt đi", cat: "Law & Society" },
  { en: "Aberration", vn: "Sự lệch lạc, sự khác thường", cat: "Advanced Vocab" },
  { en: "Abide", vn: "Tuân theo, chịu đựng", cat: "TOEIC Mastery" },
  { en: "Ability", vn: "Khả năng, năng lực", cat: "Beginner" },
  { en: "Ablaze", vn: "Rực cháy, bùng cháy", cat: "Nature & Elements" },
  { en: "Abnormal", vn: "Bất thường, khác thường", cat: "Intermediate" },
  { en: "Aboard", vn: "Trên tàu/máy bay", cat: "Travel & Tourism" },
  { en: "Abolish", vn: "Bãi bỏ, hủy bỏ", cat: "Law & Ethics" },
  { en: "Abominable", vn: "Tồi tệ, đáng ghét", cat: "Advanced Vocab" },
  { en: "Abound", vn: "Có rất nhiều, dồi dào", cat: "Advanced Vocab" },
  { en: "Abrasive", vn: "Thô ráp, gây khó chịu", cat: "Advanced Vocab" },
  { en: "Abreast", vn: "Sóng hàng, cập nhật tin tức", cat: "TOEIC Mastery" },
  { en: "Abridge", vn: "Tóm tắt, rút ngắn sách", cat: "Academic" },
  { en: "Abrupt", vn: "Đột ngột, bất ngờ", cat: "Intermediate" },
  { en: "Absence", vn: "Sự vắng mặt", cat: "Work & Career" },
  { en: "Absolute", vn: "Tuyệt đối, hoàn toàn", cat: "Intermediate" },
  { en: "Absolve", vn: "Tuyên án vô tội, xá tội", cat: "Law & Ethics" },
  { en: "Absorb", vn: "Hấp thụ, thu hút", cat: "Science & Space" },
  { en: "Abstain", vn: "Kiêng nhịn, nhẫn nại", cat: "Health & Mind" },
  { en: "Abstract", vn: "Trừu tượng", cat: "Arts & Culture" },
  { en: "Absurd", vn: "Vô lý, ngớ ngẩn", cat: "Advanced Vocab" },
  { en: "Abundance", vn: "Sự phong phú, dồi dào", cat: "Advanced Vocab" },
  { en: "Abundant", vn: "Dồi dào, nhiều", cat: "Intermediate" },
  { en: "Abuse", vn: "Lạm dụng, ngược đãi", cat: "Law & Society" },
  { en: "Academic", vn: "Thuộc học thuật, viện sĩ", cat: "Education" },
  { en: "Accelerate", vn: "Tăng tốc, gia tăng", cat: "Tech & AI" },
  { en: "Accent", vn: "Giọng điệu, dấu nhấn", cat: "Education" },
  { en: "Accept", vn: "Chấp nhận, đồng ý", cat: "Beginner" },
  { en: "Access", vn: "Quyền truy cập, lối vào", cat: "Tech & AI" },
  { en: "Accessible", vn: "Dễ dàng tiếp cận", cat: "TOEIC Mastery" },
  { en: "Accessory", vn: "Phụ kiện, đồ kèm theo", cat: "Shopping & Fashion" },
  { en: "Accident", vn: "Tai nạn, sự cố", cat: "Safety & Emergency" },
  { en: "Acclaim", vn: "Sự hoan hô, ca ngợi", cat: "Arts & Culture" },
  { en: "Acclimate", vn: "Thích nghi thời tiết", cat: "Environment" },
  { en: "Accommodate", vn: "Cung cấp chỗ ở, đáp ứng", cat: "TOEIC Mastery" },
  { en: "Accompany", vn: "Đi cùng, đồng hành", cat: "Family & Life" },
  { en: "Accomplish", vn: "Hoàn thành, đạt được", cat: "Work & Career" },
  { en: "Accord", vn: "Hiệp định, sự hòa hợp", cat: "Law & Ethics" },
  { en: "Account", vn: "Tài khoản, bản kê khai", cat: "Finance" },
  { en: "Accountant", vn: "Kế toán viên", cat: "Work & Career" },
  { en: "Accreditation", vn: "Sự kiểm định chất lượng", cat: "Education" },
  { en: "Accumulate", vn: "Tích lũy, dồn lại", cat: "Finance" },
  { en: "Accuracy", vn: "Độ chính xác", cat: "Academic" },
  { en: "Accurate", vn: "Chính xác, chuẩn xác", cat: "Intermediate" },
  { en: "Accuse", vn: "Buộc tội, cáo buộc", cat: "Law & Ethics" },
  { en: "Accustom", vn: "Làm cho quen thuộc", cat: "Psychology" },
  { en: "Achieve", vn: "Đạt được mục tiêu", cat: "Beginner" },
  { en: "Achievement", vn: "Thành tựu", cat: "Intermediate" },
  { en: "Acid", vn: "A-xít, chất chua", cat: "Science & Space" },
  { en: "Acknowledge", vn: "Thừa nhận, công nhận", cat: "TOEIC Mastery" },
  { en: "Acquaintance", vn: "Người quen", cat: "Family & Life" },
  { en: "Acquire", vn: "Thu được, mua lại", cat: "TOEIC Mastery" },
  { en: "Acquisition", vn: "Sự thâu tóm, mua lại", cat: "Work & Career" },
  { en: "Acquit", vn: "Tuyên bố trắng án", cat: "Law & Ethics" },
  { en: "Acrimonious", vn: "Gay gắt, đắng chát", cat: "Advanced Vocab" },
  { en: "Acronym", vn: "Từ viết tắt chữ đầu", cat: "Academic" },
  { en: "Action", vn: "Hành động", cat: "Beginner" },
  { en: "Activate", vn: "Kích hoạt", cat: "Tech & AI" },
  { en: "Active", vn: "Năng động, chủ động", cat: "Beginner" },
  { en: "Activity", vn: "Hoạt động", cat: "Beginner" },
  { en: "Actor", vn: "Diễn viên nam", cat: "Arts & Culture" },
  { en: "Actress", vn: "Diễn viên nữ", cat: "Arts & Culture" },
  { en: "Actual", vn: "Thực sự, thực tế", cat: "Intermediate" },
  { en: "Actuary", vn: "Chuyên viên định phí", cat: "Finance" },
  { en: "Acute", vn: "Cấp tính, sắc bén", cat: "Health & Mind" },
  { en: "Adapt", vn: "Thích nghi", cat: "Intermediate" },
  { en: "Adaptable", vn: "Có thể thích nghi", cat: "Work & Career" },
  { en: "Adaptation", vn: "Sự thích nghi, tác phẩm chuyển thể", cat: "Arts & Culture" },
  { en: "Addiction", vn: "Sự nghiện ngập", cat: "Health & Mind" },
  { en: "Addition", vn: "Phép cộng, sự thêm vào", cat: "Education" },
  { en: "Additional", vn: "Bổ sung, thêm vào", cat: "TOEIC Mastery" },
  { en: "Address", vn: "Địa chỉ, diễn văn, giải quyết", cat: "Work & Career" },
  { en: "Adequate", vn: "Đầy đủ, thỏa đáng", cat: "TOEIC Mastery" },
  { en: "Adhere", vn: "Dính chặt, tuân thủ quy tắc", cat: "TOEIC Mastery" },
  { en: "Adhesive", vn: "Chất dính, keo dán", cat: "Home & Living" },
  { en: "Adjacent", vn: "Kế bên, liền kề", cat: "TOEIC Mastery" },
  { en: "Adjourn", vn: "Tạm dừng phiên họp", cat: "Law & Ethics" },
  { en: "Adjust", vn: "Điều chỉnh", cat: "Intermediate" },
  { en: "Adjustment", vn: "Sự điều chỉnh", cat: "TOEIC Mastery" },
  { en: "Administer", vn: "Quản lý, điều hành", cat: "Work & Career" },
  { en: "Administration", vn: "Ban quản lý, sự hành chính", cat: "Work & Career" },
  { en: "Admirable", vn: "Đáng khâm phục", cat: "Psychology" },
  { en: "Admiration", vn: "Sự khâm phục, ngưỡng mộ", cat: "Psychology" },
  { en: "Admire", vn: "Khâm phục, ngưỡng mộ", cat: "Beginner" },
  { en: "Admission", vn: "Sự nhận vào, vé vào cửa", cat: "Education" },
  { en: "Admit", vn: "Thừa nhận, nhận vào", cat: "Intermediate" },
  { en: "Adolescent", vn: "Thanh thiếu niên", cat: "Family & Life" },
  { en: "Adopt", vn: "Nhận nuôi, thông qua quy tắc", cat: "Family & Life" },
  { en: "Adoration", vn: "Sự sùng bái, yêu thương", cat: "Psychology" },
  { en: "Adorn", vn: "Trang trí, làm đẹp", cat: "Arts & Culture" },
  { en: "Adrenaline", vn: "Hormone kích thích", cat: "Health & Mind" },
  { en: "Adult", vn: "Người trưởng thành", cat: "Beginner" },
  { en: "Adulterate", vn: "Pha trộn làm giảm chất lượng", cat: "Law & Ethics" },
  { en: "Advance", vn: "Tiến bộ, tiền ứng trước", cat: "TOEIC Mastery" },
  { en: "Advanced", vn: "Nâng cao, tiên tiến", cat: "Education" },
  { en: "Advancement", vn: "Sự thăng tiến", cat: "Work & Career" },
  { en: "Advantage", vn: "Lợi thế, ưu điểm", cat: "Intermediate" },
  { en: "Advantageous", vn: "Có lợi, thuận lợi", cat: "TOEIC Mastery" },
  { en: "Advent", vn: "Sự xuất hiện, sự đến", cat: "Advanced Vocab" },
  { en: "Adventure", vn: "Chuyến phiêu lưu", cat: "Travel & Tourism" },
  { en: "Adversary", vn: "Đối thủ, kẻ thù", cat: "Law & Ethics" },
  { en: "Adverse", vn: "Bất lợi, tồi tệ", cat: "TOEIC Mastery" },
  { en: "Adversity", vn: "Sự nghịch cảnh, khó khăn", cat: "Advanced Vocab" },
  { en: "Advertise", vn: "Quảng cáo", cat: "Work & Career" },
  { en: "Advertisement", vn: "Bài quảng cáo", cat: "Work & Career" },
  { en: "Advice", vn: "Lời khuyên", cat: "Beginner" },
  { en: "Advise", vn: "Khuyên bảo", cat: "Beginner" },
  { en: "Adviser", vn: "Cố vấn", cat: "Work & Career" },
  { en: "Advocacy", vn: "Sự bào chữa, sự vận động", cat: "Law & Ethics" },
  { en: "Advocate", vn: "Ủng hộ, người chủ trương", cat: "TOEIC Mastery" },
  { en: "Aerial", vn: "Trên không, ăng-ten", cat: "Science & Space" },
  { en: "Aerodynamics", vn: "Khí động học", cat: "Science & Space" },
  { en: "Aerosol", vn: "Bình xịt hơi", cat: "Home & Living" },
  { en: "Aesthetic", vn: "Thuộc thẩm mỹ", cat: "Arts & Culture" },
  { en: "Affable", vn: "Lịch sự, niềm nở", cat: "Psychology" },
  { en: "Affair", vn: "Vụ việc, chuyện tình cảm", cat: "Family & Life" },
  { en: "Affect", vn: "Ảnh hưởng đến", cat: "Intermediate" },
  { en: "Affection", vn: "Tình cảm tha thiết", cat: "Family & Life" },
  { en: "Affiliate", vn: "Chi nhánh, gia nhập", cat: "Work & Career" },
  { en: "Affinity", vn: "Sự cuốn hút, mối quan hệ gần gũi", cat: "Psychology" },
  { en: "Affirm", vn: "Xác nhận, khẳng định", cat: "TOEIC Mastery" },
  { en: "Affirmation", vn: "Sự khẳng định", cat: "Psychology" },
  { en: "Affliction", vn: "Tai họa, sự đau đớn", cat: "Advanced Vocab" },
  { en: "Affluent", vn: "Giàu có, dồi dào", cat: "Advanced Vocab" },
  { en: "Afford", vn: "Có đủ khả năng chi trả", cat: "Finance" },
  { en: "Affordable", vn: "Giá cả hợp lý", cat: "Shopping & Fashion" },
  { en: "Afforestation", vn: "Sự trồng rừng", cat: "Environment" },
  { en: "Afraid", vn: "Sợ hãi, e ngại", cat: "Beginner" },
  { en: "Aftermath", vn: "Hậu quả sau thiên tai/sự cố", cat: "Safety & Emergency" },
  { en: "Afternoon", vn: "Buổi chiều", cat: "Beginner" },
  { en: "Agenda", vn: "Chương trình nghị sự", cat: "Work & Career" },
  { en: "Agent", vn: "Đại lý, tác nhân", cat: "Work & Career" },
  { en: "Aggravate", vn: "Làm trầm trọng thêm", cat: "Advanced Vocab" },
  { en: "Aggregate", vn: "Tổng số, gộp lại", cat: "Finance" },
  { en: "Aggression", vn: "Sự xâm lược, sự hung hăng", cat: "Psychology" },
  { en: "Aggressive", vn: "Hung hăng, quyết đoán", cat: "Psychology" },
  { en: "Agile", vn: "Nhanh nhẹn, linh hoạt", cat: "Work & Career" },
  { en: "Agility", vn: "Sự nhanh nhạy", cat: "Sports & Hobbies" },
  { en: "Agitate", vn: "Kích động, làm xáo động", cat: "Psychology" },
  { en: "Agony", vn: "Sự đau đớn dữ dội", cat: "Health & Mind" },
  { en: "Agree", vn: "Đồng ý", cat: "Beginner" },
  { en: "Agreeable", vn: "Dễ chịu, đồng ý", cat: "Psychology" },
  { en: "Agreement", vn: "Hợp đồng, sự thỏa thuận", cat: "TOEIC Mastery" },
  { en: "Agriculture", vn: "Nông nghiệp", cat: "Environment" },
  { en: "Ahead", vn: "Về phía trước", cat: "Beginner" },
  { en: "Aid", vn: "Sự viện trợ, trợ giúp", cat: "Safety & Emergency" },
  { en: "Ailment", vn: "Bệnh tật nhẹ", cat: "Health & Mind" },
  { en: "Aim", vn: "Mục tiêu, nhắm vào", cat: "Beginner" },
  { en: "Airborne", vn: "Ở trên không, truyền qua không khí", cat: "Science & Space" },
  { en: "Aircraft", vn: "Máy bay, khí cầu", cat: "Travel & Tourism" },
  { en: "Airline", vn: "Hãng hàng không", cat: "Travel & Tourism" },
  { en: "Airport", vn: "Sân bay", cat: "Travel & Tourism" },
  { en: "Aisle", vn: "Lối đi giữa các hàng ghế", cat: "Travel & Tourism" },
  { en: "Alarm", vn: "Chuông báo động", cat: "Safety & Emergency" },
  { en: "Albeit", vn: "Mặc dù, dù rằng", cat: "Advanced Vocab" },
  { en: "Album", vn: "Tập bản đồ, album ảnh/nhạc", cat: "Arts & Culture" },
  { en: "Alchemy", vn: "Thuật luyện kim", cat: "Science & Space" },
  { en: "Alcohol", vn: "Rượu, cồn", cat: "Food & Dining" },
  { en: "Alert", vn: "Cảnh giác, thông báo", cat: "Safety & Emergency" },
  { en: "Algorithm", vn: "Thuật toán", cat: "Tech & AI" },
  { en: "Alias", vn: "Bí danh, tên giả", cat: "Law & Society" },
  { en: "Alien", vn: "Người ngoài hành tinh, xa lạ", cat: "Science & Space" },
  { en: "Alienate", vn: "Xa lánh, làm rạn nứt", cat: "Psychology" },
  { en: "Align", vn: "Căn chỉnh, sắp hàng", cat: "Work & Career" },
  { en: "Alignment", vn: "Sự căn chỉnh thẳng hàng", cat: "Tech & AI" },
  { en: "Alike", vn: "Giống nhau, tương tự", cat: "Intermediate" },
  { en: "Allegation", vn: "Sự cáo buộc chưa chứng minh", cat: "Law & Ethics" },
  { en: "Allege", vn: "Cáo buộc, cho rằng", cat: "Law & Ethics" },
  { en: "Allegiance", vn: "Lòng trung thành", cat: "Law & History" },
  { en: "Allegory", vn: "Truyện ngụ ngôn", cat: "Arts & Culture" },
  { en: "Allergy", vn: "Sự dị ứng", cat: "Health & Mind" },
  { en: "Alleviate", vn: "Làm xoa dịu, giảm bớt", cat: "TOEIC Mastery" },
  { en: "Alliance", vn: "Liên minh, sự hợp tác", cat: "Law & History" },
  { en: "Allocate", vn: "Phân bổ nguồn lực", cat: "TOEIC Mastery" },
  { en: "Allocation", vn: "Sự phân bổ", cat: "Finance" },
  { en: "Allotment", vn: "Phần được giao, thửa đất", cat: "Finance" },
  { en: "Allow", vn: "Cho phép", cat: "Beginner" },
  { en: "Allowance", vn: "Tiền tiêu vặt, hạn mức", cat: "Finance" },
  { en: "Alloy", vn: "Hợp kim", cat: "Science & Space" },
  { en: "Allure", vn: "Sự quyến rũ, sức hút", cat: "Arts & Culture" },
  { en: "Allusion", vn: "Sự ám chỉ, ẩn ý", cat: "Academic" },
  { en: "Ally", vn: "Đồng minh", cat: "Law & History" },
  { en: "Almanac", vn: "Niên giám", cat: "Academic" },
  { en: "Almighty", vn: "Toàn năng, tối cao", cat: "Philosophy" },
  { en: "Almost", vn: "Hầu như, gần như", cat: "Beginner" },
  { en: "Alone", vn: "Một mình, đơn độc", cat: "Beginner" },
  { en: "Along", vn: "Dọc theo", cat: "Beginner" },
  { en: "Aloof", vn: "Xa cách, lạnh nhạt", cat: "Psychology" },
  { en: "Alphabet", vn: "Bảng chữ cái", cat: "Education" },
  { en: "Already", vn: "Đã... rồi", cat: "Beginner" },
  { en: "Alter", vn: "Thay đổi, sửa đổi", cat: "Intermediate" },
  { en: "Alteration", vn: "Sự chỉnh sửa", cat: "TOEIC Mastery" },
  { en: "Alternate", vn: "Luân phiên, thay thế", cat: "Intermediate" },
  { en: "Alternative", vn: "Giải pháp thay thế", cat: "TOEIC Mastery" },
  { en: "Altitude", vn: "Độ cao so với mặt nước biển", cat: "Science & Space" },
  { en: "Altruism", vn: "Lòng vị tha", cat: "Philosophy" },
  { en: "Aluminium", vn: "Nhôm", cat: "Science & Space" },
  { en: "Always", vn: "Luôn luôn", cat: "Beginner" },
  { en: "Amass", vn: "Tích góp, chất đống", cat: "Finance" },
  { en: "Amateur", vn: "Nghiệp dư", cat: "Sports & Hobbies" },
  { en: "Amaze", vn: "Làm kinh ngạc", cat: "Beginner" },
  { en: "Amazing", vn: "Tuyệt vời, kinh ngạc", cat: "Beginner" },
  { en: "Ambassador", vn: "Đại sứ", cat: "Law & History" },
  { en: "Ambience", vn: "Bầu không khí quán/phòng", cat: "Arts & Culture" },
  { en: "Ambiguity", vn: "Sự mơ hồ, không rõ ràng", cat: "Advanced Vocab" },
  { en: "Ambiguous", vn: "Mơ hồ, nhập nhằng", cat: "Advanced Vocab" },
  { en: "Ambition", vn: "Hoài bão, khát vọng", cat: "Psychology" },
  { en: "Ambitious", vn: "Nhiều tham vọng", cat: "Psychology" },
  { en: "Ambivalence", vn: "Mối mâu thuẫn trong tư tưởng", cat: "Psychology" },
  { en: "Ambulance", vn: "Xe cấp cứu", cat: "Safety & Emergency" },
  { en: "Ambush", vn: "Cuộc phục kích", cat: "Law & History" },
  { en: "Ameliorate", vn: "Cải thiện, làm tốt hơn", cat: "Advanced Vocab" },
  { en: "Amenable", vn: "Dễ bị ảnh hưởng, tuân theo", cat: "Psychology" },
  { en: "Amend", vn: "Sửa đổi luật/văn bản", cat: "TOEIC Mastery" },
  { en: "Amendment", vn: "Sự sửa đổi luật", cat: "Law & Ethics" },
  { en: "Amenity", vn: "Tiện nghi tòa nhà/khách sạn", cat: "TOEIC Mastery" },
  { en: "Amiable", vn: "Thân thiện, hòa nhã", cat: "Psychology" },
  { en: "Amicable", vn: "Thân thiện, hòa giải", cat: "TOEIC Mastery" },
  { en: "Amid", vn: "Ở giữa, giữa lúc", cat: "Intermediate" },
  { en: "Ammunition", vn: "Đạn dược", cat: "Law & History" },
  { en: "Amnesty", vn: "Sự ân xá", cat: "Law & Ethics" },
  { en: "Amortization", vn: "Sự khấu hao tài sản", cat: "Finance" },
  { en: "Amount", vn: "Số lượng, tổng số", cat: "Beginner" },
  { en: "Amplify", vn: "Khuếch đại âm thanh/tín hiệu", cat: "Tech & AI" },
  { en: "Amplitude", vn: "Biên độ sóng", cat: "Science & Space" },
  { en: "Ample", vn: "Phong phú, dư dả", cat: "Advanced Vocab" },
  { en: "Amputate", vn: "Cắt bỏ bộ phận cơ thể", cat: "Health & Mind" },
  { en: "Amuse", vn: "Làm giải trí, làm vui", cat: "Beginner" },
  { en: "Amusement", vn: "Trò giải trí", cat: "Sports & Hobbies" },
  { en: "Anachronism", vn: "Sự sai lệch thời đại", cat: "Arts & Culture" },
  { en: "Anaesthesia", vn: "Sự gây mê", cat: "Health & Mind" },
  { en: "Anagram", vn: "Từ đảo chữ", cat: "Education" },
  { en: "Analogy", vn: "Sự tương tự, phép ví von", cat: "Academic" },
  { en: "Analyses", vn: "Các sự phân tích (số nhiều)", cat: "Academic" },
  { en: "Analysis", vn: "Sự phân tích", cat: "Academic" },
  { en: "Analyst", vn: "Chuyên viên phân tích", cat: "Work & Career" },
  { en: "Analytical", vn: "Thuộc về phân tích", cat: "Academic" },
  { en: "Analyze", vn: "Phân tích dữ liệu", cat: "TOEIC Mastery" },
  { en: "Anarchy", vn: "Tình trạng vô chính phủ", cat: "Law & History" },
  { en: "Anatomy", vn: "Giải phẫu học", cat: "Science & Space" },
  { en: "Ancestor", vn: "Tổ tiên", cat: "Family & Life" },
  { en: "Ancestry", vn: "Dòng họ, nguồn gốc", cat: "Family & Life" },
  { en: "Anchor", vn: "Mỏ neo, người dẫn chương trình", cat: "News & Media" },
  { en: "Ancient", vn: "Cổ xưa", cat: "History & World" },
  { en: "Ancillary", vn: "Phụ thuộc, bổ trợ", cat: "Work & Career" },
  { en: "Anecdote", vn: "Giai thoại, câu chuyện nhỏ", cat: "Arts & Culture" },
  { en: "Angel", vn: "Thiên thần", cat: "Philosophy" },
  { en: "Anger", vn: "Cơn tức giận", cat: "Psychology" },
  { en: "Angle", vn: "Góc độ", cat: "Education" },
  { en: "Angry", vn: "Tức giận", cat: "Beginner" },
  { en: "Anguish", vn: "Sự đau khổ dằn xé", cat: "Psychology" },
  { en: "Angular", vn: "Góc cạnh", cat: "Arts & Culture" },
  { en: "Animal", vn: "Động vật", cat: "Pets & Animals" },
  { en: "Animate", vn: "Làm nhộn nhịp, tạo hoạt họa", cat: "Arts & Culture" },
  { en: "Animation", vn: "Phim hoạt hình, sự hăng hái", cat: "Arts & Culture" },
  { en: "Animosity", vn: "Lòng thù hận", cat: "Psychology" },
  { en: "Ankle", vn: "Mắt cá chân", cat: "Health & Mind" },
  { en: "Annex", vn: "Phụ lục, sáp nhập lãnh thổ", cat: "Law & History" },
  { en: "Annihilate", vn: "Têu diệt hoàn toàn", cat: "Law & History" },
  { en: "Anniversary", vn: "Ngày kỷ niệm", cat: "Family & Life" },
  { en: "Annotate", vn: "Chú giải, chú thích", cat: "Academic" },
  { en: "Annotation", vn: "Sự ghi chú", cat: "Academic" },
  { en: "Announce", vn: "Thông báo", cat: "Intermediate" },
  { en: "Announcement", vn: "Lời thông báo", cat: "TOEIC Mastery" },
  { en: "Announcer", vn: "Người phát thanh", cat: "News & Media" },
  { en: "Annoy", vn: "Làm bực mình", cat: "Beginner" },
  { en: "Annoyance", vn: "Sự khó chịu", cat: "Psychology" },
  { en: "Annual", vn: "Hàng năm", cat: "TOEIC Mastery" },
  { en: "Annuity", vn: "Tiền trợ cấp hàng năm", cat: "Finance" },
  { en: "Annulment", vn: "Sự bãi bỏ hợp đồng/hôn nhân", cat: "Law & Ethics" },
  { en: "Anode", vn: "Cực dương", cat: "Science & Space" },
  { en: "Anomalous", vn: "Bất thường, dị thường", cat: "Advanced Vocab" },
  { en: "Anomaly", vn: "Sự dị thường", cat: "Advanced Vocab" },
  { en: "Anonymous", vn: "Ẩn danh, không tên", cat: "Tech & AI" },
  { en: "Answer", vn: "Câu trả lời, đáp lại", cat: "Beginner" },
  { en: "Antagonism", vn: "Sự sự đối đầu", cat: "Psychology" },
  { en: "Antagonist", vn: "Nhân vật phản diện, đối thủ", cat: "Arts & Culture" },
  { en: "Antarctic", vn: "Thuộc Nam Cực", cat: "Environment" },
  { en: "Antecedent", vn: "Tiền đề, lai lịch", cat: "Academic" },
  { en: "Antelope", vn: "Linh dương", cat: "Pets & Animals" },
  { en: "Antenna", vn: "Ăng-ten, râu côn trùng", cat: "Tech & AI" },
  { en: "Anthem", vn: "Bài quốc ca/thánh ca", cat: "Arts & Culture" },
  { en: "Anthology", vn: "Tuyển tập văn học", cat: "Arts & Culture" },
  { en: "Anthropology", vn: "Nhân học", cat: "Science & Space" },
  { en: "Antibiotic", vn: "Thuốc kháng sinh", cat: "Health & Mind" },
  { en: "Antibody", vn: "Kháng thể", cat: "Health & Mind" },
  { en: "Anticipate", vn: "Dự đoán, mong chờ", cat: "TOEIC Mastery" },
  { en: "Anticipation", vn: "Sự dự đoán, kỳ vọng", cat: "Psychology" },
  { en: "Anticlimax", vn: "Sự giảm hưng phấn đột ngột", cat: "Arts & Culture" },
  { en: "Antidote", vn: "Thuốc giải độc", cat: "Health & Mind" },
  { en: "Antipathetic", vn: "Ác cảm, không thích", cat: "Psychology" },
  { en: "Antipathy", vn: "Sự ác cảm", cat: "Psychology" },
  { en: "Antiquated", vn: "Lỗi thời, cổ xơ", cat: "Advanced Vocab" },
  { en: "Antique", vn: "Đồ cổ", cat: "Arts & Culture" },
  { en: "Antiquity", vn: "Thời cổ đại", cat: "History & World" },
  { en: "Antiseptic", vn: "Chất sát trùng", cat: "Health & Mind" },
  { en: "Antisocial", vn: "Chống đối xã hội", cat: "Psychology" },
  { en: "Antithesis", vn: "Sự đối lập hoàn toàn", cat: "Academic" },
  { en: "Antonym", vn: "Từ trái nghĩa", cat: "Education" },
  { en: "Anxiety", vn: "Sự lo âu, băn khoăn", cat: "Psychology" },
  { en: "Anxious", vn: "Lo âu, sốt sắng", cat: "Intermediate" },
  { en: "Anybody", vn: "Bất kỳ ai", cat: "Beginner" },
  { en: "Anymore", vn: "Nữa (không còn... nữa)", cat: "Beginner" },
  { en: "Anyone", vn: "Bất kỳ ai", cat: "Beginner" },
  { en: "Anything", vn: "Bất kỳ điều gì", cat: "Beginner" },
  { en: "Anyway", vn: "Dù sao đi nữa", cat: "Beginner" },
  { en: "Anywhere", vn: "Bất kỳ đâu", cat: "Beginner" },
  { en: "Apartment", vn: "Căn hộ", cat: "Home & Living" },
  { en: "Apathy", vn: "Sự thờ ơ, vô cảm", cat: "Psychology" },
  { en: "Apex", vn: "Đỉnh cao, điểm cao nhất", cat: "Advanced Vocab" },
  { en: "Aphorism", vn: "Thành ngữ, ngạn ngữ", cat: "Arts & Culture" },
  { en: "Apologetic", vn: "Xin lỗi, hối hận", cat: "Psychology" },
  { en: "Apologize", vn: "Xin lỗi", cat: "Beginner" },
  { en: "Apology", vn: "Lời xin lỗi", cat: "Intermediate" },
  { en: "Appalling", vn: "Kinh hãi, dở tệ", cat: "Advanced Vocab" },
  { en: "Apparatus", vn: "Bộ máy, thiết bị thử nghiệm", cat: "Science & Space" },
  { en: "Apparel", vn: "Trang phục, quần áo", cat: "Shopping & Fashion" },
  { en: "Apparent", vn: "Rõ ràng, hiển nhiên", cat: "TOEIC Mastery" },
  { en: "Apparently", vn: "Hình như, có vẻ như", cat: "Intermediate" },
  { en: "Appeal", vn: "Sức hấp dẫn, sự chống án", cat: "Law & Ethics" },
  { en: "Appealing", vn: "Hấp dẫn, lôi cuốn", cat: "Arts & Culture" },
  { en: "Appear", vn: "Xuất hiện", cat: "Beginner" },
  { en: "Appearance", vn: "Vẻ bề ngoài, sự xuất hiện", cat: "Intermediate" },
  { en: "Appease", vn: "Xoa dịu, nhượng bộ", cat: "Law & History" },
  { en: "Append", vn: "Đính kèm vào cuối", cat: "Tech & AI" },
  { en: "Appendix", vn: "Phụ lục sách, ruột thừa", cat: "Academic" },
  { en: "Appetite", vn: "Sự thèm ăn", cat: "Food & Dining" },
  { en: "Appetizer", vn: "Món khai vị", cat: "Food & Dining" },
  { en: "Applaud", vn: "Vỗ tay tán thưởng", cat: "Arts & Culture" },
  { en: "Applause", vn: "Tiếng vỗ tay", cat: "Arts & Culture" },
  { en: "Appliance", vn: "Thiết bị gia dụng", cat: "Home & Living" },
  { en: "Applicable", vn: "Có thể áp dụng", cat: "TOEIC Mastery" },
  { en: "Applicant", vn: "Ứng viên xin việc", cat: "Work & Career" },
  { en: "Application", vn: "Đơn xin việc, ứng dụng", cat: "Work & Career" },
  { en: "Applied", vn: "Được ứng dụng", cat: "Academic" },
  { en: "Apply", vn: "Nộp đơn, áp dụng", cat: "Beginner" },
  { en: "Appoint", vn: "Bổ nhiệm, hẹn giờ", cat: "Work & Career" },
  { en: "Appointment", vn: "Cuộc hẹn, sự bổ nhiệm", cat: "TOEIC Mastery" },
  { en: "Appraisal", vn: "Sự định giá, đánh giá nhân sự", cat: "TOEIC Mastery" },
  { en: "Appraise", vn: "Đánh giá giá trị", cat: "Finance" },
  { en: "Appreciable", vn: "Đáng kể, thấy rõ", cat: "Advanced Vocab" },
  { en: "Appreciate", vn: "Trân trọng, tăng giá trị", cat: "Intermediate" },
  { en: "Appreciation", vn: "Sự biết ơn, tăng giá", cat: "Finance" },
  { en: "Apprehend", vn: "Bắt giữ, thấu hiểu", cat: "Law & Ethics" },
  { en: "Apprehension", vn: "Sự e sợ, sự bắt giữ", cat: "Psychology" },
  { en: "Apprentice", vn: "Người học việc", cat: "Work & Career" },
  { en: "Approach", vn: "Tiếp cận, phương pháp", cat: "TOEIC Mastery" },
  { en: "Appropriate", vn: "Thích hợp, chiếm dụng", cat: "TOEIC Mastery" },
  { en: "Appropriation", vn: "Sự chiếm đoạt, sự cấp vốn", cat: "Finance" },
  { en: "Approval", vn: "Sự phê duyệt, tán thành", cat: "TOEIC Mastery" },
  { en: "Approve", vn: "Phê duyệt, tán thành", cat: "Intermediate" },
  { en: "Approximate", vn: "Xấp xỉ, ước chừng", cat: "TOEIC Mastery" },
  { en: "Approximately", vn: "Khoảng chừng", cat: "Intermediate" },
  { en: "Apron", vn: "Tạp dề", cat: "Home & Living" },
  { en: "Aptitude", vn: "Năng khiếu bẩm sinh", cat: "Education" },
  { en: "Aquarium", vn: "Thủy cung, bể cá", cat: "Travel & Tourism" },
  { en: "Aquatic", vn: "Dưới nước", cat: "Pets & Animals" },
  { en: "Aqueduct", vn: "Cầu dẫn nước cổ", cat: "History & World" },
  { en: "Arbitrary", vn: "Tùy tiện, độc đoán", cat: "Advanced Vocab" },
  { en: "Arbitrate", vn: "Phân giải trọng tài", cat: "Law & Ethics" },
  { en: "Arbitration", vn: "Sự trọng tài phân giải", cat: "Law & Ethics" },
  { en: "Arbitrator", vn: "Trọng tài hòa giải", cat: "Work & Career" },
  { en: "Arcade", vn: "Khu vui chơi giải trí", cat: "Sports & Hobbies" },
  { en: "Archaeology", vn: "Khảo cổ học", cat: "History & World" },
  { en: "Archaic", vn: "Cổ xưa, lỗi thời", cat: "Advanced Vocab" },
  { en: "Architect", vn: "Kiến trúc sư", cat: "Work & Career" },
  { en: "Architectural", vn: "Thuộc kiến trúc", cat: "Arts & Culture" },
  { en: "Architecture", vn: "Kiến trúc", cat: "Arts & Culture" },
  { en: "Archive", vn: "Kho lưu trữ tài liệu", cat: "Tech & AI" },
  { en: "Ardent", vn: "Nhiệt thành, hăng hái", cat: "Psychology" },
  { en: "Arduous", vn: "Gian khổ, gay go", cat: "Advanced Vocab" },
  { en: "Area", vn: "Khu vực, diện tích", cat: "Beginner" },
  { en: "Arena", vn: "Đấu trường, sàn đấu", cat: "Sports & Hobbies" },
  { en: "Arguable", vn: "Có thể tranh cãi", cat: "Academic" },
  { en: "Argue", vn: "Tranh luận, cãi nhau", cat: "Beginner" },
  { en: "Argument", vn: "Cuộc tranh luận, luận điểm", cat: "Intermediate" },
  { en: "Arid", vn: "Khô hạn, cằn cỗi", cat: "Environment" },
  { en: "Arise", vn: "Nảy sinh, phát sinh", cat: "TOEIC Mastery" },
  { en: "Aristocracy", vn: "Tầng lớp quý tộc", cat: "History & World" },
  { en: "Arithmetic", vn: "Số học", cat: "Education" },
  { en: "Armor", vn: "Áo giáp", cat: "History & World" },
  { en: "Armpit", vn: "Nách", cat: "Health & Mind" },
  { en: "Aroma", vn: "Hương thơm thức ăn/cà phê", cat: "Food & Dining" },
  { en: "Aromatic", vn: "Thơm tho", cat: "Food & Dining" },
  { en: "Arouse", vn: "Kích thích, khơi dậy", cat: "Psychology" },
  { en: "Arraign", vn: "Thắt tố, buộc tội", cat: "Law & Ethics" },
  { en: "Arrange", vn: "Sắp xếp, thu xếp", cat: "Beginner" },
  { en: "Arrangement", vn: "Sự sắp xếp, sự thỏa thuận", cat: "Intermediate" },
  { en: "Array", vn: "Mảng, một dãy phong phú", cat: "Tech & AI" },
  { en: "Arrear", vn: "Khoản nợ quá hạn", cat: "Finance" },
  { en: "Arrest", vn: "Bắt giữ", cat: "Law & Ethics" },
  { en: "Arrival", vn: "Sự đến nơi", cat: "Travel & Tourism" },
  { en: "Arrive", vn: "Đến nơi", cat: "Beginner" },
  { en: "Arrogance", vn: "Sự ngông cuồng, kiêu ngạo", cat: "Psychology" },
  { en: "Arrogant", vn: "Kiêu ngạo, ngạo mạn", cat: "Psychology" },
  { en: "Arrow", vn: "Mũi tên", cat: "Sports & Hobbies" },
  { en: "Arsenal", vn: "Kho vũ khí", cat: "Law & History" },
  { en: "Arson", vn: "Tội cố ý phóng hỏa", cat: "Law & Ethics" },
  { en: "Art", vn: "Nghệ thuật", cat: "Beginner" },
  { en: "Artery", vn: "Động mạch", cat: "Health & Mind" },
  { en: "Artful", vn: "Xảo quyệt, tinh xảo", cat: "Psychology" },
  { en: "Article", vn: "Bài báo, điều khoản", cat: "News & Media" },
  { en: "Articulate", vn: "Diễn đạt rõ ràng", cat: "Advanced Vocab" },
  { en: "Artifact", vn: "Cổ vật", cat: "History & World" },
  { en: "Artificial", vn: "Nhân tạo", cat: "Tech & AI" },
  { en: "Artillery", vn: "Pháo binh", cat: "Law & History" },
  { en: "Artisan", vn: "Thợ thủ công", cat: "Arts & Culture" },
  { en: "Artist", vn: "Họa sĩ, nghệ sĩ", cat: "Beginner" },
  { en: "Artistic", vn: "Mang tính nghệ thuật", cat: "Arts & Culture" },
  { en: "Artistry", vn: "Tay nghề nghệ thuật", cat: "Arts & Culture" },
  { en: "Ascend", vn: "Đi lên, thăng tiến", cat: "Advanced Vocab" },
  { en: "Ascent", vn: "Sự trèo lên, sự phát triển", cat: "Advanced Vocab" },
  { en: "Ascertain", vn: "Xác minh làm rõ", cat: "TOEIC Mastery" },
  { en: "Ascetic", vn: "Khổ hạnh", cat: "Philosophy" },
  { en: "Ascribe", vn: "Gán cho, quy cho", cat: "Academic" },
  { en: "Ashamed", vn: "Xấu hổ, ngượng ngùng", cat: "Beginner" },
  { en: "Ashes", vn: "Tro tàn", cat: "Nature & Elements" },
  { en: "Ashore", vn: "Lên bờ", cat: "Travel & Tourism" },
  { en: "Aside", vn: "Sang một bên", cat: "Beginner" },
  { en: "Aspect", vn: "Khía cạnh", cat: "Intermediate" },
  { en: "Aspiration", vn: "Khát vọng", cat: "Psychology" },
  { en: "Aspire", vn: "Khao khát, hướng tới", cat: "Psychology" },
  { en: "Aspirin", vn: "Thuốc giảm đau aspirin", cat: "Health & Mind" },
  { en: "Assailant", vn: "Kẻ tấn công", cat: "Law & Ethics" },
  { en: "Assassin", vn: "Sát thủ", cat: "Law & History" },
  { en: "Assassinate", vn: "Ám sát", cat: "Law & History" },
  { en: "Assault", vn: "Sự hành hung, cuộc tấn công", cat: "Law & Ethics" },
  { en: "Assemble", vn: "Lắp ráp, tập hợp", cat: "TOEIC Mastery" },
  { en: "Assembly", vn: "Hội đồng, sự lắp ráp", cat: "Work & Career" },
  { en: "Assert", vn: "Khẳng định, đòi quyền lợi", cat: "TOEIC Mastery" },
  { en: "Assertion", vn: "Sự khẳng định", cat: "Academic" },
  { en: "Assertive", vn: "Quả quyết, quyết đoán", cat: "Psychology" },
  { en: "Assess", vn: "Đánh giá, ước lượng", cat: "TOEIC Mastery" },
  { en: "Assessment", vn: "Sự đánh giá", cat: "TOEIC Mastery" },
  { en: "Asset", vn: "Tài sản, lợi thế", cat: "Finance" },
  { en: "Assign", vn: "Phân công nhiệm vụ", cat: "Work & Career" },
  { en: "Assignment", vn: "Nhiệm vụ được giao, bài tập", cat: "Education" },
  { en: "Annihilated", vn: "Bị tiêu diệt hoàn toàn", cat: "Law & History" },
  { en: "Assimilate", vn: "Đồng hóa, tiếp thu", cat: "Academic" },
  { en: "Assist", vn: "Hỗ trợ, giúp đỡ", cat: "Beginner" },
  { en: "Assistance", vn: "Sự trợ giúp", cat: "TOEIC Mastery" },
  { en: "Assistant", vn: "Trợ lý", cat: "Work & Career" },
  { en: "Associate", vn: "Liên kết, đồng nghiệp", cat: "TOEIC Mastery" },
  { en: "Association", vn: "Hiệp hội, sự liên tưởng", cat: "Work & Career" },
  { en: "Assortment", vn: "Sự phối hợp đủ loại", cat: "Shopping & Fashion" },
  { en: "Assume", vn: "Giả định, đảm nhận", cat: "TOEIC Mastery" },
  { en: "Assumption", vn: "Sự giả định", cat: "Academic" },
  { en: "Assurance", vn: "Sự bảo đảm, sự tự tin", cat: "TOEIC Mastery" },
  { en: "Assure", vn: "Cam đoan, đảm bảo", cat: "TOEIC Mastery" },
  { en: "Asteroid", vn: "Tiểu hành tinh", cat: "Science & Space" },
  { en: "Asthma", vn: "Bệnh hen suyễn", cat: "Health & Mind" },
  { en: "Astonish", vn: "Làm kinh ngạc", cat: "Intermediate" },
  { en: "Astonishing", vn: "Đáng kinh ngạc", cat: "Intermediate" },
  { en: "Astonishment", vn: "Sự ngạc nhiên lớn", cat: "Psychology" },
  { en: "Astray", vn: "Lạc đường, chệch hướng", cat: "Travel & Tourism" },
  { en: "Astronomy", vn: "Thiên văn học", cat: "Science & Space" },
  { en: "Astute", vn: "Sắc sảo, tinh khôn", cat: "Advanced Vocab" },
  { en: "Asylum", vn: "Sự tị nạn chính trị", cat: "Law & History" },
  { en: "Asymmetric", vn: "Bất đối xứng", cat: "Arts & Culture" },
  { en: "Athlete", vn: "Vận động viên", cat: "Sports & Hobbies" },
  { en: "Athletic", vn: "Khỏe khoắn, thể thao", cat: "Sports & Hobbies" },
  { en: "Athletics", vn: "Môn điền kinh", cat: "Sports & Hobbies" },
  { en: "Atlas", vn: "Tập bản đồ", cat: "Education" },
  { en: "Atmosphere", vn: "Bầu khí quyển, không khí", cat: "Environment" },
  { en: "Atmospheric", vn: "Thuộc khí quyển", cat: "Science & Space" },
  { en: "Atom", vn: "Nguyên tử", cat: "Science & Space" },
  { en: "Atomic", vn: "Thuộc nguyên tử", cat: "Science & Space" },
  { en: "Atrocity", vn: "Tội ác tàn bạo", cat: "Law & History" },
  { en: "Attach", vn: "Đính kèm, dán vào", cat: "TOEIC Mastery" },
  { en: "Attachment", vn: "Tệp đính kèm, sự gắn bó", cat: "Tech & AI" },
  { en: "Attack", vn: "Tấn công", cat: "Beginner" },
  { en: "Attain", vn: "Đạt được", cat: "TOEIC Mastery" },
  { en: "Attainable", vn: "Có thể đạt được", cat: "Work & Career" },
  { en: "Attempt", vn: "Nỗ lực, thử sức", cat: "Intermediate" },
  { en: "Attend", vn: "Tham dự, chú ý", cat: "Beginner" },
  { en: "Attendance", vn: "Sự tham dự, điểm danh", cat: "Education" },
  { en: "Attendant", vn: "Người phục vụ", cat: "Work & Career" },
  { en: "Attention", vn: "Sự chú ý", cat: "Beginner" },
  { en: "Attentive", vn: "Chăm chú, ân cần", cat: "Psychology" },
  { en: "Attest", vn: "Chứng nhận, làm chứng", cat: "Law & Ethics" },
  { en: "Attic", vn: "Gác xép", cat: "Home & Living" },
  { en: "Attitude", vn: "Thái độ", cat: "Psychology" },
  { en: "Attorney", vn: "Luật sư", cat: "Law & Ethics" },
  { en: "Attract", vn: "Thu hút, lôi cuốn", cat: "Beginner" },
  { en: "Attraction", vn: "Điểm tham quan, sức hút", cat: "Travel & Tourism" },
  { en: "Attractive", vn: "Hấp dẫn, đẹp đẽ", cat: "Beginner" },
  { en: "Attribute", vn: "Thuộc tính, quy cho", cat: "TOEIC Mastery" },
  { en: "Auction", vn: "Cuộc đấu giá", cat: "Finance" },
  { en: "Audacious", vn: "Táo bạo, liều lĩnh", cat: "Advanced Vocab" },
  { en: "Audacity", vn: "Sự táo bạo", cat: "Advanced Vocab" },
  { en: "Audible", vn: "Có thể nghe thấy", cat: "Arts & Culture" },
  { en: "Audience", vn: "Khán giả", cat: "Arts & Culture" },
  { en: "Audio", vn: "Âm thanh", cat: "Tech & AI" },
  { en: "Audit", vn: "Sự kiểm toán", cat: "TOEIC Mastery" },
  { en: "Audition", vn: "Buổi thử giọng/thử vai", cat: "Arts & Culture" },
  { en: "Auditorium", vn: "Hội trường lớn", cat: "Education" },
  { en: "Augment", vn: "Tăng cường, gia tăng", cat: "Advanced Vocab" },
  { en: "Augmented", vn: "Được tăng cường (AR)", cat: "Tech & AI" },
  { en: "August", vn: "Tháng 8, uy nghi", cat: "Beginner" },
  { en: "Aunt", vn: "Cô, dì, bác gái", cat: "Beginner" },
  { en: "Authentic", vn: "Đích thực, chính hảng", cat: "TOEIC Mastery" },
  { en: "Authenticity", vn: "Tính xác thực", cat: "TOEIC Mastery" },
  { en: "Author", vn: "Tác giả", cat: "Arts & Culture" },
  { en: "Authoritative", vn: "Có thẩm quyền, hống hách", cat: "Work & Career" },
  { en: "Authority", vn: "Cơ quan thẩm quyền, uy tín", cat: "Law & Ethics" },
  { en: "Authorization", vn: "Sự cấp phép", cat: "TOEIC Mastery" },
  { en: "Authorize", vn: "Ủy quyền, cho phép", cat: "TOEIC Mastery" },
  { en: "Autobiography", vn: "Tự truyện", cat: "Arts & Culture" },
  { en: "Automate", vn: "Tự động hóa", cat: "Tech & AI" },
  { en: "Automatic", vn: "Tự động", cat: "Tech & AI" },
  { en: "Autonomous", vn: "Tự chủ, độc lập", cat: "Tech & AI" },
  { en: "Autonomy", vn: "Quyền tự trị, tính tự lập", cat: "Law & History" },
  { en: "Autopsy", vn: "Sự khám nghiệm tử thi", cat: "Health & Mind" },
  { en: "Autumn", vn: "Mùa thu", cat: "Beginner" },
  { en: "Auxiliary", vn: "Bổ trợ, trợ lực", cat: "Academic" },
  { en: "Available", vn: "Có sẵn, rảnh rỗi", cat: "Beginner" },
  { en: "Avalanche", vn: "Tuyết lở", cat: "Safety & Emergency" },
  { en: "Avenue", vn: "Đại lộ", cat: "Travel & Tourism" },
  { en: "Average", vn: "Trung bình", cat: "Beginner" },
  { en: "Aversion", vn: "Sự ác cảm, ghét", cat: "Psychology" },
  { en: "Avert", vn: "Năn ngừa, ngoảnh đi", cat: "Safety & Emergency" },
  { en: "Aviation", vn: "Ngành hàng không", cat: "Travel & Tourism" },
  { en: "Avid", vn: "Khao khát, say mê", cat: "Psychology" },
  { en: "Avoid", vn: "Tránh né", cat: "Beginner" },
  { en: "Avoidance", vn: "Sự tránh né", cat: "Psychology" },
  { en: "Await", vn: "Chờ đợi", cat: "Intermediate" },
  { en: "Awake", vn: "Tỉnh giấc", cat: "Beginner" },
  { en: "Award", vn: "Giải thưởng", cat: "Beginner" },
  { en: "Aware", vn: "Nhận biết, nhận thức", cat: "Intermediate" },
  { en: "Awareness", vn: "Nhận thức", cat: "Intermediate" },
  { en: "Awesome", vn: "Tuyệt vời", cat: "Beginner" },
  { en: "Awful", vn: "Tồi tệ", cat: "Beginner" },
  { en: "Awkward", vn: "Gượng gạo, ngượng ngùng", cat: "Psychology" },
  { en: "Awkwardly", vn: "Một cách vụng về", cat: "Psychology" },
  { en: "Axis", vn: "Trục xoay", cat: "Science & Space" }
];

console.log("Loaded base words count:", baseWords.length);
