import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const gamesDataPath = path.join(__dirname, '../src/data/games-data.js');

// View current games-data.js content
let content = fs.readFileSync(gamesDataPath, 'utf8');

// We will append rich 3000+ item generators to games-data.js so each game reaches 3000+ items
const expansionCode = `

// ==========================================================================
// MASSIVE 3000+ TRAINING POOL GENERATORS FOR EACH MINI-GAME
// ==========================================================================

// Core 3000 High-Frequency Training Words Pool
export const COMMON_3000_VOCAB_BANK = [
  // A
  { en: 'Ability', vn: 'Khả năng, năng lực', category: 'Education' },
  { en: 'Abolish', vn: 'Bãi bỏ, hủy bỏ', category: 'Law & Ethics' },
  { en: 'Abundant', vn: 'Dồi dào, phong phú', category: 'Environment' },
  { en: 'Academic', vn: 'Thuộc học thuật, nghiên cứu', category: 'Education' },
  { en: 'Accelerate', vn: 'Gia tốc, làm nhanh hơn', category: 'Tech & AI' },
  { en: 'Accent', vn: 'Giọng điệu, trọng âm', category: 'Public Speaking' },
  { en: 'Acceptable', vn: 'Có thể chấp nhận được', category: 'Work & Career' },
  { en: 'Accessible', vn: 'Dễ dàng tiếp cận, có sẵn', category: 'Tech & AI' },
  { en: 'Accommodate', vn: 'Cung cấp chỗ ở, đáp ứng', category: 'Travel & Tourism' },
  { en: 'Accommodation', vn: 'Chỗ ở, khách sạn lưu trú', category: 'Travel & Tourism' },
  { en: 'Accomplish', vn: 'Hoàn thành xuất sắc, đạt được', category: 'Work & Career' },
  { en: 'Accountant', vn: 'Nhân viên kế toán', category: 'Work & Career' },
  { en: 'Accumulate', vn: 'Tích lũy, dồn tích', category: 'Finance' },
  { en: 'Accuracy', vn: 'Sự chính xác tuyệt đối', category: 'Science & Space' },
  { en: 'Achievement', vn: 'Thành tựu, kết quả lớn', category: 'Future & Goals' },
  { en: 'Acknowledge', vn: 'Thừa nhận, công nhận', category: 'Public Speaking' },
  { en: 'Acquisition', vn: 'Sự thâu tóm, thu mua doanh nghiệp', category: 'Finance' },
  { en: 'Adaptability', vn: 'Khả năng thích ứng linh hoạt', category: 'Psychology' },
  { en: 'Additional', vn: 'Bổ sung, thêm vào', category: 'Work & Career' },
  { en: 'Adequate', vn: 'Đầy đủ, thỏa đáng', category: 'Health & Mind' },
  { en: 'Administration', vn: 'Ban quản trị, sự hành chính', category: 'Work & Career' },
  { en: 'Admirable', vn: 'Đáng khâm phục, ngưỡng mộ', category: 'Psychology' },
  { en: 'Admission', vn: 'Vé vào cửa, sự nhận học', category: 'Education' },
  { en: 'Adoptive', vn: 'Thuộc về nhận làm con nuôi', category: 'Family & Life' },
  { en: 'Advantageous', vn: 'Có lợi, thuận lợi', category: 'Work & Career' },
  { en: 'Adventure', vn: 'Chuyến phiêu lưu khám phá', category: 'Travel & Tourism' },
  { en: 'Advertisement', vn: 'Bài quảng cáo, sự tiếp thị', category: 'Shopping & Style' },
  { en: 'Advocacy', vn: 'Sự bào chữa, vận động chính sách', category: 'Law & Ethics' },
  { en: 'Aesthetic', vn: 'Tính thẩm mỹ, nghệ thuật', category: 'Arts & Culture' },
  { en: 'Affordable', vn: 'Giá cả hợp lý, vừa túi tiền', category: 'Shopping & Style' },
  { en: 'Aggressive', vn: 'Hung hăng, quyết đoán bứt phá', category: 'Psychology' },
  { en: 'Agility', vn: 'Sự nhanh nhẹn, linh hoạt', category: 'Tech & AI' },
  { en: 'Agreement', vn: 'Hợp đồng, sự thỏa thuận', category: 'Law & Ethics' },
  { en: 'Agriculture', vn: 'Nông nghiệp, canh tác', category: 'Environment' },
  { en: 'Aircraft', vn: 'Máy bay, phi cơ', category: 'Travel & Tourism' },
  { en: 'Algorithm', vn: 'Thuật toán máy tính', category: 'Tech & AI' },
  { en: 'Alignment', vn: 'Sự căn chỉnh, liên minh', category: 'Tech & AI' },
  { en: 'Alleviate', vn: 'Xoa dịu, giảm nhẹ nỗi đau', category: 'Health & Mind' },
  { en: 'Alliance', vn: 'Sự liên minh quốc tế', category: 'News & Society' },
  { en: 'Allocation', vn: 'Sự phân bổ ngân sách', category: 'Finance' },
  { en: 'Allowance', vn: 'Tiền trợ cấp, phụ cấp', category: 'Finance' },
  { en: 'Alteration', vn: 'Sự chỉnh sửa, thay đổi', category: 'Shopping & Style' },
  { en: 'Alternative', vn: 'Giải pháp thay thế', category: 'Future & Goals' },
  { en: 'Altitude', vn: 'Độ cao so với mực nước biển', category: 'Science & Space' },
  { en: 'Altruism', vn: 'Lòng vị tha cao đẹp', category: 'Philosophy' },
  { en: 'Ambassador', vn: 'Đại sứ ngoại giao', category: 'News & Society' },
  { en: 'Ambiguity', vn: 'Sự mơ hồ, không rõ ràng', category: 'Philosophy' },
  { en: 'Ambiguous', vn: 'Mơ hồ, nhập nhằng', category: 'Philosophy' },
  { en: 'Ambitious', vn: 'Có tham vọng, hoài bão', category: 'Future & Goals' },
  { en: 'Ambulance', vn: 'Xe cấp cứu cứu thương', category: 'Safety & Emergency' },
  { en: 'Amendment', vn: 'Tu chính án, sự sửa đổi luật', category: 'Law & Ethics' },
  { en: 'Amenity', vn: 'Tiện nghi khách sạn / căn hộ', category: 'Travel & Tourism' },
  { en: 'Analogy', vn: 'Phép ví von, sự tương tự', category: 'Public Speaking' },
  { en: 'Analytical', vn: 'Có tư duy phân tích', category: 'Education' },
  { en: 'Anarchy', vn: 'Tình trạng vô chính phủ', category: 'History & World' },
  { en: 'Anatomy', vn: 'Giải phẫu học cơ thể', category: 'Health & Mind' },
  { en: 'Ancestry', vn: 'Dòng họ, nguồn gốc tổ tiên', category: 'History & World' },
  { en: 'Anecdote', vn: 'Giai thoại, chuyện phiếm thú vị', category: 'Public Speaking' },
  { en: 'Animation', vn: 'Hiệu ứng hoạt hình, động', category: 'Arts & Culture' },
  { en: 'Anniversary', vn: 'Ngày kỷ niệm hàng năm', category: 'Festivals' },
  { en: 'Announcement', vn: 'Bản thông báo chính thức', category: 'Work & Career' },
  { en: 'Annual', vn: 'Diễn ra hàng năm', category: 'Work & Career' },
  { en: 'Anonymous', vn: 'Ẩn danh, không tên', category: 'Tech & AI' },
  { en: 'Anticipation', vn: 'Sự mong chờ, dự đoán', category: 'Future & Goals' },
  { en: 'Anxiety', vn: 'Sự lo âu, trăn trở', category: 'Psychology' },
  { en: 'Apologetic', vn: 'Cảm thấy có lỗi, hối hận', category: 'Family & Life' },
  { en: 'Apparatus', vn: 'Thiết bị, bộ máy máy móc', category: 'Science & Space' },
  { en: 'Apparel', vn: 'Trang phục, quần áo thời trang', category: 'Shopping & Style' },
  { en: 'Apparent', vn: 'Rõ ràng, hiển nhiên', category: 'Science & Space' },
  { en: 'Appealing', vn: 'Lôi cuốn, hấp dẫn', category: 'Shopping & Style' },
  { en: 'Appearance', vn: 'Ngoại hình, diện mạo', category: 'Shopping & Style' },
  { en: 'Appetite', vn: 'Sự thèm ăn, khẩu vị ngon', category: 'Food & Dining' },
  { en: 'Applaud', vn: 'Vỗ tay tán thưởng nồng nhiệt', category: 'Arts & Culture' },
  { en: 'Applause', vn: 'Tiếng vỗ tay vang dội', category: 'Arts & Culture' },
  { en: 'Appliance', vn: 'Thiết bị điện gia dụng', category: 'Home & Living' },
  { en: 'Applicant', vn: 'Ứng viên nộp đơn xin việc', category: 'Work & Career' },
  { en: 'Application', vn: 'Ứng dụng di động, đơn từ', category: 'Tech & AI' },
  { en: 'Appointment', vn: 'Cuộc hẹn làm việc, bổ nhiệm', category: 'Work & Career' },
  { en: 'Appraisal', vn: 'Sự thẩm định, đánh giá giá trị', category: 'Work & Career' },
  { en: 'Appreciate', vn: 'Trân trọng, biết ơn', category: 'Family & Life' },
  { en: 'Appreciation', vn: 'Sự trân trọng, đánh giá cao', category: 'Family & Life' },
  { en: 'Apprehension', vn: 'Mối e ngại, sự lo sợ', category: 'Psychology' },
  { en: 'Apprentice', vn: 'Người học việc, tập sự', category: 'Work & Career' },
  { en: 'Appropriate', vn: 'Phù hợp, thích đáng', category: 'Education' },
  { en: 'Approval', vn: 'Sự phê duyệt, chấp thuận', cat: 'Work & Career' },
  { en: 'Approximate', vn: 'Xấp xỉ, ước chừng', category: 'Finance' },
  { en: 'Aptitude', vn: 'Năng khiếu, tố chất tự nhiên', category: 'Education' },
  { en: 'Aquarium', vn: 'Thủy cung, bể cá cảnh', category: 'Pets & Animals' },
  { en: 'Arbitrary', vn: 'Tùy hứng, tùy tiện', category: 'Philosophy' },
  { en: 'Arbitration', vn: 'Sự trọng tài phân xử', category: 'Law & Ethics' },
  { en: 'Archaeology', vn: 'Khảo cổ học nghiên cứu cổ đại', category: 'History & World' },
  { en: 'Architectural', vn: 'Thuộc về kiến trúc', category: 'Home & Living' },
  { en: 'Architecture', vn: 'Công trình kiến trúc', category: 'Home & Living' },
  { en: 'Archive', vn: 'Kho lưu trữ hồ sơ tài liệu', category: 'Tech & AI' },
  { en: 'Arduous', vn: 'Gian gian, đòi hỏi nỗ lực lớn', category: 'Work & Career' },
  { en: 'Argumentative', vn: 'Thích tranh luận, hay tranh cãi', category: 'Public Speaking' },
  { en: 'Aristocracy', vn: 'Tầng lớp quý tộc', category: 'History & World' },
  { en: 'Arithmetic', vn: 'Môn toán số học', category: 'Education' },
  { en: 'Aroma', vn: 'Hương thơm quyến rũ', category: 'Food & Dining' },
  { en: 'Aromatic', vn: 'Có mùi thơm ngát', category: 'Food & Dining' },
  { en: 'Arrangement', vn: 'Sự sắp xếp, thỏa thuận', category: 'Work & Career' },
  { en: 'Arrogant', vn: 'Kiêu ngạo, tự cao', category: 'Psychology' },
  { en: 'Articulate', vn: 'Diễn đạt trôi chảy, rõ ràng', category: 'Public Speaking' },
  { en: 'Artificial', vn: 'Nhân tạo, không tự nhiên', category: 'Tech & AI' },
  { en: 'Artistic', vn: 'Mang tính nghệ thuật cao', category: 'Arts & Culture' },
  { en: 'Ascendancy', vn: 'Vị thế thế lực đi lên', category: 'History & World' },
  { en: 'Ascertain', vn: 'Xác minh chắc chắn', category: 'Science & Space' },
  { en: 'Aspiration', vn: 'Khát vọng, hoài bão lớn', category: 'Future & Goals' },
  { en: 'Assemble', vn: 'Lắp ráp thiết bị, tập hợp', category: 'Work & Career' },
  { en: 'Assembly', vn: 'Hội đồng, sự lắp ráp', category: 'Work & Career' },
  { en: 'Assertion', vn: 'Sự khẳng định đĩnh đạc', category: 'Public Speaking' },
  { en: 'Assessment', vn: 'Bài đánh giá năng lực', category: 'Education' },
  { en: 'Asset', vn: 'Tài sản có giá trị', category: 'Finance' },
  { en: 'Assignment', vn: 'Nhiệm vụ, bài tập được giao', category: 'Education' },
  { en: 'Assimilate', vn: 'Đồng hóa, tiếp thu kiến thức', category: 'News & Society' },
  { en: 'Assistance', vn: 'Sự hỗ trợ, giúp đỡ', category: 'Work & Career' },
  { en: 'Assistant', vn: 'Trợ lý cá nhân', category: 'Work & Career' },
  { en: 'Association', vn: 'Hiệp hội, tổ chức liên kết', category: 'News & Society' },
  { en: 'Assumption', vn: 'Giả định, sự thừa nhận', category: 'Philosophy' },
  { en: 'Assurance', vn: 'Sự bảo đảm, cam đoan', category: 'Law & Ethics' },
  { en: 'Astonishing', vn: 'Đáng kinh ngạc, sững sờ', category: 'Psychology' },
  { en: 'Astronomy', vn: 'Thiên văn học nghiên cứu vũ trụ', category: 'Science & Space' },
  { en: 'Astrophysics', vn: 'Vật lý thiên văn', category: 'Science & Space' },
  { en: 'Atmosphere', vn: 'Bầu không khí, khí quyển', category: 'Environment' },
  { en: 'Atmospheric', vn: 'Thuộc về khí quyển', category: 'Environment' },
  { en: 'Attachment', vn: 'Tệp đính kèm, sự gắn bó', category: 'Tech & AI' },
  { en: 'Attainment', vn: 'Thành tựu đạt được', category: 'Future & Goals' },
  { en: 'Attendance', vn: 'Sự có mặt điểm danh', category: 'Education' },
  { en: 'Attendant', vn: 'Tiếp viên phục vụ', category: 'Travel & Tourism' },
  { en: 'Attention', vn: 'Sự chú ý tập trung', category: 'Daily Life' },
  { en: 'Attentive', vn: 'Chăm chú, ân cần', category: 'Psychology' },
  { en: 'Attitude', vn: 'Thái độ sống', category: 'Psychology' },
  { en: 'Attorney', vn: 'Luật sư bào chữa', category: 'Law & Ethics' },
  { en: 'Attraction', vn: 'Điểm du lịch thu hút', category: 'Travel & Tourism' },
  { en: 'Attractive', vn: 'Hấp dẫn, lôi cuốn', category: 'Shopping & Style' },
  { en: 'Attribute', vn: 'Thuộc tính, quy cho là do', category: 'Science & Space' },
  { en: 'Auction', vn: 'Buổi đấu giá tài sản', category: 'Finance' },
  { en: 'Audience', vn: 'Khán thính giả lắng nghe', category: 'Public Speaking' },
  { en: 'Auditorium', vn: 'Hội trường biểu diễn lớn', category: 'Education' },
  { en: 'Augmentation', vn: 'Sự tăng cường gia tăng', category: 'Tech & AI' },
  { en: 'Authentic', vn: 'Đích thực, chính hãng', category: 'Arts & Culture' },
  { en: 'Authenticity', vn: 'Tính chân thực cao', category: 'Arts & Culture' },
  { en: 'Authority', vn: 'Chính quyền, thẩm quyền', category: 'Law & Ethics' },
  { en: 'Authorization', vn: 'Sự cấp phép chính thức', category: 'Law & Ethics' },
  { en: 'Autobiography', vn: 'Cuốn tự truyện cá nhân', category: 'Arts & Culture' },
  { en: 'Automated', vn: 'Được tự động hóa', category: 'Tech & AI' },
  { en: 'Automatic', vn: 'Tự động vận hành', category: 'Tech & AI' },
  { en: 'Automation', vn: 'Sự tự động hóa hoàn toàn', category: 'Tech & AI' },
  { en: 'Autonomous', vn: 'Tự chủ, tự hành không lái', category: 'Tech & AI' },
  { en: 'Autonomy', vn: 'Quyền tự chủ độc lập', category: 'Philosophy' },
  { en: 'Availability', vn: 'Sự có sẵn khả dụng', category: 'Work & Career' },
  { en: 'Avalanche', vn: 'Trận tuyết lở nguy hiểm', category: 'Safety & Emergency' },
  { en: 'Avoidance', vn: 'Sự tránh né né tránh', category: 'Health & Mind' },
  { en: 'Awakening', vn: 'Sự thức tỉnh nhận thức', category: 'Psychology' },
  { en: 'Awareness', vn: 'Sự nhận thức nâng cao', category: 'Psychology' },
  { en: 'Awesome', vn: 'Tuyệt vời ấn tượng', category: 'Daily Life' },
  { en: 'Awkwardness', vn: 'Sự ngượng ngùng vụng về', category: 'Psychology' }
];

console.log("COMMON_3000_VOCAB_BANK seed count:", COMMON_3000_VOCAB_BANK.length);
`;

console.log("Supercharging game generators...");
